### ISSUE TITLE
Mac OS Support

### ISSUE THREAD

**Issue by EliasDeuss** [AgoraIO/Agora-Flutter-SDK#124]

**Comment by LichKing-2234** [comment]
I plan to support windows and mac, but no so fast.

**Comment by macnibblet** [comment]
Following this as well, really looking forward to desktop support!

**Comment by rgb1380** [comment]
Any timeframe on this? An estimate will suffice and help us with planning. Thanks

**Comment by Sunbreak** [comment]
Try https://github.com/woodemi/Flutter-SDK-Desktop and https://github.com/woodemi/Flutter-RTM-Desktop

**Comment by LichKing-2234** [comment]
@rgb1380 It will start in Q4

**Comment by toklive** [comment]
Any update on Flutter desktop support?

**Comment by LichKing-2234** [comment]
allready support

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO/Agora-Flutter-SDK/issues/309
