### ISSUE TITLE
Error with Firebase User UID

### ISSUE THREAD

**Issue by chilex111** [AgoraIO/Agora-Flutter-SDK#189]
Hi, 
I keep getting the error message below. from the firebase I am getting a `long` digit instead of an `int`, how do I move out from this issue?
The log keep pointing to this code: 
```
  await AgoraRtcEngine.joinChannel(
        null, widget.selectedClass.classTitle, null, _authenticationService.currentUser.numberId);
```
`
E/MethodChannel#agora_rtc_engine(30185): Failed to handle method call
E/MethodChannel#agora_rtc_engine(30185): java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
E/MethodChannel#agora_rtc_engine(30185): 	at io.agora.agorartcengine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.java:138)
E/MethodChannel#agora_rtc_engine(30185): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#agora_rtc_engine(30185): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#agora_rtc_engine(30185): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#agora_rtc_engine(30185): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#agora_rtc_engine(30185): 	at android.os.MessageQueue.next(MessageQueue.java:331)
E/MethodChannel#agora_rtc_engine(30185): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#agora_rtc_engine(30185): 	at android.app.ActivityThread.main(ActivityThread.java:6518)
E/MethodChannel#agora_rtc_engine(30185): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#agora_rtc_engine(30185): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#agora_rtc_engine(30185): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (30185): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.Long cannot be cast to java.lang.Integer, null)
E/flutter (30185): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (30185): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (30185): <asynchronous suspension>
E/flutter (30185): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (30185): #3      AgoraRtcEngine.joinChannel (package:agora_rtc_engine/agora_rtc_engine.dart:459:41)
E/flutter (30185): #4      _WatchLiveStreamViewState.initialize (package:myfitlyfe/ui/views/watch_livestream_view.dart:82:26)
E/flutter (30185): <asynchronous suspension>
E/flutter (30185): #5      _WatchLiveStreamViewState.initState (package:myfitlyfe/ui/views/watch_livestream_view.dart:58:5)
E/flutter (30185): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (30185): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (30185): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (30185): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (30185): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (30185): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (30185): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (30185): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (30185): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (30185): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (30185): #26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (30185): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (30185): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (30185): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter (30185): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (30185): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (30185): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter (30185): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (30185): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (30185): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter (30185): #40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (30185): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter (30185): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter (30185): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.d`

**Comment by LichKing-2234** [comment]
our uid must be int, may be you can use stringUid, `joinChannelWithUserAccount`

**Comment by chilex111** [comment]
Ok, let me try it out, thank you @LichKing-2234

**Comment by chilex111** [comment]
@LichKing-2234  if I call` joinChannelWithUserAccount` does that mean I will not need to call the agora event handler like `AgoraRtcEngine.onJoinChannelSuccess` and `AgoraRtcEngine.onUserJoined`?
Because at the moment after replacing :
```
await AgoraRtcEngine.joinChannel(
        null, widget.selectedClass.classTitle, null, _authenticationService.currentUser.numberId);
``` 
**with** 
 ```
var result = {
      "userAccount": '${_authenticationService.currentUser.numberId}',
      "token": null,
      "channelId": widget.selectedClass.classTitle,
    };
    await AgoraRtcEngine.joinChannelByUserAccount(result);
``` I am still getting error

**Comment by LichKing-2234** [comment]
the error seems like from `FirestoreService`
