### ISSUE TITLE
setCameraFocusPositionInPreview does not keep the focus on Android

### ISSUE THREAD

**Issue by iNima** [AgoraIO/Agora-Flutter-SDK#195]
**Describe the bug**
Setting the focus position in preview does not work as expected on Android but it works perfectly on iOS. When I tap the view to focus it does focus but just for a fraction of time and then the focus comes back to what it was before tapping.

**To Reproduce**
1. Wrap the video view with a `GestureDetector`.
2. implement `onTapDown`.
3. set CameraFocusPositionInPreview with the `localPosition` values.

**Expected behavior**
The camera view should change its focus based on where the user taps on the view and keep that focus.

**Smartphone:**
 - Device: Pixel3a, Samsung S20
 - OS: Android 10
 - Version of Agora: 3.1.2
- Version of Flutter: 1.22.0 Stable channel

```
GestureDetector(
    child: cameraView,
    onTapDown: (details) async {
        await _rtcEngine.setCameraFocusPositionInPreview(details.localPosition.dx, details.localPosition.dy);
    },
)
```

**Comment by LichKing-2234** [comment]
the system camera works?

**Comment by iNima** [comment]
@LichKing-2234 By system camera if you mean the native camera or flutter camera plugin, yes, it works.

**Comment by iNima** [comment]
@LichKing-2234 Is there any update on this issue?

**Comment by LichKing-2234** [comment]
can you receive `cameraFocusAreaChanged` event?

**Comment by iNima** [comment]
Yes, I receive `cameraFocusAreaChanged`. 
As I mentioned before the same code works correctly on iOS but not on Android.

**Comment by LichKing-2234** [comment]
receive `cameraFocusAreaChanged` also on Android?

**Comment by iNima** [comment]
@LichKing-2234 Yes I receive it on Android as well.

**Comment by LichKing-2234** [comment]
so, you can receive `cameraFocusAreaChanged` both on Android and iOS, but not work on Android when previewing the local video?

**Comment by iNima** [comment]
@LichKing-2234 Yes exactly, on Android it happens in this way, it does focus but just for a fraction of time, it keeps the focus, then the focus comes back to what it was before tapping.
(In this situation the `cameraFocusAreaChanged` receives once)

**Comment by LichKing-2234** [comment]
by the way, `isCameraFocusSupported` return true or false?

**Comment by iNima** [comment]
@LichKing-2234 it returns true.

**Comment by LichKing-2234** [comment]
could you pls record a video? I will send it to our native SDK developer.

**Comment by iNima** [comment]
@LichKing-2234 Sure, Please send this video to them.
[focusIssue.zip](https://github.com/AgoraIO/Flutter-SDK/files/5388304/focusIssue.zip)

**Comment by LichKing-2234** [comment]
@iNima seems like a bug on some device, have you try on other devices?

**Comment by iNima** [comment]
@LichKing-2234 It works on all iOS devices. The issue is happening on Android devices. I tested on Samsung S20 and Pixel3a

**Comment by LichKing-2234** [comment]
@iNima could you pls test on other android devices? It works on my device.

**Comment by iNima** [comment]
@LichKing-2234 Sorry, I only have those two Android phones which didn't work for them.

**Comment by plutoless** [comment]
@iNima sorry for late reply. i would suggest you to ignore it for now if you don't have more phones to test. it might just be sth wrong with your cam.
