### ISSUE TITLE
进入一个两人房间，app切换到后台再切回来会偶现视频渲染异常

### ISSUE THREAD

**Issue by shop987** [AgoraIO/Agora-Flutter-SDK#210]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shop987** [comment]
安卓机型，红米手机

**Comment by LichKing-2234** [comment]
能详细描述下现象么
