### ISSUE TITLE
Expose SDK setExternalAudioSource methods

### ISSUE THREAD

**Issue by dgilperez** [AgoraIO/Agora-Flutter-SDK#215]
**Is your feature request related to a problem? Please describe.**

Agora SDK allows for external audio source selection (ie external mic) but the flutter package does not expose it. https://docs.agora.io/en/Interactive%20Broadcast/custom_audio_android?platform=Android

**Describe the solution you'd like**

I'd like either to have access to that part of the SDK from the flutter code, or a workaround to use an external mic. 

**Additional context**

There was a previous PR but it's closed with no further context. https://github.com/AgoraIO/Flutter-SDK/pull/142

**Comment by LichKing-2234** [comment]
you should not export `setExternalAudioSource` method to the dart layer. you can implement it on the native layer, and just export some methods such as `enableCustomAudioCapture`.

**Comment by dgilperez** [comment]
Thanks @LichKing-2234 for answering! 

I'm not very experienced on the native layer, that's one of the reasons we chose dart / flutter for our project. 

I'm a bit confused: is there a reason to not be able to control audio sources from the dart layer? I'd say that the flutter SDK should enable all potential capabilities from Agora, ideally - it's just a matter of extending the package. I'd love to send a PR but I don't think I'm experienced enought. I'm curious what could be the reasons to think otherwise. 

If that should be done natively, can you please point me to the right direction? Is there some documentation I could use? 

Thanks again!

**Comment by LichKing-2234** [comment]
you can refer to https://docs.agora.io/en/Voice/custom_audio_android?platform=Android

**Comment by dgilperez** [comment]
Hi @LichKing-2234 this requirement popped up again in our priority list. 

Our users would like to be able to use their external microphones on their mobile devices while using our App (flutter app). Re-reading your response, I don't understand the limitation of flutter on the external audio source 

* Is it just not implemented and you would consider accepting a PR? 
* Or is it something you don't want to support in flutter for some reason? In this case, would that force us to drop the flutter dependency and reimplement this part of the App natively in Android / iOS, or is there another solution to support external sources with flutter? 

Thanks!

**Comment by LichKing-2234** [comment]
1. this is a customized requirement, I think it may be different with different customers. if it can be designed for all of the customers, then I'd like to accept the PR.
2. custom audio/video source needs the developer to implement the Java/OC code. I suggest you fork our repository and implement your requirement on your repository which you have forked.

**Comment by dgilperez** [comment]
Thanks! I assumed external mic should be something straight forward, I now understand it's not. 

Looking at the available forks, I see @truyenjc has some strong developments in this line. Would you be so kind to share if they are production ready? Would it make sense for @LichKing-2234 to add some of those improvements to the base project in a PR? 

I'd be glad to collaborate in anything I can, testing or fixing things. 

Thanks again for a nice product!

**Comment by plutoless** [comment]
@dgilperez sorry for late reply. we will discuss internally how we will support this and maybe provide roadmap. but this will not come up very soon due to our schedule.

**Comment by dgilperez** [comment]
Hi @plutoless! just pinging to check the status for this. Again, I'd be glad to beta test any improvement you have in this line.

**Comment by dgilperez** [comment]
Ping @plutoless ! Could you provide an update, please?

**Comment by silversquall** [comment]
@plutoless @LichKing-2234 This feature is also very important for our project.
when could we expect it ? 
thanks.

**Comment by LichKing-2234** [comment]
you can refer to our native example and add it on the native layer.

**Comment by LichKing-2234** [comment]
Support it.
