### ISSUE TITLE
IOS Locked state call not connected sometimes

### ISSUE THREAD

**Issue by YuvarajaCPR** [AgoraIO/Agora-Flutter-SDK#216]
Problem
-For sometime if app is in locked state, then user will receive the call and after attend the call, video room get open but user will not connect to video room. In some case the video is connected

Installation
-Version 3.1.3
- Device IOS

Expected behavior
-If the app is in locked state and if user attend the call the Video Room should connect each other

**Comment by LichKing-2234** [comment]
have you do this https://github.com/AgoraIO/Flutter-SDK/issues/28#issuecomment-717667342?

**Comment by YuvarajaCPR** [comment]
Yeah, I already done that configuration

**Comment by LichKing-2234** [comment]
after done that configuration, you can keep chat in background mode. but if you want to keep the network connecting and wait for the invitation to chat, I think you should use [`PushKit`](https://developer.apple.com/documentation/pushkit/responding_to_voip_notifications_from_pushkit)

**Comment by YuvarajaCPR** [comment]
I use 'flutter_ios_voip_kit: ^0.0.5'  for PushKit

**Comment by plutoless** [comment]
@YuvarajaCPR do you have sdk logs for when you reproduced the issue?

**Comment by YuvarajaCPR** [comment]
@plutoless  sorry I don't have sdk logs

**Comment by plutoless** [comment]
@YuvarajaCPR it would be difficult for us to investigate w/o logs. do you recall the channel name in which the issue happened and date time? maybe i can try searching our backend

**Comment by LichKing-2234** [comment]
you can refer to the `setLogFile` method to get more information.

I will close this issue, you can reopen it if the issue still exists.
