### ISSUE TITLE
Switch audio source

### ISSUE THREAD

**Issue by theSharpestTool** [AgoraIO/Agora-Flutter-SDK#218]
Is there any way to switch between audio input/output sources? For example, if I have connected Bluetooth headphones and I need to switch audio playback to the phone speaker. 
I've tried to use `setEnableSpeakerphone` when the headphones are connected, but it had no effect. My profiles are `ChannelProfile.Communication`, `AudioProfile.Default`, `AudioScenario.Default`.

**Comment by plutoless** [comment]
have you received AudioRouteChanged  callback?

**Comment by shashikantdurge** [comment]
| iOS | Android
-- | -- | --
Autoswitch for Broadcasters |  YES | NO(*1)
Autoswitch for Audiences | YES  |  YES
audioRouteChanged callback | YES  | NO(*2)

*1 - Works if the audio scenario is Game streaming
*2 - It is inconsistent and cannot be relied upon. I've tested in LiveBroadcast as Audience, although auto switch works fine, the audioRouteChanged is not called.

**Comment by LichKing-2234** [comment]
seem like a known bug.
https://github.com/AgoraIO/Flutter-SDK/issues/27

**Comment by NarHakobyan** [comment]
We also have such problem!

**Comment by LichKing-2234** [comment]
pls follow #27 and try the latest version.
