### ISSUE TITLE
Crash in Android

### ISSUE THREAD

**Issue by duy1998** [AgoraIO/Agora-Flutter-SDK#227]
**Describe the bug**
When run android crash
Log:
aunching lib/main.dart on sdk gphone x86 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(25415): FATAL EXCEPTION: main
E/AndroidRuntime(25415): Process: **************, PID: 25415
E/AndroidRuntime(25415): java.lang.RuntimeException: Unable to instantiate application **********.Application: java.lang.ClassNotFoundException: Didn't find class "***********.Application" on path: DexPathList[[zip file "/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/***********-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/**********-3jsTnI0AYh2Ih9OTFDq0VQ==/lib/x86, /data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/***********-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
E/AndroidRuntime(25415): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1244)
E/AndroidRuntime(25415): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683)
E/AndroidRuntime(25415): 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
E/AndroidRuntime(25415): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
E/AndroidRuntime(25415): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25415): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(25415): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(25415): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25415): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(25415): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(25415): Caused by: java.lang.ClassNotFoundException: Didn't find class "***********************.Application" on path: DexPathList[[zip file "/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/***********************.-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/***********************.-3jsTnI0AYh2Ih9OTFDq0VQ==/lib/x86, /data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/***********************.-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
E/AndroidRuntime(25415): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(25415): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(25415): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(25415): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
E/AndroidRuntime(25415): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
E/AndroidRuntime(25415): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
E/AndroidRuntime(25415): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
E/AndroidRuntime(25415): 	... 9 more

Manifest file 
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="**********">

    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    
    
    <uses-permission android:name="android.permission.BLUETOOTH" />

    
    <application
        android:name=".Application"
        android:fullBackupContent="@xml/backup_descriptor"
        android:icon="@mipmap/ic_launcher"
        android:label="****"
        android:networkSecurityConfig="@xml/network_security_config"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:usesCleartextTraffic="true"
        tools:ignore="GoogleAppIndexingWarning,UnusedAttribute"
        tools:replace="android:fullBackupContent">
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_noti_status_bar" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/color_noti_icon" />

        

        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize"
            tools:ignore="ExtraText">

            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background"
                />

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="******"
                    android:scheme="launch" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                <data
                    android:host="ngocdung.onelink.me"
                    android:scheme="https" />
            </intent-filter>
        </activity>

        <activity android:name="com.djgeo.majascan.g_scanner.QrCodeScannerActivity" />
        
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />

        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

build.gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
localPropertiesFile.withReader('UTF-8') { reader ->
localProperties.load(reader)
}
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
compileSdkVersion 30
sourceSets {
main.java.srcDirs += 'src/main/kotlin'
}

lintOptions {
    disable 'InvalidPackage'
}

defaultConfig {
 
    applicationId "*******************"
    minSdkVersion 24
    targetSdkVersion 30
    multiDexEnabled true
    versionCode flutterVersionCode.toInteger()
    versionName flutterVersionName
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    proguardFiles
}

// buildTypes {
//     release {
//         // TODO: Add your own signing config for the release build.
//         // Signing with the debug keys for now, so `flutter run --release` works.
//         signingConfig signingConfigs.debug
//     }
// }
signingConfigs {
   release {
       keyAlias keystoreProperties['keyAlias']
       keyPassword keystoreProperties['keyPassword']
       storeFile file(keystoreProperties['storeFile'])
       storePassword keystoreProperties['storePassword']
   }
}
buildTypes {
release {

       signingConfig signingConfigs.release

       minifyEnabled true
       useProguard true

       proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
}

flutter {
source '../..'
}

dependencies {
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
implementation "com.google.firebase:firebase-messaging:20.2.4"
implementation "androidx.multidex:multidex:2.0.1"
testImplementation 'junit:junit:4.12'
androidTestImplementation 'androidx.test🏃1.2.0'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

}
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'

**Comment by LichKing-2234** [comment]
I can not get any log about our SDK? it may crash because of another reason?

**Comment by duy1998** [comment]
> **Describe the bug**
> When run android crash
> Log:
> aunching lib/main.dart on sdk gphone x86 in debug mode...
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
> E/AndroidRuntime(25415): FATAL EXCEPTION: main
> E/AndroidRuntime(25415): Process: _**_**********, PID: 25415 E/AndroidRuntime(25415): java.lang.RuntimeException: Unable to instantiate application **********.Application: java.lang.ClassNotFoundException: Didn't find class "**********_.Application" on path: DexPathList[[zip file "/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/**_********-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/**********-3jsTnI0AYh2Ih9OTFDq0VQ==/lib/x86, /data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/********_**-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]] E/AndroidRuntime(25415): at android.app.LoadedApk.makeApplication(LoadedApk.java:1244) E/AndroidRuntime(25415): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683) E/AndroidRuntime(25415): at android.app.ActivityThread.access$1300(ActivityThread.java:237) E/AndroidRuntime(25415): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) E/AndroidRuntime(25415): at android.os.Handler.dispatchMessage(Handler.java:106) E/AndroidRuntime(25415): at android.os.Looper.loop(Looper.java:223) E/AndroidRuntime(25415): at android.app.ActivityThread.main(ActivityThread.java:7656) E/AndroidRuntime(25415): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(25415): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) E/AndroidRuntime(25415): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) E/AndroidRuntime(25415): Caused by: java.lang.ClassNotFoundException: Didn't find class "**_********************.Application" on path: DexPathList[[zip file "/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/********************_**.-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/**_********************.-3jsTnI0AYh2Ih9OTFDq0VQ==/lib/x86, /data/app/~~5JQA1JAzE9P_cYTY-eh5Vg==/***********************.-3jsTnI0AYh2Ih9OTFDq0VQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
> E/AndroidRuntime(25415): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
> E/AndroidRuntime(25415): at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> E/AndroidRuntime(25415): at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> E/AndroidRuntime(25415): at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
> E/AndroidRuntime(25415): at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
> E/AndroidRuntime(25415): at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
> E/AndroidRuntime(25415): at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
> E/AndroidRuntime(25415): ... 9 more
> 
> Manifest file
> 
> ```
> 
> <uses-permission android:name="android.permission.INTERNET" />
> <uses-permission android:name="android.permission.CAMERA" />
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
> <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
> <uses-permission android:name="android.permission.VIBRATE" />
> <uses-permission android:name="android.permission.WAKE_LOCK" />
> 
> <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
> <uses-permission android:name="android.permission.RECORD_AUDIO" />
> <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
> 
> 
> <uses-permission android:name="android.permission.BLUETOOTH" />
> 
> 
> <application
>     android:name=".Application"
>     android:fullBackupContent="@xml/backup_descriptor"
>     android:icon="@mipmap/ic_launcher"
>     android:label="****"
>     android:networkSecurityConfig="@xml/network_security_config"
>     android:roundIcon="@mipmap/ic_launcher_round"
>     android:usesCleartextTraffic="true"
>     tools:ignore="GoogleAppIndexingWarning,UnusedAttribute"
>     tools:replace="android:fullBackupContent">
>     <meta-data
>         android:name="com.google.firebase.messaging.default_notification_channel_id"
>         android:value="@string/default_notification_channel_id" />
> 
>     <meta-data
>         android:name="com.google.firebase.messaging.default_notification_icon"
>         android:resource="@drawable/ic_noti_status_bar" />
> 
>     <meta-data
>         android:name="com.google.firebase.messaging.default_notification_color"
>         android:resource="@color/color_noti_icon" />
> 
>     
> 
>     <activity
>         android:name=".MainActivity"
>         android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>         android:hardwareAccelerated="true"
>         android:launchMode="singleTop"
>         android:theme="@style/LaunchTheme"
>         android:windowSoftInputMode="adjustResize"
>         tools:ignore="ExtraText">
> 
>         <meta-data
>             android:name="io.flutter.embedding.android.SplashScreenDrawable"
>             android:resource="@drawable/launch_background"
>             />
> 
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
> 
>         
>         <intent-filter>
>             <action android:name="FLUTTER_NOTIFICATION_CLICK" />
>             <category android:name="android.intent.category.DEFAULT" />
>         </intent-filter>
> 
>         <intent-filter>
>             <action android:name="android.intent.action.VIEW" />
> 
>             <category android:name="android.intent.category.DEFAULT" />
>             <category android:name="android.intent.category.BROWSABLE" />
> 
>             <data
>                 android:host="******"
>                 android:scheme="launch" />
>         </intent-filter>
>         <intent-filter android:autoVerify="true">
>             <action android:name="android.intent.action.VIEW" />
> 
>             <category android:name="android.intent.category.DEFAULT" />
>             <category android:name="android.intent.category.BROWSABLE" />
>             
>             <data
>                 android:host="ngocdung.onelink.me"
>                 android:scheme="https" />
>         </intent-filter>
>     </activity>
> 
>     <activity android:name="com.djgeo.majascan.g_scanner.QrCodeScannerActivity" />
>     
>     <meta-data
>         android:name="com.facebook.sdk.ApplicationId"
>         android:value="@string/facebook_app_id" />
> 
>     <activity
>         android:name="com.facebook.FacebookActivity"
>         android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
>         android:label="@string/app_name" />
> 
>     <activity
>         android:name="com.facebook.CustomTabActivity"
>         android:exported="true">
>         <intent-filter>
>             <action android:name="android.intent.action.VIEW" />
> 
>             <category android:name="android.intent.category.DEFAULT" />
>             <category android:name="android.intent.category.BROWSABLE" />
> 
>             <data android:scheme="@string/fb_login_protocol_scheme" />
>         </intent-filter>
>     </activity>
> 
>     <meta-data
>         android:name="flutterEmbedding"
>         android:value="2" />
> </application>
> ```

build.gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 30
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }
    
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "*******************"
        minSdkVersion 24
        targetSdkVersion 30
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        proguardFiles
    }

    // buildTypes {
    //     release {
    //         // TODO: Add your own signing config for the release build.
    //         // Signing with the debug keys for now, so `flutter run --release` works.
    //         signingConfig signingConfigs.debug
    //     }
    // }
    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {

           signingConfig signingConfigs.release

           minifyEnabled true
           useProguard true

           proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
   }
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.google.firebase:firebase-messaging:20.2.4"
    implementation "androidx.multidex:multidex:2.0.1"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    
}
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'

**Comment by duy1998** [comment]
> I can not get any log about our SDK? it may crash because of another reason?

I updated build.gradle. thank you

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
