### ISSUE TITLE
在Flutter 1.26.0-1.0.pre 不能运行

### ISSUE THREAD

**Issue by gdwenjun** [AgoraIO/Agora-Flutter-SDK#234]
flutter --version
Flutter 1.26.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63062a6443 (2 weeks ago) • 2020-12-13 23:19:13 +0800
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)

在**ios目录**下执行pod install报错。
gavinwjwang@GAVINWJWANG-MB1 example/ios (master *) » pod install 

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/gavinwjwang/work/GitHub/Agora-Flutter-SDK/example/ios/Podfile:57
 #  -------------------------------------------
 #      unless File.exist?(copied_framework_path)
 >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
 #      end

直接运行的话也报下面错误
CocoaPods' output:
↳
    [!] Invalid `Podfile` file: no implicit conversion of nil into String.
     #  from /Users/gavinwjwang/work/GitHub/Agora-Flutter-SDK/example/ios/Podfile:57
     #  -------------------------------------------
     #      unless File.exist?(copied_framework_path)
     >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
     #      end
     #  -------------------------------------------

**Comment by LichKing-2234** [comment]
看起来是flutter本身的问题，只有我们的demo无法运行？
还有尝试下换成其他版本的flutter以及`flutter clean`再试试.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
