### ISSUE TITLE
ErrorCode.InvalidAppId

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#235]
I'm getting ErrorCode.InvalidAppId. I copy the app id from agora and paste it there but it shows me this error.
please let me know how to resolve this issue

**Comment by LichKing-2234** [comment]
pls double check it.

btw, where you got this error

**Comment by ziasultan2** [comment]
> pls double check it.
> 
> btw, where you got this error

In the app screen it shows me this error with yellow container background

**Comment by LichKing-2234** [comment]
My mistake, I mean which method did you call report the error

**Comment by ziasultan2** [comment]
Thank you for your reply. I'm not sure I just copy the files from agora flutter quickstart project and add it to my project

**Comment by LichKing-2234** [comment]
is our quickstart working fine?

**Comment by ziasultan2** [comment]
I'm not sure I copy the lib folder files to my current project. Here is the screenshot of error. Please check the image
https://ibb.co/xzcWqth

**Comment by LichKing-2234** [comment]
you can try our quickstart or our web demo

https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/

**Comment by ziasultan2** [comment]
Thank you dear the issue was with token I used primary token. Is there any way I can use primary token in my app so that I don't have to create token everytime I create a call

**Comment by ziasultan2** [comment]
Hi dear Is there any way to make video size as like skype or facebook and toggle their position like the caller will have a small square box screen it top right and the receiver will cover the whole screen

**Comment by LichKing-2234** [comment]
just change the style of the render widget

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
