### ISSUE TITLE
sendMetadata is not working

### ISSUE THREAD

**Issue by ilyasmez** [AgoraIO/Agora-Flutter-SDK#236]
**Describe the bug**
Can't send a metadata.

**To Reproduce**
Try sending some metadata using
```dart
rtcEngine.sendMetadata('test')
```
The metadata is not sent to the other users and this error is shown in the console:
```
E/flutter (29530): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(7, not initialized, null, null)
E/flutter (29530): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (29530): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (29530): <asynchronous suspension>
E/flutter (29530): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (29530): #3      RtcEngine._invokeMethod (package:agora_rtc_engine/src/rtc_engine.dart:35:27)
E/flutter (29530): #4      RtcEngine.sendMetadata (package:agora_rtc_engine/src/rtc_engine.dart:576:12)
```

**Expected behavior**
The metadata is being sent successfully, and caught by the other users using the `metadataReceived` event listener.

**Smartphone (please complete the following information):**
 - Device: Pixel 4 (physical),  and a few other emulated devices.
 - OS: Android 11

**Additional context**
Using `  agora_rtc_engine: 3.2.1`

**Comment by LichKing-2234** [comment]
PlatformException(7, not initialized, null, null)

you should init engine first

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LichKing-2234** [comment]
PlatformException(7, not initialized, null, null)

you should init engine first

**Comment by ilyasmez** [comment]
> PlatformException(7, not initialized, null, null)
> you should init engine first

Hi @LichKing-2234, thank you for the reply.

I'm initializing the engine before anything else:
```dart
_engine = await RtcEngine.create(AGORA_APP_ID);
await _engine.enableVideo();
await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await _engine.setClientRole(ClientRole.Audience);
```

I don't think this is the problem, because I try to send the metadata during an active live streaming.

**Comment by LichKing-2234** [comment]
Sorry, My mistake, you should  call `registerMediaMetadataObserver` first.

**Comment by ilyasmez** [comment]
Great thank you @LichKing-2234, the error is gone now.
But the metadata is still not received by the other users. The string is really short, so it's probably not the due to the size.
I'm trying to send the metadata from the broadcaster to the audience, in case this matters.

This is a simplified snippet:
```dart
RtcEngine _engine;

Future<void> initializeAgora() async {
  _engine = await RtcEngine.create(AGORA_APP_ID);

  _engine.setEventHandler(RtcEngineEventHandler(
    metadataReceived: (buffer, _, __) {
      print('Metadata received $buffer');
    },
  ));

  await _engine.registerMediaMetadataObserver();
} 

Future<void> sendAgoraMetadata() async {
  await _engine.sendMetadata( 'test');
} 
```

And `sendAgoraMetadata` is called during the video call.
The "Metadata received" is never printed for any user.

**Comment by LichKing-2234** [comment]
maybe you should call `setMaxMetadataSize`

**Comment by elricym** [comment]
I find the same issue which I can't receive any metadata sent. Could you tell me the solution about this? Thank you.

**Comment by hovanhung98hust** [comment]
> Sorry, my mistake, you should call `registerMediaMetadataObserver` first.

this work for me. Thanks

**Comment by Miko2x** [comment]
Hi @ilyasmez have you found the solution for this?

**Comment by Miko2x** [comment]
@hovanhung98hust  same to me, have you found the solution?
I'm using version is 5.3.1.
CC: @littleGnAl

**Comment by littleGnAl** [comment]
@Miko2x Can you please raise a new issue for your case, thanks.
