### ISSUE TITLE
add setVideoProfile to flutter package

### ISSUE THREAD

**Issue by DeanPack** [AgoraIO/Agora-Flutter-SDK#237]
Hello! Thank you for making this package to support agora in flutter apps, Everything is working great except I want to be able to set the video quality of the local view. We have an app that streams to hundreds of users at once and some of our users complain that it uses too much data. I want to be able to let the user lower the quality of their stream if they want to, but I noticed that setVideoProfile is not yet implemented. Here is an example of its use in the agora docs
https://pub.dev/packages/agora_rtc_engine/

I'd like to be able to call setVideoProfile on the users device and be able to let the user change their video quality to one of these
enum AgoraVideoResolution { P144, P240, P360, P480, P720, Auto }

Thank you!

**Comment by LichKing-2234** [comment]
setVideoProfile is deprecated, pls use setVideoEncoderConfiguration
