### ISSUE TITLE
该项目与agora_flutter_webrtc项目的区别是啥

### ISSUE THREAD

**Issue by shop987** [AgoraIO/Agora-Flutter-SDK#238]
flutter开发音视频应该基于哪个项目来进行开发呢

**Comment by LichKing-2234** [comment]
那个项目是dart版本的webrtc，给web用的

**Comment by shop987** [comment]
![image](https://user-images.githubusercontent.com/70259290/103844926-fa264400-50d5-11eb-85c8-58424434b67e.png)

我看基于flutter-webrtc也支持Android和iOS？

**Comment by LichKing-2234** [comment]
看你的需求吧，如果只是Android、iOS，还是不要用那个。那个没有产品化，只是个初版本，目前也没人维护 。

**Comment by shop987** [comment]
感觉这个项目还挺好的，可以跨更多平台，为什么没有产品化呢。是有什么性能问题吗

**Comment by shop987** [comment]
@LichKing-2234

**Comment by LichKing-2234** [comment]
@plutoless 麻烦你这边回复下

**Comment by plutoless** [comment]
@shop987 flutter webrtc的项目是直接基于原生webrtc的，很多端上的优化控制不到，所以可能的话还是建议用我们原生flutter sdk哈

**Comment by shop987** [comment]
了解了，感谢
