### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by ruikc** [AgoraIO/Agora-Flutter-SDK#243]
java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err( 9382): 	at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err( 9382): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err( 9382): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err( 9382): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err( 9382): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err( 9382): 	at libcore.io.Linux.open(Native Method)
W/System.err( 9382): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err( 9382): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err( 9382): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err( 9382): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
W/System.err( 9382): 	at libcore.io.IoBridge.open(IoBridge.java:478

**Comment by LichKing-2234** [comment]
which version you used

**Comment by ruikc** [comment]
> which version you used?

agora_rtc_engine: ^3.2.1
agora_rtm: ^0.9.14

**Comment by LichKing-2234** [comment]
it seems like you denied the `READ_EXTERNAL_STORAGE` permission

**Comment by ruikc** [comment]
![image](https://user-images.githubusercontent.com/7445875/105122132-9a398f80-5b10-11eb-9e4b-8f6973f72489.png)
![image](https://user-images.githubusercontent.com/7445875/105122154-a58cbb00-5b10-11eb-9e63-581fb8ea8c85.png)
added the permission ,question also

**Comment by LichKing-2234** [comment]
I mean `Permission.storage.request()`

**Comment by volskaya** [comment]
@LichKing-2234 Why is the plugin trying to read thermal and access storage for no reason?

**Comment by ruikc** [comment]
I/flutter (16474): Permission.storage 同意
I/flutter (16474): Permission.camera 同意
D/*WEBRTCN*(16474): SetRenderAndroidVM
I/VideoCapabilities(16474): Unsupported profile 4 for video/mp4v-es
D/HostConnection(16474): HostConnection::get() New Host Connection established 0xf1f64f20, tid 16579
I/CameraManagerGlobal(16474): Connecting to camera service
D/HostConnection(16474): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(16474): eglCreateContext: 0xf1f63390: maj 3 min 0 rcv 3
D/GDPGlUtil(16474): EGLContext created, client version 3
D/EGL_emulation(16474): eglMakeCurrent: 0xf1f63390: ver 3 0 (tinfo 0xba639f90) (first time)
I/GDPAndroid(16474): cores:4
I/chatty  (16474): uid=10155(com.ruikc.chat) GENP.0 identical 4 lines
I/GDPAndroid(16474): cores:4
I/GDPAndroid(16474): max freq:2
I/GDPAndroid(16474): total mem:2076913664
I/flutter (16474): 全局变量绑定成功
W/Gralloc4(16474): allocator 3.x is not supported
W/System.err(16474): java.io.FileNotFoundException: /sys/class/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(16474): 	at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err(16474): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err(16474): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(16474): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(16474): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(16474): 	at libcore.io.Linux.open(Native Method)
W/System.err(16474): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(16474): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err(16474): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(16474): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
W/System.err(16474): 	at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err(16474): 	... 3 more
W/System.err(16474): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(16474): 	at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err(16474): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err(16474): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(16474): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(16474): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(16474): 	at libcore.io.Linux.open(Native Method)
W/System.err(16474): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(16474): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err(16474): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(16474): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
W/System.err(16474): 	at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err(16474): 	... 3 more

**Comment by ruikc** [comment]
> I mean `Permission.storage.request()`

https://blog.csdn.net/z469571695/article/details/51498013

**Comment by LichKing-2234** [comment]
> @LichKing-2234 Why is the plugin trying to read thermal and access storage for no reason?

to get CPU usage.

**Comment by LichKing-2234** [comment]
@ruikc I have reported this issue to our native SDK team, I think it should not affect your normal use.

**Comment by ruikc** [comment]
> @ruikc I have reported this issue to our native SDK team, I think it should not affect your normal use.

OK

**Comment by LichKing-2234** [comment]
@ruikc which device do you use? I get the same log with the simulator but works on my phone.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.

**Comment by naveenbharadwaj19** [comment]
I'm facing the same issue. Any update ?

**Comment by LichKing-2234** [comment]
you can ignore this log, some devices can not get CPU usage from the Linux system file.
