### ISSUE TITLE
Video call filter like facebook and others

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#244]
Is there any way to add filter in video calling.
Please let me know

**Comment by LichKing-2234** [comment]
you can use [the raw-data plugin](https://github.com/LichKing-2234/flutter_agora_rtc_rawdata), and use it with third-party video filter SDK.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
