### ISSUE TITLE
audioVolumeIndication callbacks don't allow to distinguish if for remote or local user if the list of users is empty

### ISSUE THREAD

**Issue by silversquall** [AgoraIO/Agora-Flutter-SDK#247]
**Your doc says :**
 onAudioVolumeIndication() : 
`The SDK triggers TWO independent onAudioVolumeIndication callbacks simultaneously, which separately report the volume information of the local user who sends a stream and the remote users (up to three) whose instantaneous volumes are the highest.`

I see a problem for my use case as i need to know who is the loudest user ( including local & remote) :
If i receive 1 of the callbacks with empty list (i don't know if this is the callback for the remote user or local user unless i wait for the second callback but that's very tricky since i rely on streams). 

**I think the best solution**  --> A single callback containing both local & remote users, you do the job on your side and send us the result, i'ts clean and effective.  

**temporary solution** --> I suggest that you at least create  separated callbacks to distinguish them  (for instance onLocalAudioVolumeIndication & onRemoteAudioVolumeIndication) since their order of reception is not guaranteed 

Also i suggest that you mention in your note what occurs when you unmute the local user
```
Note
    After you enable this callback, calling muteLocalAudioStream affects the SDK's behavior as follows:

        If the local user calls muteLocalAudioStream, the SDK stops triggering the local user's callback.
        20 seconds after a remote user whose volume is one of the three highest calls muteLocalAudioStream, the remote users' callback excludes this remote user's information; 20 seconds after all remote users call muteLocalAudioStream, the SDK stops triggering the remote users' callback.
```

**Comment by LichKing-2234** [comment]
it means from remote if the callback did not contain uid 0.

**Comment by silversquall** [comment]
@LichKing-2234 you didn't get the question : when I receive a first onAudioVolumeIndication  with empty list of user, How do i know if i  if it is from remote or from local ??

**Comment by plutoless** [comment]
@silversquall i think enableAudioVolumeIndication has a parameter `interval`, you may set this value larger to get a better fit value.

**Comment by silversquall** [comment]
@plutoless unfortunately changing "interval" param doesn't help as it is applied for both remote & local at the same time.

Could you take in account a Single callback solution or temporary solution described above ? thx

**Comment by plutoless** [comment]
@silversquall a temporary solution would be set a 1 second timer, and every second you collect all callback results into an array and eventually accumulate a result. If no remote user ever talks(which is possible), you can fill in a struct with 0 values. In this case your application logic should be unified while using this info. as this is very use case specific so maybe it's more reasonable to do this in app level.

**Comment by silversquall** [comment]
@plutoless thanks for the workaround but in my case it is going to be complicated as i need enableAudioVolumeIndication  every 250 ms.
@LichKing-2234 @plutoless Can you at least add a new boolean param "fromLocal" or "fromRemote" in AudioVolumeCallback audioVolumeIndication ? 
Would be much apprecited otherwise without solution i'll just have to leave Agora for another alternative.
thank you.

**Comment by LichKing-2234** [comment]
@silversquall if you got an empty list of speakers, it means from remote. the local speakers must contain an `AudioVolumeInfo` for the local user which uid is 0.
![image](https://user-images.githubusercontent.com/9312526/107727055-67f10b80-6d25-11eb-90cb-eb65c8e19816.png)

**Comment by silversquall** [comment]
You can get empty list of speakers for both remote and local user, so how do you make the distinction ? 
I proposed some solution above.

**Comment by LichKing-2234** [comment]
The list of speakers for the local user should not be empty.

**Comment by silversquall** [comment]
but it is, I have done tests on my side !
can you please check on your side ?

**Comment by LichKing-2234** [comment]
@silversquall could you pls make a demo for it, I will test your code.

**Comment by silversquall** [comment]
@LichKing-2234 The scenario is :

1) channel created
2) local user joins the channel and is muted
3) only one AgoraAudioVolume event is triggered with empty speakers list --> OK as expected
3) remote user joins the channel and is mutted
4) still only one AgoraAudioVolume event is triggered with empty speakers list --> KO i would expect another dedicated event triggered for remote users
5) local user unmutes (remote user is still mute)
6) 2 AgoraAudioVolume  are triggered : 1 event for local user with 1 speaker in the list, another event for remote users with empty speaker list
7) I mute local user
8) I unmute remote user 
9) 1 AgoraAudioVolume  event only is triggered for remote user, nothing for local user

--> you are threating steps 4 & 6 & 9 differently, sometimes you put 2 events, sometimes 1, the logic is completely crazy.
I recommand to 

- add a new param in AgoraAudioVolume  to know if the event is local or remote.
- Always trigger 2 events.

**Comment by LichKing-2234** [comment]
I will check it.

**Comment by silversquall** [comment]
@LichKing-2234 thanks this is blocking our release, looking forward for your reply.

**Comment by RoJoHub** [comment]
We are looking into the problem now. Just a moment, please

**Comment by RoJoHub** [comment]
> @LichKing-2234 thanks this is blocking our release, looking forward for your reply.

There are several situations here.

```
case 1:
local device mute
remote device unmute

audioVolumeIndication event will receive:
 - empty speakers list   :Remot user did not speak
 - [{uid:'xxx'}]:   Remote user is speaking

```



```
case 2:
local device unmute
remote device mute

audioVolumeIndication event will receive:
 - empty speakers list   :myself did not speak
 - [{uid:'0'}]:   myself is speaking

```


```
case 3
local device mute
remote device mute

audioVolumeIndication event will receive:
 - empty speakers list   :   because all ueser is mute

```

```
case 3
local device unmute
remote device unmute

audioVolumeIndication event will receive:
 - empty speakers list   :   all user is not speaking now
 -  [{uid:0}]   :   myself is speaking
 -  [{uid:xxx}]   :   remote user  is speaking
 -   [{uid:xxx},{uid:0}]   :   remote user  and myself  are speaking

```

**Comment by RoJoHub** [comment]
After my testing, our sdk conforms to these examples.
I hope this will help you!
@silversquall

**Comment by silversquall** [comment]
@RoJoHub In your exemple it is not clear how many events you generate and what is inside those events.
Can you add this info in your exemples above ?
thank you.
