### ISSUE TITLE
[IOS] If you mute your stream while playing an audio using Flutter's audioplayers, the audio sound will become really low

### ISSUE THREAD

**Issue by mirrorlink** [AgoraIO/Agora-Flutter-SDK#248]
**Describe the bug**
[IOS] If you mute your stream while playing an audio using Flutter's audioplayers, the audio sound will become really low.

**To Reproduce**
1. Connect to an agoraio room
2. Load and play an audio using AudioPlayers plugin ( https://pub.dev/packages/audioplayers )
3. Mute your own audio stream

**Expected behavior**
Muting your conference audio stream should not interfere with audioplayers playback.

**Smartphone (please complete the following information):**
 - IPad Pro
 - OS: 14.3

**Additional context**
Flutter audio plugin: https://pub.dev/packages/audioplayers

**Comment by LichKing-2234** [comment]
this is the iOS system behaves. you can try to control AudioSession by yourself.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
