### ISSUE TITLE
[IOS] Echo cancellation will stop working after coming from background on iOS.

### ISSUE THREAD

**Issue by mirrorlink** [AgoraIO/Agora-Flutter-SDK#249]
**Describe the bug**
 Echo cancellation will stop working after coming from background on iOS.

**To Reproduce**
1. Enter a session room with agoraIO.
2. With the iOS device, go to background, come back.
3. When app opens again, echo cancellation will stop working. Eg. All audio ios users receive from other people will start echoing in the mic.

**Expected behavior**
App should behave normally, with echo cancellation working.

**Smartphone (please complete the following information):**
 - Device: Iphone 12
 - OS: 14.3

**Comment by LichKing-2234** [comment]
could you pls provide our SDK log?

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
