### ISSUE TITLE
[IOS] Turning on/off local mic stream will stop app from receiving remote audio for a few seconds.

### ISSUE THREAD

**Issue by mirrorlink** [AgoraIO/Agora-Flutter-SDK#250]
**Describe the bug**
Turning on/off local mic stream will stop app from receiving remote audio for a few seconds.

**To Reproduce**
1. Connect to an agoraio session on iOS.
2. Have a friend start talking on another device.
3. Mute your own local stream on iOS while listening to your friend.
4. Notice that the remote audio from your friend will stop from 1 to 10 seconds.

**Expected behavior**
Muting local audio mic should not interfere with remote audio.

**Smartphone (please complete the following information):**
 - Device:  iPad Pro
 - OS: 14.3

**Comment by LichKing-2234** [comment]
could you pls provide our SDK log?

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
