### ISSUE TITLE
Plugin with id 'com.android.library' not found

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#252]
**Describe the bug**
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/johnsmith/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-3.2.1/android/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'agora_rtc_engine'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin agora_rtc_engine could not be built due to the issue above.

**Smartphone (please complete the following information):**
 - Android emulator

**Comment by LichKing-2234** [comment]
which folder did you open in AndroidStudio?

**Comment by ziasultan2** [comment]
I run it in visual studio. When I try to run in android emulator it shows me this error but in iOS emulator it works fine

**Comment by LichKing-2234** [comment]
maybe you can try to open the android project in android studio.

btw, could you pls provide the result from `flutter doctor`?

**Comment by ziasultan2** [comment]
Zia-Sultan:app Raymond$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.20.2 at /Users/johnsmith/Developer/flutter
    • Framework revision bbfbf1770c (6 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Raymond Tucker/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 8382A243-0357-4EAB-AE4E-6983C02AB556 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by sulaimanmmd6** [comment]
I fixed this using following step

- Open 'app' folder in Android Studio & it did gradle sync
- Migrate project to AndroidX
- Now try to run directly from Android Studio

It works for me.


Mistake I made:

I tried to use custom push notification icon, but it was an error for me (shown while building via android studio).

**Comment by NuHunter** [comment]
I have the same problem. I run it in Visual Studio Code. When I try to run in android emulator it shows me this error but in iOS emulator it works fine.

**Comment by NuHunter** [comment]
> I run it in visual studio. When I try to run in android emulator it shows me this error but in iOS emulator it works fine

I have the same problem.
