### ISSUE TITLE
Execution failed for task ':agora_rtc_engine:generateDebugRFile'.

### ISSUE THREAD

**Issue by bladeofgod** [AgoraIO/Agora-Flutter-SDK#254]
recently i got this problem:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:generateDebugRFile'.
> No non-density apk found

 thanks for help.

**Comment by LichKing-2234** [comment]
have you tried our example or quickstart?

**Comment by bladeofgod** [comment]
> have you tried our example or quickstart?

yes，lot of times.

**Comment by bladeofgod** [comment]
> have you tried our example or quickstart?

it happened on some android devices.

**Comment by LichKing-2234** [comment]
https://developer.android.com/studio/build/configure-apk-splits

**Comment by bladeofgod** [comment]
> Seems like you enable `splits.density`?
> https://developer.android.com/studio/build/configure-apk-splits

thanks for you reply,i will try it after vacation.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.

**Comment by Nijinsha** [comment]
Experiencing the same issue.
