### ISSUE TITLE
Can i create dynamic  token  inside flutter app?

### ISSUE THREAD

**Issue by KhayyamA47** [AgoraIO/Agora-Flutter-SDK#255]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LichKing-2234** [comment]
it is not safe, you should generate the token on your server.

**Comment by KhayyamA47** [comment]
I know,but i can't find way for create dynamic key inside flutter app anyway for testing

**Comment by LichKing-2234** [comment]
you can refer to https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey and make it with `dart`.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.
