### ISSUE TITLE
Audio choppy on 3.3.0-rc.0

### ISSUE THREAD

**Issue by imurnane** [AgoraIO/Agora-Flutter-SDK#259]
**Describe the bug**
Consistent choppy sounding audio. Like someone is tapping the microphone at about 10hz.
Note: I just downgraded to 3.2.1 and the audio is clear again.

**To Reproduce**
Create an audio only call

**Expected behavior**
Clear audio

**Smartphone (please complete the following information):**
Android app: (clear audio)
  Pixel 5 5G
  android library io.agora.rtc:voice-sdk:3.3.0

=> connected to

Flutter app: (choppy audio)
  Samsung Galaxy Grand Prime+
  Flutter library 3.3.0-rc.0

**Comment by plutoless** [comment]
hi @imurnane is there any chance you can make a recording to help us understand the phenomenon?
ideally one recording with 3.2.1 and one with 3.3.0

**Comment by imurnane** [comment]
> hi @imurnane is there any chance you can make a recording to help us understand the phenomenon?
> ideally one recording with 3.2.1 and one with 3.3.0

http://www.users.on.net/~imurnane/agora_rtc_engine_3.3.0.rc0-vs-3.2.1.mp3

**Comment by plutoless** [comment]
@imurnane thanks. and sorry for late reply. i'm taking this to our audio expert to diagnose.

**Comment by LichKing-2234** [comment]
you can refer to `setLogFile` method to get the log file.

I will close this issue, you can reopen it if it still exists.
