### ISSUE TITLE
请问fluttersdk是封装的声网的nativesdk还是websdk呢？

### ISSUE THREAD

**Issue by xinlee333** [AgoraIO/Agora-Flutter-SDK#262]
因为我看到官网上写着，websdk在某些平台上会有问题，比如ios设备商因为默认的webview都是Safari，声网websdk在ios的safari上会有很多问题，所以官方不建议使用。
那这个flutter的sdk是封装的nativesdk还是websdk呢？
谢谢。

**Comment by plutoless** [comment]
native sdk.

**Comment by xinlee333** [comment]
多谢！
