### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by VictorUvarov** [AgoraIO/Agora-Flutter-SDK#264]
**Is your feature request related to a problem? Please describe.**
Flutter stable now uses Dart 2.12.0 which supports sound null safety.

**Describe the solution you'd like**
Add support for null safety.

**Additional context**
Can start upgrading to null safety by updating SDK from `sdk: ">=2.7.0 <3.0.0"` to `sdk: ">=2.12.0 <3.0.0"` and running `dart migrate` on this package.

**Comment by fareesh** [comment]
I've tried to do it here #265
