### ISSUE TITLE
isCameraFocusSupported() & getCameraMaxZoomFactor() on iOS throws exception

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Agora-Flutter-SDK#267]
Agora Plugin version: 3.1.4

Using isCameraFocusSupported() or getCameraMaxZoomFactor() on iOS results in the following error:
PlatformException (PlatformException(4, not supported, null, null))

The methods work fine on Android.

isCameraZoomSupported() works fine on iOS.

**Comment by LichKing-2234** [comment]
this method not support for ios

**Comment by rgb1380** [comment]
Perhaps documentation needs to be updated then.
However, how is it that isCameraZoomSupported() is OK but one cannot get the max zoom factor? What are you supposed to assume in terms of zoom?

**Comment by LichKing-2234** [comment]
discuss on https://github.com/AgoraIO/Agora-Flutter-SDK/issues/261

**Comment by rgb1380** [comment]
Cannot see any more info that can help with this in #261
