### ISSUE TITLE
Calling setCameraZoomFactor() on iOS causes the app to crash

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Agora-Flutter-SDK#268]
Not much more information to add as the app crashes on calling setCameraZoomFactor(). 

Agora Plugin version: 3.1.4

**Comment by LichKing-2234** [comment]
any crash dump?

**Comment by rgb1380** [comment]
Attached.
[Runner-2021-03-06-170417.txt](https://github.com/AgoraIO/Agora-Flutter-SDK/files/6095101/Runner-2021-03-06-170417.txt)

**Comment by LichKing-2234** [comment]
seem like your param is null.

**Comment by rgb1380** [comment]
What do you mean?

**Comment by LichKing-2234** [comment]
pls, double-check the param of `setCameraZoomFactor` method is null or not.

**Comment by rgb1380** [comment]
It is not null. It is a double value  > 1.0
Have you tried this on a physical IOS device on your side. Should be easy to replicate.

**Comment by LichKing-2234** [comment]
could you pls share the code about it?

**Comment by rgb1380** [comment]
Not sure how that could be helpful. It is a Flutter code which runs fine on Android and crashes on iOS. There are no OS dependent code.
Have you tried to test this on iOS on your side? Are you saying you cannot replicate the issue?

**Comment by LichKing-2234** [comment]
@rgb1380 yes, I cannot replicate it, it only crashes when I set the param to null.
```
double factor = null;
engine.setCameraZoomFactor(factor);
```

**Comment by rgb1380** [comment]
I have upgraded to the latest plug-in (3.2.1)

Just to be perfectly sure, I have set the zoom factor to a constant and it crashes as before.

await _rtcEngine.setCameraZoomFactor(1.1);

Here is the details of the physical device. 
Model: iPhone8,2 (Physical), OS: iOS 14.4

**Comment by LichKing-2234** [comment]
I have replicated it on the physical device, it will be fixed next version.

**Comment by LichKing-2234** [comment]
version [3.3.1-rc.1](https://pub.dev/packages/agora_rtc_engine/versions/3.3.1-rc.1) have been published.
