### ISSUE TITLE
agora_rtc_engine ^3.3.0-rc.0 using old version of json_annotation 

### ISSUE THREAD

**Issue by shic** [AgoraIO/Agora-Flutter-SDK#269]
My project use

```
  agora_rtc_engine: ^3.3.0-rc.0
  json_annotation: ^4.0.0 
  json_serializable: ^4.0.2
```

And it cause error
```
Project depends on agora_rtc_engine ^3.3.0-rc.0 which depends on json_annotation ^3.0.0, json_annotation ^3.0.0 is required.
So, because leopard depends on json_annotation ^4.0.0, version solving failed.
```

**Comment by LichKing-2234** [comment]
It has been pushed to the `rc/3.3.+` branch, but it not be published to  `pub.dev`.

**Comment by shic** [comment]
> It has been pushed to the `rc/3.3.+` branch, but it not be published to `pub.dev`.

Thanks for the response, could I ask when the `rc/3.3.+` will be published?

**Comment by LichKing-2234** [comment]
the 4.x version support dart 2.12 and    flutter2
