### ISSUE TITLE
LogLevel not working

### ISSUE THREAD

**Issue by dganzella** [AgoraIO/Agora-Flutter-SDK#270]
**Describe the bug**
Either using 3.3.0+  LogConfig(level: LogLevel.Fatal), or older 3.2.1  setLogFilter(LogFilter.Error) do not filter out the logs as expected.

**To Reproduce**
Run a project trying to change log level to anything besided default INFO

**Expected behavior**
We should be able to filter out the amount of messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/30127664/110529848-7fd76780-80f8-11eb-885d-73e6e64ec68b.png)

**Smartphone (please complete the following information):**
 - Device: Motorola G7 Play
 - OS: 9.0
 - Version Either 3.2.1 or 3.3.1-rc1

**Additional context**

**Comment by LichKing-2234** [comment]
the `LogLevel` just for the .log file.

**Comment by dganzella** [comment]
@LichKing-2234 thanks for the reply!

well...that...is..a...bummer indeed :|

well for anyone who may need to do it in the future I found a simpler solution:

flutter run --flavor=tobelive | Select-String -Pattern  'agora_vrp|libc' -NotMatch

A peson can change agora_vrp to I/agora_vrp to filter only info, or even an entire specific message to filter out specific things that are spamming too much like stuck_watch
