### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jarwin123** [AgoraIO/Agora-Flutter-SDK#274]
`[+113243 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Could not determine the dependencies of task ':app:processReleaseResources'.
[        ] > Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
[        ]    > Could not resolve io.flutter:armeabi_v7a_release:1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.
[        ]      Required by:
[        ]          project :app
[        ]       > Could not resolve io.flutter:armeabi_v7a_release:1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.        
[        ]          > Could not get resource
'https://jcenter.bintray.com/io/flutter/armeabi_v7a_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/armeabi_v7a_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'.
[        ]             > Could not GET
'https://jcenter.bintray.com/io/flutter/armeabi_v7a_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/armeabi_v7a_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'.
[        ]                > Read timed out
[        ]    > Could not resolve io.flutter:arm64_v8a_release:1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.
[        ]      Required by:
[        ]          project :app
[        ]       > Could not resolve io.flutter:arm64_v8a_release:1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.
[        ]          > Could not get resource
'https://jcenter.bintray.com/io/flutter/arm64_v8a_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/arm64_v8a_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'.
[   +1 ms]             > Could not GET
'https://jcenter.bintray.com/io/flutter/arm64_v8a_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/arm64_v8a_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'.
[        ]                > Read timed out
[        ]    > Could not resolve io.flutter:x86_64_release:1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.
[        ]      Required by:
[        ]          project :app
[        ]       > Could not resolve io.flutter:x86_64_release:1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.
[        ]          > Could not get resource
'https://jcenter.bintray.com/io/flutter/x86_64_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/x86_64_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'.
[        ]             > Could not GET
'https://jcenter.bintray.com/io/flutter/x86_64_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/x86_64_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'.
[        ]                > Read timed out
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.  
Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 53s`

![图片](https://user-images.githubusercontent.com/8475971/111179844-68601900-85e7-11eb-8daf-0950e871d636.png)

**Comment by jarwin123** [comment]
![图片](https://user-images.githubusercontent.com/8475971/111180017-95143080-85e7-11eb-9948-ed779537b705.png)

**Comment by plutoless** [comment]
Could not resolve io.flutter:armeabi_v7a_release:1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380. [ ] > Could not get resource 'https://jcenter.bintray.com/io/flutter/armeabi_v7a_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/armeabi_v7a_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'. [ ] > Could not GET 'https://jcenter.bintray.com/io/flutter/armeabi_v7a_release/1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380/armeabi_v7a_release-1.0.0-07c1eed46b9d9b58df78566e9b8b2e42e80d3380.pom'. [ ] > Read timed out

it seems you are having some network issues as the error indicates read time out

**Comment by jarwin123** [comment]
![image](https://user-images.githubusercontent.com/8475971/111259186-6767cf80-8659-11eb-8451-facb428cd21e.png)

**Comment by LichKing-2234** [comment]
@jarwin123 maybe you have cached gradle 5.6.2, but you can't download gradle 6.7.1.

**Comment by jarwin123** [comment]
@LichKing-2234 not only  i have gradle 6.7.1,    but also have gradle 5.6.2 
![图片](https://user-images.githubusercontent.com/8475971/111356740-9fa3f800-86c3-11eb-9b11-4e1bc4089d9f.png)

**Comment by LichKing-2234** [comment]
you can try to delete it and try again.

**Comment by ShreshtaRupa** [comment]
Could not resolve all task dependencies for configuration ':agora_rtc_engine:debugRuntimeClasspath'.
   > Could not resolve com.github.agorabuilder:native-full-sdk:3.5.0.3. 
     Required by:                                                       
         project :agora_rtc_engine                                      
      > Could not resolve com.github.agorabuilder:native-full-sdk:3.5.0.3.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/github/agorabuilder/native-full-sdk/3.5.0.3/native-full-sdk-3.5.0.3.pom'.
            > Could not HEAD 'https://google.bintray.com/exoplayer/com/github/agorabuilder/native-full-sdk/3.5.0.3/native-full-sdk-3.5.0.3.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.
     Required by:                                                       
         project :agora_rtc_engine                                      
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.
         > Could not get resource 'https://google.bintray.com/exoplayer/io/flutter/flutter_embedding_debug/1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce/flutter_embedding_debug-1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.pom'.
            > Could not HEAD 'https://google.bintray.com/exoplayer/io/flutter/flutter_embedding_debug/1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce/flutter_embedding_debug-1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.pom'. Received status code 502 from server: Bad Gateway

**Comment by littleGnAl** [comment]
Pls try `agora_rtc_engine: ^5.0.0`
