### ISSUE TITLE
joinChannelWithUserAccount  does not work in android in some cases

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO/Agora-Flutter-SDK#275]
**To Reproduce**

Join channel X
Leave channel X
onLeave callback, Join Y
It neither joins nor throws an error.

**Expected behavior**
Either Join Y or throw an error

**Smartphone (please complete the following information):**
 - Device: One plus 3
 - OS: Android
 - Version Android 9

**Comment by LichKing-2234** [comment]
maybe you use the same token to join two different channels?

**Comment by LichKing-2234** [comment]
you can listen to the `Error` event to get more information.

**Comment by shashikantdurge** [comment]
No error thrown on the error event

**Comment by RoJoHub** [comment]
Sorry to reply you so late.     @shashikantdurge

Please use this code to show more information.

```dart
_joinChannel() async {
    try {
      if (defaultTargetPlatform == TargetPlatform.android) {
        await Permission.microphone.request();
      }
      await widget._engine
          ?.joinChannelWithUserAccount(config.token, channelId, stringUid);
          print('ok-----join');
    } catch (e) {
      print(e.toString());
    } finally {
      print('finally');
    }
  }
```

**Comment by shashikantdurge** [comment]
@RoJoHub it prints ok...join, but the join channel callback is not called

**Comment by RoJoHub** [comment]
Could you please test this code 

```javascript
this._engine?.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
      console.info('JoinChannelSuccess', channel, uid, elapsed);
      // RtcLocalView.SurfaceView must render after engine init and channel join
      this.setState({ isJoin: true });
    });
    this._engine?.addListener('UserJoined', async (uid, elapsed) => {
      console.info('UserJoined', uid, elapsed);
      this.setState({ remoteUid: uid });
    });
```

**Comment by shashikantdurge** [comment]
Note:
**joinChannel does NOT work ONLY in the following use case**:

Join channel X as Broadcaster
Leave channel X
in the onLeave callback, join channel Y

It does NOT throw errors anywhere.
