### ISSUE TITLE
Unsynchronized audio and video

### ISSUE THREAD

**Issue by rekonvald** [AgoraIO/Agora-Flutter-SDK#278]
Hi!

When I run app for the 1st time and have 1-on-1 call it works fine! But the longer conversation continues the more we can see unsynchronized audio and video effect(

It happens on ios. 

Thanks

**Comment by plutoless** [comment]
could you pls make a recording of the unsync audio/video issue?

**Comment by rekonvald** [comment]
https://s3.eu-west-3.amazonaws.com/uat-call-video/records/55cf4ac9384f96cd2e99159539879c7d_50cffbea-1ff6-4276-a587-08bb2faa29dd.m3u8

**Comment by rekonvald** [comment]
Any updates?

**Comment by LichKing-2234** [comment]
@rekonvald sorry for the later reply, we need the sdk log file.

**Comment by rekonvald** [comment]
[agorasdk.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/6185012/agorasdk.log)
Can we maybe solve it directly( anna.rekonvald@gmail.com)
Conversation was started at about 21:57

**Comment by LichKing-2234** [comment]
@rekonvald if you need quick help, you can find support on our website.

**Comment by rekonvald** [comment]
I just thought the problem is into flutter implementation, could you please give a link for support

**Comment by The-Machine-Tango** [comment]
@rekonvald You could reach to the email Support / CS <support@agora.io> for Agora Support. You could also submit a ticket from your console following the steps below and in this way, you could better track the issue with a ticket number.
 https://docs.agora.io/en/Agora%20Platform/ticket?platform=Flutter
