### ISSUE TITLE
'create' what should i use instead  deprecated 

### ISSUE THREAD

**Issue by Yahya-khodr** [AgoraIO/Agora-Flutter-SDK#280]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LichKing-2234** [comment]
you can keep using it. it may be a mistake of doc.

**Comment by Yahya-khodr** [comment]
So the agora quickstart is the latest repository? 
Because I've just copied all the quickstart in my app , but it says deprecated,  can you please give me some suggestions or sources to get rid of the problem ?
