### ISSUE TITLE
App size going to 100+MB on adding Agora Flutter SDK

### ISSUE THREAD

**Issue by aayushkedawat** [AgoraIO/Agora-Flutter-SDK#282]
I am experiencing this problem that when I add agora_rtc_engine to my pubspec.yaml, the app becomes heavy, and APK size goes up to 120MB

**Comment by LichKing-2234** [comment]
you can refer to https://developer.android.com/ndk/guides/abis#gc

**Comment by RasyidMF** [comment]
Check my comment at #340 for solution
