### ISSUE TITLE
Video/Audio call

### ISSUE THREAD

**Issue by Yahya-khodr** [AgoraIO/Agora-Flutter-SDK#283]
Hello , Please can you guys help me how to reject call with agora in both side from caller/receiver in flutter app, I'm using flutter with agora rtc engine

**Comment by LichKing-2234** [comment]
Sorry, I don't understand, what means rejecting the call with agora?

**Comment by Yahya-khodr** [comment]
Done

**Comment by LichKing-2234** [comment]
could you share your solution? It may help other developers. Thanks.
