### ISSUE TITLE
Cannot change Volume in  CHATROOM_ENTERTAINMENT (Android only)

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO/Agora-Flutter-SDK#285]
**Describe the bug**
As per the documentation [here](https://docs.agora.io/en/Video/audio_profile_android?platform=Android#considerations)
CHATROOM_ENTERTAINMENT => All users use the in-call volume.

But in Android device,
**App in Foreground: Media volume is used. (But it does not take effect) [THIS IS THE ISSUE]**
App in Background: In-Call volume is used. (Yes, it takes effect) [FINE HERE]

**To Reproduce**
1. Channel profile:  Live Broadcasting
2. Audio scenario: CHATROOM_ENTERTAINMENT
3. set client role: Audience
4. Join the channel 
5. After joining, Change client role to Broadcaster
6. Change volume (try in both roles audience & Broadcaster)

**Expected behavior**
App in Foreground: In-Call volume is used. (It should take effect)
App in Background: In-Call volume is used. (It should take effect)

**Screenshots**
![Screenshot_20210327-132637](https://user-images.githubusercontent.com/20161204/112714482-87707c00-8f00-11eb-9946-1a91253b5b3e.jpg  =120x80)
![Screenshot_20210327-132633](https://user-images.githubusercontent.com/20161204/112714398-3a8ca580-8f00-11eb-86d7-2f4a5818a6d8.jpg =120x80)

**Smartphone (please complete the following information):**
 - Device: One Plus 3
 - OS: Android 9
 - Version 9

**Comment by shashikantdurge** [comment]
The same issue happens in the following use-case:
Channel profile: Live Broadcast
Audio scenario: Default
Client role: Broadcaster (Host)

**Comment by RoJoHub** [comment]
> The same issue happens in the following use-case:
> Channel profile: Live Broadcast
> Audio scenario: Default
> Client role: Broadcaster (Host)

Hi ,friend.

-----
based on your description:

*Behavior:*
>>App in Foreground: Media volume is used. (But it does not take effect) [THIS IS THE ISSUE]
>>App in Background: In-Call volume is used. (Yes, it takes effect) [FINE HERE]

*Expected behavior:*
>App in Foreground: In-Call volume is used. (It should take effect)
>App in Background: In-Call volume is used. (It should take effect)

---

Do you mean that the app can't find the media volume button in the foreground?

**Comment by RoJoHub** [comment]
> **Describe the bug**
> As per the documentation [here](https://docs.agora.io/en/Video/audio_profile_android?platform=Android#considerations)
> CHATROOM_ENTERTAINMENT => All users use the in-call volume.
> 
> But in Android device,
> **App in Foreground: Media volume is used. (But it does not take effect) [THIS IS THE ISSUE]**
> App in Background: In-Call volume is used. (Yes, it takes effect) [FINE HERE]
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Channel profile:  Live Broadcasting
> 2. Audio scenario: CHATROOM_ENTERTAINMENT
> 3. set client role: Audience
> 4. Join the channel
> 5. After joining, Change client role to Broadcaster
> 6. Change volume (try in both roles audience & Broadcaster)
> 
> **Expected behavior**
> App in Foreground: In-Call volume is used. (It should take effect)
> App in Background: In-Call volume is used. (It should take effect)
> 
> **Screenshots**
> ![Screenshot_20210327-132637](https://user-images.githubusercontent.com/20161204/112714482-87707c00-8f00-11eb-9946-1a91253b5b3e.jpg =120x80)
> ![Screenshot_20210327-132633](https://user-images.githubusercontent.com/20161204/112714398-3a8ca580-8f00-11eb-86d7-2f4a5818a6d8.jpg =120x80)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: One Plus 3
> * OS: Android 9
> * Version 9

**Comment by shashikantdurge** [comment]
Hi @RoJoHub 
I mean, The app should use In-Call volume whenever the user changes the volume with the button.
But it's not working when the app is in the foreground.

I can send the video if it's still not clear

**Comment by shashikantdurge** [comment]
Issue Detailed in the video
https://drive.google.com/file/d/1MjU69CgefJI0x1BdmX1_gx8ksZszMy54/view?usp=sharing

**Comment by RoJoHub** [comment]
Do you mean that when switching user roles(frome listener to speaker), the volume button should control the call volume?

**Comment by shashikantdurge** [comment]
Yes

**Comment by RoJoHub** [comment]
Please wait. I'm following up on this issue. It may take a while

**Comment by RoJoHub** [comment]
I'm sorry I came too late.
Due to lack of human resources, can you provide an example for my verification?

**Comment by shashikantdurge** [comment]
Update:
 We were using https://pub.dev/packages/audio_service plugin to show Notification.

This plugin was using Media volume internally, Removing the plugin fixed this issue.
