### ISSUE TITLE
SDK的example在iphone 8p上跑起来，占用存储空间有334MB

### ISSUE THREAD

**Issue by hjue** [AgoraIO/Agora-Flutter-SDK#286]
SDK的example在iphone 8p上跑起来，占用存储空间有334MB。

自己的flutter App加了agora_rtc_engine有328M，加之前只有38M。

这有点大啊，有办法瘦身吗？

**Comment by LichKing-2234** [comment]
用的是哪个版本呢

**Comment by hjue** [comment]
agora_rtc_engine: ^3.3.2
 permission_handler: ^6.1.1

**Comment by LichKing-2234** [comment]
是指ipa大小，还是安装后的大小

**Comment by hjue** [comment]
安装后的大小，334M是在手机上看到了

**Comment by LichKing-2234** [comment]
理论上只用关心ipa大小就好了
