### ISSUE TITLE
startAudioRecording not working on IOS

### ISSUE THREAD

**Issue by elijahleinkram** [AgoraIO/Agora-Flutter-SDK#292]

**Comment by elijahleinkram** [comment]
The recording is produced in the path provided, however there is no actual data within the file, the audio will simply not play.

**Comment by elijahleinkram** [comment]
If anyone has any suggestions or the like, I would be super happy! Thanks Elijah.

**Comment by plutoless** [comment]
is the filesize zero? maybe it's just a matter of choosing another player?

**Comment by elijahleinkram** [comment]
Yes, the filesize is zero

**Comment by plutoless** [comment]
have you joined the channel successfully? it only works after you join channel

**Comment by elijahleinkram** [comment]
Yes, I have joined the channel successfully, this works on my Android device.

**Comment by elijahleinkram** [comment]
Is there an issue with certain IOS devices or IOS emulators?

**Comment by LichKing-2234** [comment]
what path did you set on iOS?

**Comment by elijahleinkram** [comment]
```
Future<String> getTmpFilePath(String filename) async  {

    Directory tempDir =
        await getApplicationDocumentsDirectory().catchError((error) {
      print(error);
    });
    if (tempDir == null) {
      return null;
    }
    String tempPath = tempDir.path;
    File tempFile = File('$tempPath/$filename');
    return tempFile.path;
}

String filePath = await getTmpFilePath(
          'pod${DateTime.now().millisecondsSinceEpoch}.wav');
```

**Comment by elijahleinkram** [comment]
My code for getting the path ^^^

**Comment by LichKing-2234** [comment]
could you pls print the path, and provide our SDK log?

**Comment by elijahleinkram** [comment]
Hey thanks for getting back to me so quickly...

Here is my path:

/Users/elijah/Library/Developer/CoreSimulator/Devices/D2CF5694-1389-48B0-B6BB-2D517B5FB770/data/Containers/Data/Application/B65EAD41-47A3-447C-86B8-EA59B3D4B1B7/Documents/pod1617896293281.wav

**Comment by elijahleinkram** [comment]
iPhone 11 Pro Max ios version 14.0 (simulator)

**Comment by elijahleinkram** [comment]
I am running the app on a mac virtual machine, it's very bare bones, is there any way I can get you the SDK log from terminal?

**Comment by LichKing-2234** [comment]
pls follow the setLogFile method to get the log file.

**Comment by elijahleinkram** [comment]
Hey sorry folks I just tested it out on a real device, turns out it was my emulator after all!

Thanks for everything.
