### ISSUE TITLE
IOS defaults to ear speaker

### ISSUE THREAD

**Issue by elijahleinkram** [AgoraIO/Agora-Flutter-SDK#293]
final List<Future<dynamic>> promises = [];
    promises.add(
        _engine.enableAudioVolumeIndication(200, 3, true).catchError((error) {
      print(error);
    }));
    promises.add(_engine.enableAudio().catchError((error) {
      print(error);
    }));
    promises.add(_engine.enableDeepLearningDenoise(true).catchError((error) {
      print(error);
    }));
    promises.add(_engine
        .setChannelProfile(ChannelProfile.Communication)
        .catchError((error) {
      print(error);
    }));
    promises
        .add(_engine.setClientRole(ClientRole.Broadcaster).catchError((error) {
      print(error);
    }));
    promises.add(_engine
        .setAudioProfile(AudioProfile.SpeechStandard, AudioScenario.MEETING)
        .catchError((error) {
      print(error);
    }));
    await Future.wait(promises).catchError((error) {
      print(error);
    });
    _engine
        .joinChannel(_token, 'shmooze', null, Human.uid.hashCode)
        .catchError((error) {
      print(error);
    });

**Comment by elijahleinkram** [comment]
I thought that the enableInEarMonitoring defaults to false.

If so, then why does the audio by default come out of the ear speaker?

**Comment by LichKing-2234** [comment]
you should set channel profile to broadcasting

**Comment by elijahleinkram** [comment]
Okay thanks, this works.
