### ISSUE TITLE
Support for multi-channel recording on the client?

### ISSUE THREAD

**Issue by elijahleinkram** [AgoraIO/Agora-Flutter-SDK#294]
Hey, I was just wondering if there was a way to only record the local user's voice, so that we can get a local multi-channel recording?

**Comment by elijahleinkram** [comment]
The startAudioRecording method records all the users in the channel...

**Comment by plutoless** [comment]
you can use raw data api. or cloud recording.

**Comment by plutoless** [comment]
OH but in flutter it's not that easy to access raw data api.. would cloud recording help?

**Comment by elijahleinkram** [comment]
Thanks for the quick reply. Cloud recording would help, but I would prefer to do it on the client. Is there any way I could access the raw data api on Flutter?

**Comment by elijahleinkram** [comment]
Cloud recording would help, but I haven't seen any tutorials for getting it to work with Flutter. If there is one, then I would love to see it :)

**Comment by plutoless** [comment]
https://docs.agora.io/en/cloud-recording/landing-page?platform=RESTful check here for docs. it's triggered from your server usually.

**Comment by elijahleinkram** [comment]
I am using cloud functions. (Firebase/Firestore)

**Comment by elijahleinkram** [comment]
Can I have two people join two different channels. On the one channel person B is only able to listen with person A speaking, and on the second channel person A is only able to listen with person B speaking? 

The channels operate at the same time. And any one of these people can record the channels and they will only record the people speaking on the channel (which in this case is limited to one person).

Would this work on a p2p voice call?

**Comment by plutoless** [comment]
why do you want B to hear A while they are in different channels? Why not just put them in one channel?

**Comment by elijahleinkram** [comment]
Because how then could you record each user's own voice on the client? 

This solution assumes two things. 

a) You can be connected to two different channels at once
b) If you record audio in one channel, it will not pick up audio coming from the other channel (even if that audio is coming out of your phone's speaker)

**Comment by elijahleinkram** [comment]
Hey, it's fine, I will just use the cloud recorder for now. But there should be a way of each person recording their own audio streams.
