### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'forEach' was called on null. for Function rtcEngine.getUserInfoByUid

### ISSUE THREAD

**Issue by Gunnar-Stunnar** [AgoraIO/Agora-Flutter-SDK#297]
**Describe the bug**
when using the getUserInfoByUid on the event of the user joining a room. You get "The method 'forEach' was called on null." from package:agora_rtc_engine/src/rtc_engine.dart:266:32
`
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'forEach' was called on null.
Tried calling: forEach(Closure: (dynamic, dynamic) => void)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:87:11)
#2      RtcEngine.getUserInfoByUid.<anonymous closure> (package:agora_rtc_engine/src/rtc_engine.dart:266:32)
#3      _rootRunUnary (dart:async/zone.dart:1362:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:254:13)
#10     MethodChannel._invokeMethod (package:flutter/src/services/platfor<…>
`

**To Reproduce**
`
userJoined(uid, elapsed) async {
    print("user: $uid joined!");
    print("Getting User Info");

    UserInfo value = await RtcEngine.getUserInfoByUid(uid);
}
`
use this code, now try to join a channel with people already on it and it will throw that error.

**Expected behavior**
For it to return the correct UserInfo object about the users already in the room.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [3.3.3]
 - flutter

**Comment by Gunnar-Stunnar** [comment]
Fixed by waiting 200 ms with a Future
`await Future.delayed(Duration(milliseconds: 200));`

**Comment by LichKing-2234** [comment]
pls refer to https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/217
