### ISSUE TITLE
User Joined and user offline listener not working

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#302]
I put print when join and leave channel but those are not printing. First I try to call a method but it was not calling when I print I came to know these methods are not listening
Here is my code please check and let me know
```
  _addListeners() {
    widget._engine?.setEventHandler(RtcEngineEventHandler(
      joinChannelSuccess: (channel, uid, elapsed) {
        print('joinChannelSuccess ${channel} ${uid} ${elapsed}');
        log('joinChannelSuccess ${channel} ${uid} ${elapsed}');
        setState(() {
          isJoined = true;
        });
      },
      leaveChannel: (stats) async {
        log('leaveChannel ${stats.toJson()}');
        setState(() {
          isJoined = false;
        });
        await widget._engine
            ?.joinChannel(widget.token, widget.channel, null, widget.id)
            ?.catchError((err) {
          print('error ${err.toString()}');
        });
      },
      userJoined: (uid, elapsed) {
        updateTimer();
        print('user join ${uid} ${elapsed}');
      },
      userOffline: (uid, elapsed) {
        _leaveChannel();
      },
    ));
  }
```

**Comment by plutoless** [comment]
maybe you just fail to join the channel? could you pls try listening to error events?

**Comment by ziasultan2** [comment]
I joined from emulator and it print join event and another I join from here https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/ it also shows joined channel

**Comment by LichKing-2234** [comment]
Maybe you use string uid to join the channel on the Web platform?

**Comment by BhavyKoshti9spl** [comment]
I also gave this issue,

if person is joining the channel then user left and then user jointed is called 

any updates ? 

also `_channel.getMembers()` is also not working properly.

**Comment by ziasultan2** [comment]
use id as 0 by this it'll allow all user to join and you listener will work

**Comment by piyushbhatia891** [comment]
In my case, every user is joining with distinct Uid and same token. then also i m not able to see userjoined callback working.
Any clues, how can i correct the issue.

PS- both the users are able to join the call but userjoined callbacks and other callbacks are not getting exexuted

**Comment by vmwsree** [comment]
I'm having the same issue. any update?
