### ISSUE TITLE
When Flutter 2 will be support?

### ISSUE THREAD

**Issue by Azare77** [AgoraIO/Agora-Flutter-SDK#303]
When Flutter 2 will be supported?

**Comment by abhishekak048** [comment]
Bro flutter 2 is available now
https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65

**Comment by Azare77** [comment]
@abhishekak048  i know bro but when you check agora documents you will see this
Flutter 1.0.0 or later (Flutter 2.x is not supported)
https://docs.agora.io/en/Voice/start_call_audio_flutter?platform=Flutter

**Comment by LichKing-2234** [comment]
if you just need null safty, you can use the 4.x prerelease version.
if you need web or desktop, we are developing.

**Comment by Azare77** [comment]
thanks
