### ISSUE TITLE
Callback for when audio recording starts

### ISSUE THREAD

**Issue by elijahleinkram** [AgoraIO/Agora-Flutter-SDK#305]
Currently, when we start recording audio there is no callback function which allows us to retrieve the time, or do some other operations.

Having this callback is an essential component to the audio recording operation.

Thanks, Elijah

**Comment by plutoless** [comment]
not sure i understand. the recording should start right away once you call the api

**Comment by fareesh** [comment]
If a user joins muted it doesn't start recording till the first audio frame. There's an event for that, you can start recording on the first occurrence

**Comment by elijahleinkram** [comment]
Thanks guys :)
