### ISSUE TITLE
Video call getting disconnected when we click Back button :

### ISSUE THREAD

**Issue by gopi1315** [AgoraIO/Agora-Flutter-SDK#308]
In our Application we implemented Agora for one to one Video Call. For some reasons when the call is going on the user needs to go back for checking some information, when he does the call is getting disconnected. Is there any possible way for the Video Call is not getting disconnected when the user click on the Back button.

The Call should not be disconnected when he goes to another screen in the Application. The call should be running until anyone disconnects the call.Any help is much appreciated.Thanks in Advance.

**Comment by LichKing-2234** [comment]
the best way is using PIP.
