### ISSUE TITLE
Add Screen Sharing Feature

### ISSUE THREAD

**Issue by rupamking1** [AgoraIO/Agora-Flutter-SDK#310]
Pls Add Screen Sharing Feature on Android, IOS, Web, Desktop

**Comment by LichKing-2234** [comment]
The screen sharing needs multiple processes, so it will take a lot of time to implement it. We will develop for flutter2 first.

**Comment by rupamking1** [comment]
Pls try to make it for web and desktop also.

**Comment by JayPerfetto** [comment]
My company implemented screen sharing ourselves using Agora RTM and a custom reactive event handling loop

**Comment by EmmanuelJoshua** [comment]
@JayPerfetto No chance of sharing? 👀

**Comment by Muhammad-Ullah** [comment]
@rupamking1 did you found any solution?

**Comment by mrtordoide** [comment]
@Muhammad-Ullah You can find an implementation example here: [Screen share example](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/dev/flutter2/example/lib/examples/advanced/screen_sharing.dart)

**Comment by Muhammad-Ullah** [comment]
@mrtordoide thanks

**Comment by Muhammad-Ullah** [comment]
@mrtordoide I am new to agora. I am getting error in the above mention code.
It says in this line that:
final helper = _engine.getScreenShareHelper();

getScreenShareHelper() is not define.

**Comment by mrtordoide** [comment]
@Muhammad-Ullah You need to import alpha version of agora rtc package or use `dev/flutter2` branch  of this repo in your project.

**Comment by Muhammad-Ullah** [comment]
@dart.global.IrisRtcEngine is not a constructor. How to solve this one?

**Comment by mrtordoide** [comment]
Have you imported AgoraRtcWrapper.js into index.html? 
https://github.com/AgoraIO/Agora-Flutter-SDK/tree/dev%2Fflutter2/example%2Fweb

**Comment by Muhammad-Ullah** [comment]
@mrtordoide can you drop whatsapp link of fiverr link?

**Comment by fvisticot** [comment]
> @mrtordoide can you drop whatsapp link of fiverr link?

Same issue :( Did you fix your pb ?

**Comment by Muhammad-Ullah** [comment]
@fvisticot Sorry brother not yet

**Comment by tp** [comment]
> The screen sharing needs multiple processes, so it will take a lot of time to implement it. We will develop for flutter2 first.

We have been using the screen sharing functionality from the [`dev/flutter2`](https://github.com/AgoraIO/Agora-Flutter-SDK/tree/dev/flutter2) branch successfully.

I was just wondering what's the status there with regards to merging it to the mainline (as it's behind a few months of work, and I wondered if we're missing out on bug fixes for the core features while staying on that branch)?

**Comment by tp** [comment]
> The screen sharing needs multiple processes, so it will take a lot of time to implement it. We will develop for flutter2 first.

We have been using the screen sharing functionality from the [`dev/flutter2`](https://github.com/AgoraIO/Agora-Flutter-SDK/tree/dev/flutter2) branch successfully.

@LichKing-2234 I was just wondering what's the status there with regards to merging it to the mainline (as it's behind a few months of work, and I wondered if we're missing out on bug fixes for the core features while staying on that branch)?
