### ISSUE TITLE
M1芯片的电脑编译不了

### ISSUE THREAD

**Issue by jonjon-coder** [AgoraIO/Agora-Flutter-SDK#320]
error: 'AgoraRtcKit/AgoraRtcEngineKit.h' file not found
#import <AgoraRtcKit/AgoraRtcEngineKit.h>
        ^
<unknown>:0: error: could not build Objective-C module 'agora_rtc_engine'

**Comment by LichKing-2234** [comment]
非M1正常？有升级xcode和cocoapods么

**Comment by jonjon-coder** [comment]
> 非M1正常？有升级xcode和cocoapods么

非M1是正常的，xcode兼容模式也可以编译。但是这样没办法开发

**Comment by LichKing-2234** [comment]
尝试参考下https://github.com/firebase/firebase-ios-sdk/issues/7125

**Comment by jonjon-coder** [comment]
> 尝试参考下[firebase/firebase-ios-sdk#7125](https://github.com/firebase/firebase-ios-sdk/issues/7125)

试了，还是不行

**Comment by jonjon-coder** [comment]
rm ios/Podfile
rm ios/Podfile.lock
rm -rf ios/Pods
rm -rf ios/Runner.xcworkspace
flutter clean
flutter build ios

可以用了，非M1芯片的项目拷贝直接用引起的。
