### ISSUE TITLE
May 19th update breaks the build

### ISSUE THREAD

**Issue by Defuera** [AgoraIO/Agora-Flutter-SDK#321]
**Describe the bug**
Today my build started to fail due to an error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.agorabuilder:native-full-sdk:3.4.2.
     Required by:
         project :app > project :agora_rtc_engine
```

**To Reproduce**
1. Add `agora_rtc_engine: ^4.0.0` dependency to your pubspec.yaml
2. Run `flutter run` in your terminal

**Expected behavior**
App runs

**Smartphone (please complete the following information):**
 - Android Pixel 3 real device

**Comment by LichKing-2234** [comment]
try to add `maven { url 'https://www.jitpack.io' }` , like https://github.com/AgoraIO/Agora-Flutter-SDK/blob/rc%2F4.0.%2B/example/android/build.gradle#L18

**Comment by Defuera** [comment]
thx, it does indeed fixes the issue :)

**Comment by RaghuMudem** [comment]
Having the same issue. Tried the given suggestion but not worked for me.

Already tried the below 2 versions separately.
agora_rtc_engine: ^4.0.1
agora_rtc_engine: ^4.0.0-rc.3

And also done the below exercises:
1. flutter pub cache repair 
2. flutter clean
3. flutter pub get
4. flutter pub upgrade
5. flutter run (Separate command)

But no luck. 

Exactly same error logs as mentioned in the issue. 
Did I still missing anything?? 

Please advice me.

**Comment by ShreshtaRupa** [comment]
> try to add `maven { url 'https://www.jitpack.io' }` , like https://github.com/AgoraIO/Agora-Flutter-SDK/blob/rc%2F4.0.%2B/example/android/build.gradle#L18

This link   https://github.com/AgoraIO/Agora-Flutter-SDK/blob/rc%2F4.0.%2B/example/android/build.gradle#L18
 is not working for me it shows a 404 error

**Comment by LichKing-2234** [comment]
If not working, try to use `maven { url 'https://jitpack.io' }`

**Comment by ShreshtaRupa** [comment]
> If not working, try to use `maven { url 'https://jitpack.io' }`

https://github.com/AgoraIO/Agora-Flutter-SDK/issues/520#issue-1075537463
