### ISSUE TITLE
muteLocalVideoStream after calling this method video is not working

### ISSUE THREAD

**Issue by Faisalkc4u** [AgoraIO/Agora-Flutter-SDK#324]
**Describe the bug**
await _engine.muteLocalVideoStream(true);

await _engine.muteLocalVideoStream(false);

After re-enabling the video, the new frames not getting for other people in the meeting 

**To Reproduce**
1. Initialize the  agora engine and it' configuration
2. establish a group video call
3. pause the video by calling await _engine.muteLocalVideoStream(true);
4. resume the video by calling await _engine.muteLocalVideoStream(false);
5. the video is not resuming for other people in the group video call

 - OS:iOS, Android
 - Version: agora_rtc_engine: ^4.0.1

**Smartphone (please complete the following information):**
 - Device: Iphone 7, Iphone 12Pro,Iphone x, android huawei p10 lite
 - OS: iOS 14.4.2 , android 6.0

**Comment by LichKing-2234** [comment]
have you try it with our example?
