### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac' in Flutter

### ISSUE THREAD

**Issue by RaghuMudem** [AgoraIO/Agora-Flutter-SDK#325]
**Describe the bug**
This is the continues of the bug mentioned in the below link.
As the issue is closed, created a new bug for the follow up.

https://github.com/AgoraIO/Agora-Flutter-SDK/issues/321

**To Reproduce**
Add agora_rtc_engine: ^4.0.1/ (or agora_rtc_engine: ^4.0.0-rc.3 ) dependency to your pubspec.yaml
Run flutter run in your terminal

**Expected behavior**
App runs

**Additional context**
This is the follow up for the below mentioned issue. 

https://github.com/AgoraIO/Agora-Flutter-SDK/issues/321

**Comment by LichKing-2234** [comment]
as jcenter is end of life, we migrate to jitpack.

**Comment by LichKing-2234** [comment]
my mistake, thanks!

**Comment by LichKing-2234** [comment]
you can refer to https://github.com/jitpack/jitpack.io/issues/4002

I think it may be an issue from jitpack.

**Comment by Basher7** [comment]
> @LichKing-2234, Thanks for the reply.
> 
> Solved after using the below repo link. Note the link **without** 'www'.
> 
> `maven { url 'https://jitpack.io' }`

where you use this ```maven { url 'https://jitpack.io' }``` link?

**Comment by RaghuMudem** [comment]
> > @LichKing-2234, Thanks for the reply.
> > Solved after using the below repo link. Note the link **without** 'www'.
> > `maven { url 'https://jitpack.io' }`
> 
> where you use this `maven { url 'https://jitpack.io' }` link?

Used in `android/build.gradle` file. You can find the clue and example here #321. Check the answer given by @LichKing-2234.
