### ISSUE TITLE
Could not find com.github.agorabuilder:native-full-sdk:3.4.2

### ISSUE THREAD

**Issue by nimr77** [AgoraIO/Agora-Flutter-SDK#326]
In Flutter 2.2, 
I merged  my app to null safety after waiting for it in this plugin, 
and the build crashed on this Error:
```
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.agorabuilder:native-full-sdk:3.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
       - https://jcenter.bintray.com/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
     Required by:
         project :app > project :agora_rtc_engine

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by akashgk** [comment]
Im getting the same error

**Comment by akashgk** [comment]
`
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.agorabuilder:native-full-sdk:3.4.2.
     Required by:
         project :app > project :agora_rtc_engine

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by nimr77** [comment]
I need the null safety for it.
I think the error because of links for the dependency 
```
Could not find com.github.agorabuilder:native-full-sdk:3.4.2.
``

**Comment by akashgk** [comment]
You can use `--no-sound-null-safety` in case you are in development phase so this won't hinder you,

**Comment by akashgk** [comment]
https://github.com/AgoraIO/Agora-Flutter-SDK/issues/321#issuecomment-843913064
this should fix this issue

**Comment by LichKing-2234** [comment]
pls refer to #321
