### ISSUE TITLE
Could not find com.github.agorabuilder:native-full-sdk:3.4.2.

### ISSUE THREAD

**Issue by VadimBliz** [AgoraIO/Agora-Flutter-SDK#329]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.agorabuilder:native-full-sdk:3.4.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
       - https://jcenter.bintray.com/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
       - https://google.bintray.com/exoplayer/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
     Required by:
         project :app > project :agora_rtc_engine
`

sdk: ">=2.12.0 <3.0.0"
agora_rtc_engine: ^4.0.1

flutter doctor -v 
`[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale ru-UA)
    • Flutter version 2.2.0 at /Users/elereman/flutter
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/elereman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

• No issues found!
`

Can you please investigate tis issue?

**Comment by MySwastik** [comment]
Same Issue : Could not find com.github.agorabuilder:native-full-sdk:3.4.2.

**Comment by louis030195** [comment]
tried https://github.com/AgoraIO/Agora-Flutter-SDK/issues/325#issuecomment-844802327 ?

**Comment by LichKing-2234** [comment]
pls migrate to jitpack
