### ISSUE TITLE
userJoined event with String uid (for joinChannelWithUserAccount)

### ISSUE THREAD

**Issue by louis030195** [AgoraIO/Agora-Flutter-SDK#334]
**Is your feature request related to a problem? Please describe.**

`joinChannelWithUserAccount` lets using a `String` as uid, but most events still give `int` as input.

**Describe the solution you'd like**

Maybe another event that is triggered when a user joined with a `String` uid, or merging with `userJoined`

**Describe alternatives you've considered**

- A hack to map `String` uid to `int` uid just for Agora things.
- Using another RTC system

**Comment by LichKing-2234** [comment]
string uid just a wrapper, you can use getUserInfo to get int uid.

**Comment by louis030195** [comment]
@LichKing-2234 thanks, that should be enough
