### ISSUE TITLE
Agora rtc engine issue in build ios 

### ISSUE THREAD

**Issue by kamoashiwal** [AgoraIO/Agora-Flutter-SDK#335]
Failed to build iOS app
Error output from Xcode build:
↳
    objc[12025]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f5b79160) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x126aa42b8). One of the two will be used. Which one is undefined.
    objc[12025]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f5b791b0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x126aa4308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/kamalashiwal/flutter/doc_domi/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'agora_rtc_engine' not found
    @import agora_rtc_engine;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

**Comment by LichKing-2234** [comment]
maybe you not open the .workspace?

**Comment by kamoashiwal** [comment]
No open many time but same.This is flutter project please help me to solve out .

**Comment by kamoashiwal** [comment]
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-arm, locale en-IN)
    • Flutter version 2.2.0 at /Users/kamalashiwal/Development/Flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kamalashiwal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • SM J700F (mobile)          • 330045dbc7c1c291                     • android-arm    • Android 10 (API 25)
    • iPhone 12 Pro Max (mobile) • F3A66AFC-3C81-47A9-9234-570F614AF2B6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.77

• No issues found!

**Comment by FeifanChang** [comment]
Same issue!

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by YashVG** [comment]
i'm having this exact same issue, it's so annoying i've tried virtually everything possible. Please someone help us

**Comment by yelkamel** [comment]
I have the same issue and in the exemple everything work but I cant build release with the SDK Agora Engine.

It's work only on debug.

**Comment by zionnite** [comment]
am having this issue too, cant do anything all effort proves useless,

**Comment by YashVG** [comment]
Hi, I've found a temporary solution,
so basically you have to go onto ur terminal and switch flutter's channel to master, then update flutter
from there you have to run flutter clean in your project directory

**Comment by zionnite** [comment]
thaks @YashVG
