### ISSUE TITLE
Multi platform support 

### ISSUE THREAD

**Issue by swarupbhanjachowdhury** [AgoraIO/Agora-Flutter-SDK#336]
Please Extend support for web & desktop as well

support Web, linux, windows and mac os as well, it will help us to develop cross platform app with flutter

**Comment by LichKing-2234** [comment]
you can follow the dev/flutter2 branch.

**Comment by swarupbhanjachowdhury** [comment]
> you can follow the dev/flutter2 branch.

Till when we can get stable official support?

**Comment by LichKing-2234** [comment]
We have published the alpha version to support web, macOS, and windows.
https://pub.dev/packages/agora_rtc_engine/versions/4.1.0-alpha.0

**Comment by swarupbhanjachowdhury** [comment]
Thank you so much

**Comment by sujanmt** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
#0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)

#1 RtcEngine.createWithContext (package:agora_rtc_engine/src/rtc_engine.dart:165:5)

#2 _State._initEngine (package:agora_rtc_engine_example/examples/basic/join_channel_video/join_channel_video.dart:39:15)
