### ISSUE TITLE
Could not find com.github.agorabuilder:native-full-sdk:3.4.2.

### ISSUE THREAD

**Issue by k1ycee** [AgoraIO/Agora-Flutter-SDK#337]
**Describe the bug**
 I tried running my app on Flutter 2.2 and for some reason it keeps saying it can't get a necessary resource to build the app on my device

**To Reproduce**
1. Upgrade to Flutter 2.2 
2. Get package 
3. Try running the app
4. FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:checkDebugAarMetadata'.                 
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.agorabuilder:native-full-sdk:3.4.2.      
     Searched in the following locations:                               
       - https://dl.google.com/dl/android/maven2/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
       - https://jcenter.bintray.com/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
     Required by:                                                       
         project :app > project :agora_rtc_engine

**Comment by LichKing-2234** [comment]
pls refer to readme
