### ISSUE TITLE
Could not find com.github.agorabuilder:native-full-sdk:3.4.2.

### ISSUE THREAD

**Issue by wondercrazy15** [AgoraIO/Agora-Flutter-SDK#339]
Describe the bug
I tried running my app on Flutter 2.2 and for some reason it keeps saying it can't get a necessary resource to build the app on my device

To Reproduce

Upgrade to Flutter 2.2
Get package
Try running the app

FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Could not find com.github.agorabuilder:native-full-sdk:3.4.2.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
- https://jcenter.bintray.com/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
- https://storage.googleapis.com/download.flutter.io/com/github/agorabuilder/native-full-sdk/3.4.2/native-full-sdk-3.4.2.pom
Required by:
project :app > project :agora_rtc_engine

**Comment by LichKing-2234** [comment]
pls refer to readme.
