### ISSUE TITLE
issue with flutter web

### ISSUE THREAD

**Issue by georgesamirmansour** [AgoraIO/Agora-Flutter-SDK#342]
Isusue with flutter web, using agora sdk 4.0.1
when getting started with agora sdk and trying to join channel from web, it says target platform.windwos not support yet by the plugin, 
flutter version 2.2.0, dark sdk 1.13.0
using chrome browser on local host,
notes , it work fine with android device and ios,

**Comment by LichKing-2234** [comment]
which api?
