### ISSUE TITLE
I'm newbie integrate agora io service 

### ISSUE THREAD

**Issue by ysy523** [AgoraIO/Agora-Flutter-SDK#343]
I have question regarding the local and remote user.  Local user (Host) and remote user both of them have their own uid or only remote have uid ,local user no uid?

**Comment by LichKing-2234** [comment]
local uid is 0

**Comment by ysy523** [comment]
> local uid is 0

Thanks for answer this question.  I need to use local uid and remote uid for recording the video

**Comment by LichKing-2234** [comment]
if you need to recording the video, you should use the uid from JoinChannelSuccess

**Comment by ysy523** [comment]
> if you need to recording the video, you should use the uid from JoinChannelSuccess event.

Could i know how to call this JoinChannelSuccess event?

**Comment by LichKing-2234** [comment]
after you call joinChannel success

**Comment by ysy523** [comment]
ok . Thanks
