### ISSUE TITLE
Could not find com.github.agorabuilder:native-full-sdk:3.4.2.

### ISSUE THREAD

**Issue by contactlutforrahman** [AgoraIO/Agora-Flutter-SDK#344]
I'm using agora_rtc_engine: ^4.0.1 with Flutter 2.2.1 and getting the below error.

Could not find com.github.agorabuilder:native-full-sdk:3.4.2.
     Required by:
         project :app > project :agora_rtc_engine

**Comment by LichKing-2234** [comment]
pls refer to readme

**Comment by ArcherEmiya05** [comment]
> pls refer to readme

Please avoid this kind of answer, I check the README and it doesn't help at all about this issue. README content is also ever-changing.
