### ISSUE TITLE
Geofencing support

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO/Agora-Flutter-SDK#350]
**Describe the bug**
As per the sample code here https://docs.agora.io/en/Interactive%20Broadcast/region_oc_rtc?platform=iOS#sample-code
// Swift
// Exclude Mainland China from the regions for connection.
let agoraRtcEngineConfig = AgoraRtcEngineConfig();
agoraRtcEngineConfig.appId = type.appId(isClassical: settings.shouldUseClassicalAppIds)
agoraRtcEngineConfig.areaCode = AgoraAreaCode.GLOB.rawValue ^ AgoraAreaCode.CN.rawValue //THIS
agoraKit = AgoraRtcEngineKit.sharedEngine(with: agoraRtcEngineConfig, delegate: self)

Flutter provides Area code enum values, upon which we cannot perform following operation
`AgoraAreaCode.GLOB.rawValue ^ AgoraAreaCode.CN.rawValue`

**Comment by LichKing-2234** [comment]
pls use `RtcEngine.createWithConfig`

**Comment by LichKing-2234** [comment]
but it only supports one area now.

**Comment by shashikantdurge** [comment]
We are having a use case for our application: 
Exclude Mainland China from the regions for connection.

Can we pass an array of Area codes?

**Comment by plutoless** [comment]
i think you can use bitwise operator to combine areas.

**Comment by shashikantdurge** [comment]
@plutoless can you send sample code

**Comment by LichKing-2234** [comment]
@shashikantdurge It does not support now, pls wait for the next version or fork our SDK to implement it.

**Comment by jajuat** [comment]
Hello,
Any update on this request?

**Comment by LichKing-2234** [comment]
Supported.
