### ISSUE TITLE
Version 4.0.2, the project cannot be started normally

### ISSUE THREAD

**Issue by freeala** [AgoraIO/Agora-Flutter-SDK#352]
My environment is：
![image](https://user-images.githubusercontent.com/39516160/121930462-fd081d80-cd74-11eb-811f-141bae7929dd.png)
I introduced the agora4.0.2 version, and the project startup will stop at the Running Gradle task'assembleDebug'...
But when I remove agora4.0.2, the project can start normally
I have tried to introduce 3.3.3 and 3.3.1, it is the same problem

**Comment by LichKing-2234** [comment]
any more build log?
