### ISSUE TITLE
setCloudProxy and rtc.enable_proxy make the connection Unknown/Down

### ISSUE THREAD

**Issue by nizwar** [AgoraIO/Agora-Flutter-SDK#354]
I got some issues with server connection, its like while i'm using "Data/Sim Card" connection, users sound's like robot, some how it sounds like you got poor connection even you have good connection... But while i switch to Wifi connection everything work perfectly...

So i look up on CloudProxy and try to implement it
https://docs.agora.io/en/Voice/API%20Reference/flutter/rtc_engine/RtcEngine/setCloudProxy.html

This what i did (with your example project)
`await _engine.setParameters("{\"rtc.enable_proxy\":true}");`
`await _engine.setCloudProxy(CloudProxyType.UDP);`

Print log is
`flutter: ConnectionStateType.Connecting - ConnectionChangedReason.Connecting`
`flutter: Your Quality is NetworkQuality.Unknown`

This one is working fine on Agora_rtc_engine : 3.2.1
`_engine.setParameters("{\"rtc.enable_proxy\":true}");`

**Comment by LichKing-2234** [comment]
Sorry for the late reply, is this issue still exist?
