### ISSUE TITLE
RtcLocalView freezes when using another AndroidViewSurface plugin on the same page

### ISSUE THREAD

**Issue by xinoxapps** [AgoraIO/Agora-Flutter-SDK#355]
**Describe the bug**
RtcLocalView freezes and RtcRemoteView runs out of memory when using another AndroidViewSurface plugin on the same page.

**To Reproduce**
Run simplified example at https://github.com/xinoxapps/flutter_rtc_app

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 10, kernel 4.4

**Additional context**
Also occurs on other android devices.

**Comment by LichKing-2234** [comment]
Seem like so strange, I will take a look next week.

**Comment by xinoxapps** [comment]
Thank you! 

It is a showstopper for a large company who likes to integrate Agora in their mobile platform

**Comment by LichKing-2234** [comment]
![image](https://user-images.githubusercontent.com/9312526/122723055-12190b00-d2a5-11eb-9d94-8d1cedc002d8.png)
seem like a bug from flutter engine? the GL cause memory leak.

**Comment by xinoxapps** [comment]
It doesn't occur with other plugins such as video_player. 

I suspect something goes wild in the RtcLocalView. It doesn't matter if you use RtcLocalView.TextureView or RtcLocalView.SurfaceView.

**Comment by xinoxapps** [comment]
Any news on this issue, eta?

Has it researched thoroughly and reported to the flutter team?

**Comment by LichKing-2234** [comment]
Sorry, It is difficult to find the cause of this issue. We need more time.

**Comment by LichKing-2234** [comment]
Could pls show your `flutter doctor -v`?

**Comment by xinoxapps** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale nl-NL)
    • Flutter version 2.2.2 at /Users/wendel/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/wendel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.43

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • SM A405FN (mobile) • R58N11GPXQF               • android-arm64  • Android 10 (API 29)
    • iPhone (mobile)    • 00008101-001135A214F0001E • ios            • iOS 14.6
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

**Comment by LichKing-2234** [comment]
I have made sure the memory leaks are caused by flutter.

<img width="1387" alt="企业微信20210701-222231@2x" src="https://user-images.githubusercontent.com/9312526/124141143-be37ce80-dabb-11eb-9b61-ffa941910c01.png">
<img width="1145" alt="企业微信20210701-222330@2x" src="https://user-images.githubusercontent.com/9312526/124141162-c1cb5580-dabb-11eb-9294-37955bcd83e5.png">

**Comment by LichKing-2234** [comment]
but I have no idea why there are too many `FlutterImageViews`.

**Comment by LichKing-2234** [comment]
![Uploading wecom-temp-6ad15f3114968fbc0b083152998b65e3.png…]()

**Comment by LichKing-2234** [comment]
Hi, you should not use `PlatformViewLink`, pls use `AndroidView` on Android and `UiKitView` on iOS.
<img width="648" alt="wecom-temp-6ad15f3114968fbc0b083152998b65e3" src="https://user-images.githubusercontent.com/9312526/124605918-fb76d480-de9e-11eb-8f3d-fb367693762b.png">

you can refer to our SDK.
![wecom-temp-ad2a8754d38a65575520bd6078d2c863](https://user-images.githubusercontent.com/9312526/124606113-27925580-de9f-11eb-9cec-3b12b6b52b24.png)

**Comment by xinoxapps** [comment]
Strange, but it did solve the problem. Seems to be a problem with PlatformViewLink.

Thank you for looking into it!
