### ISSUE TITLE
 Prerelease: 4.1.0-alpha.2: publish error AgoraRTCError INVALID_OPERATION: audience can not publish stream on flutter web

### ISSUE THREAD

**Issue by hateftad** [AgoraIO/Agora-Flutter-SDK#356]
On  Prerelease: 4.1.0-alpha.2

When trying to join a stream with the role set as Audience the error 

**publish error AgoraRTCError INVALID_OPERATION: audience can not publish stream**

Seems to be an issue only with the web sdk, works fine on Android and iOS.

await engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await engine.setClientRole(ClientRole.Audience);
engine.joinChannel(null, "channelName", null, 0);

Let me know if you need more info.

**Comment by LichKing-2234** [comment]
only broadcaster can publish stream, you can refer to the web submodule which is a wrapper by javascript.

**Comment by hateftad** [comment]
Thank you for your answer.

Yes i understand that, I am setting the role as Audience and joining a channel with a broadcaster present.

The same implementation works for iOS and Android but not for web, could it be that when the client is being created it is setting 
{ codec: "vp8", mode: "rtc" }
where as the audience needs the codec live in order to join...
Ive followed the example on that branch however it doesnt seem to work

**Comment by hateftad** [comment]
Any progress on this?

**Comment by LichKing-2234** [comment]
pls follow the dev/flutter2 branch, the alpha version is out-date.

**Comment by littleGnAl** [comment]
Pls try `agora_rtc_engine: ^5.0.0`
