### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method joinChannel on channel agora_rtc_engine) E/flutter (14086): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)

### ISSUE THREAD

**Issue by alenpmla** [AgoraIO/Agora-Flutter-SDK#358]
**Issue**

I use agora_rtc_engine: ^3.3.3. 

**Issue**
```
W/System.err(14086): java.lang.reflect.InvocationTargetException
W/System.err(14086): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14086): 	at io.agora.agora_rtc_engine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.kt:113)
W/System.err(14086): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(14086): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(14086): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/System.err(14086): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(14086): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err(14086): 	at android.os.Looper.loop(Looper.java:206)
W/System.err(14086): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
W/System.err(14086): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14086): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
W/System.err(14086): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
W/System.err(14086): Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Number
W/System.err(14086): 	at io.agora.rtc.base.RtcEngineManager.joinChannel(RtcEngine.kt:398)
W/System.err(14086): 	... 12 more
E/flutter (14086): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method joinChannel on channel agora_rtc_engine)
E/flutter (14086): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
```

**To Reproduce**

1. Initialize sdk
2. Call `joinchannel()` method

**Flutter Doctor**

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-IN)
    • Flutter version 2.2.2 at /Users/alen/Documents/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • SM F415F (mobile) • RZ8NB08AWVP • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.114

**Comment by alenpmla** [comment]
Tried all solutions which are mentioned in this ticket #253, none of them worked.

**Comment by LichKing-2234** [comment]
`Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Number`

your `uid` parameter may be null.

**Comment by waqadArshad** [comment]
> `Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Number`
> 
> your `uid` parameter may be null.

@LichKing-2234 here is my code and the uid is not null.

```
final AgoraClient client = AgoraClient(
    agoraConnectionData: AgoraConnectionData(
      appId: "40216abc119348c4a6236c11ab1a0c3e",
      tokenUrl: "https://nikah----match.herokuapp.com",
      channelName: channelName,
      uid: 0,
    ),
    enabledPermission: [
      Permission.camera,
      Permission.microphone,
    ],
  );
```

This error comes for the first one or two tries after opening the app everytime I open the app and try to initiate a call and on the third or maybe 4th try. it works. what could be the possible reason?

**Comment by littleGnAl** [comment]
Hello @waqadArshad , is possible to share the implementation of the joinChannel?

**Comment by waqadArshad** [comment]
> Hello @waqadArshad , is possible to share the implementation of the joinChannel?

@littleGnAl Hi, thanks for getting back to me. the thing is that the version of the plugin I was using was a bit old and this error went away after updating the plugin version. But I am still getting another error if u can help me with that, please have a look here: [PlatformException(-17, request to join channel is rejected, null, null) Or when I end the call PlatformException(-7, , null, null)](https://github.com/AgoraIO-Community/Flutter-UIKit/issues/92#issue-1284899112)
