### ISSUE TITLE
Audio does not work in web version (dev/flutter2 branch)

### ISSUE THREAD

**Issue by reeteshranjan** [AgoraIO/Agora-Flutter-SDK#365]
**Describe the bug**

Audio does not work on the web version (main issue: https://github.com/AgoraIO/Agora-Flutter-SDK/issues/63) of the example app. The audio of what a user says after joining the channel is not heard by other user joined in the session.

**To Reproduce**

Steps to reproduce the behaviour:

1. Build the release version of the example app: `$ flutter build web` providing appropriate tokens, app IDs etc. (I built it twice, with tokens and UIDs of 2 users, 1 used in each build)
2. Setup a local domain or an actual domain with the root being the build directory
3. For 1st user, open the domain URL in your browser
4. Click 'JoinChannelAudio'
5. Click 'Join Channel'
6. Move sliders for Recording volume and Playback volume to maximum
7. For 2nd user, repeat steps 3-6 in a separate browser, on a separate laptop
8. Attempt talking on both browser sessions
9. Toggle between earpiece and speakerphone and repeat step 8

**Expected behaviour**

In steps 8 and 9, one should be able to hear what other user speaks.

**Screenshots**

N/A (it's about audio)

**Desktop (please complete the following information):**
 
- OS: macOS Big Sur 11.4
 - Browsers: Chrome 89.0, Brave 1.26.74, Safari 14.1.1

**Smartphone (please complete the following information):**

- Not applicable (it's about the web version)

**Comment by LichKing-2234** [comment]
Sorry for the late reply, I am so busy,  I will take a look today.

**Comment by reeteshranjan** [comment]
The audio works with the new JS with the same test described by me. Thank you for fixing it! @LichKing-2234

**Comment by reeteshranjan** [comment]
I have verified audio working fine in my application's web version as well. @LichKing-2234
