### ISSUE TITLE
Video streams start freezing

### ISSUE THREAD

**Issue by florianthiel** [AgoraIO/Agora-Flutter-SDK#366]
Sometimes video streams start freezing (local and remote) after approximately 100 minutes. The only way to fix this is to end the call and start a new one.

**To Reproduce**
Start a video call:
```
_engine = await RtcEngine.create('XXX');
_engine!.setEventHandler(RtcEngineEventHandler(
  joinChannelSuccess: joinChannelSuccess,
  userJoined: userJoined,
  userOffline: userOffline,
  videoSizeChanged: videoSizeChanged,
  localUserRegistered: localUserRegistered,
  error: (error) {
    print(error);
  },
));

final config = VideoEncoderConfiguration();
config.dimensions = VideoDimensions(1280, 720);
config.frameRate = VideoFrameRate.Fps24;
config.bitrate = 1710;
config.degradationPrefer = DegradationPreference.MaintainBalanced;

await _engine!.setVideoEncoderConfiguration(config);
await _engine!.registerLocalUserAccount('XXX', Client.instance.currentUser!.id);
await _engine!.enableAudio();
await _engine!.enableVideo();
await _engine!.joinChannelWithUserAccount(token, training.id, Client.instance.currentUser!.id);
```
Wait approximately 100 minutes than the video streams start freezing. Audio is still working

**Expected behavior**
Video streams don't freeze in a long video call

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11"
 - OS: iOS 14.6
 - Version 4.0.2 Flutter 2.2.3

**Additional context**
Part of the logs of the call: 
[agorasdk_1.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/6776445/agorasdk_1.log)

**Comment by LichKing-2234** [comment]
Sorry for the late reply, is this issue still exist?

**Comment by florianthiel** [comment]
Couldn't reproduce this issue in the latest version
