### ISSUE TITLE
Implementation of Custom Answer Screen with App is terminated

### ISSUE THREAD

**Issue by Samson11** [AgoraIO/Agora-Flutter-SDK#367]
**Is your feature request related to a problem? Please describe.**
I am working on a chat app and voice call is necessary but i couldn't implement it when the app is terminated

**Describe the solution you'd like**
A way to implement a custom answer screen when app is terminated

**Comment by N-tech-o** [comment]
yes

**Comment by LichKing-2234** [comment]
you should use callkit on ios and use  connectionservice on android.
