### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by harsuu942** [AgoraIO/Agora-Flutter-SDK#371]
![Screenshot_1626091276](https://user-images.githubusercontent.com/17287262/125414838-b42276be-f6e5-41a5-b676-7b64c27d7021.png)

We tested Agora flutter SDK in the demo app in landscape mode with two different scenarios and we got this result.

How can we solve that first scenario?

1) If the capturer device and the player device both capture video different facing camera (front camera and back camera). 
it shows the rotated video in the player device

2) If the capturer device and the player device both capture video same facing camera (front camera or back camera).
it shows the perfect result in the player device.

**Comment by LichKing-2234** [comment]
just unlock the screen orientation and test again, then share the screenshot pls.

**Comment by harsuu942** [comment]
It's working when the unlock screen orientation. but what about when the screen is a lock orientation?
can you suggest?

**Comment by LichKing-2234** [comment]
If you lock the screen orientation, just work on the locked orientation is expect.
