### ISSUE TITLE
Local SurfaceView not working

### ISSUE THREAD

**Issue by sanjidbillah** [AgoraIO/Agora-Flutter-SDK#374]
[agora video call](https://github.com/tadaspetra/agora/tree/main/video-call)
I have used this project and build an APK.

While checking apk  , It shows black screen in local surface view.

noticeably , i did not change any code or anything .

**Comment by LichKing-2234** [comment]
make sure the SurfaceView is created after RtcEngine init and granted permissions.

**Comment by sanjidbillah** [comment]
@LichKing-2234  then how remote view is ok for me?
only local surface view not working

**Comment by LichKing-2234** [comment]
the remote view must be created after the engine created.
