### ISSUE TITLE
Mirror mode does not work in web version (dev/flutter2)

### ISSUE THREAD

**Issue by reeteshranjan** [AgoraIO/Agora-Flutter-SDK#376]
**Describe the bug**
Setting the mirror mode during `setVideoEncoderConfiguration` or in calls to `RtcRemoteView.SurfaceView` / `RtcLocalView.SurfaceView` works on Android and iOS; but not on web.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: Chrome, Brave
 - Version: latest

**Comment by LichKing-2234** [comment]
this just for android and ios now.

**Comment by reeteshranjan** [comment]
@LichKing-2234 I was told by Agora support that web version is expected to be live in August sometime. Would mirror mode be part of the official web support by that time? Or it won't be supported at all?

**Comment by LichKing-2234** [comment]
may implement it by workaround, such as css?

**Comment by reeteshranjan** [comment]
> may implement it by workaround, such as css?

How do I do that using Flutter SDK (currently building the web version using `dev/flutter2` branch)?

**Comment by reeteshranjan** [comment]
@LichKing-2234 any updates on this please? A duplicate ticket https://github.com/AgoraIO/Agora-Flutter-SDK/issues/420 added, too.

**Comment by reeteshranjan** [comment]
https://github.com/AgoraIO/Agora-Flutter-SDK/issues/420#issuecomment-925540372

**Comment by LichKing-2234** [comment]
fixed. pls follow #420
