### ISSUE TITLE
Unhandled Exception: PlatformException(7, not initialized, null, null)

### ISSUE THREAD

**Issue by coder-Aayush** [AgoraIO/Agora-Flutter-SDK#379]
I have initialized the agora engine in my flutter app. when I try to destroy the engine/leave channel it throws the following error.
`Unhandled Exception: PlatformException(7, not initialized, null, null)`
Everything works properly but it throws errors while calling `destroy` and `leaveChannel`

## Code 
```dart
initAgora(context) async {
    try {
      Map<Permission, PermissionStatus> permission =
          await [Permission.microphone, Permission.camera].request();
      if (permission.values.toList()[0].isGranted &&
          permission.values.toList()[1].isGranted) {
        _engine = await RtcEngine.createWithConfig(RtcEngineConfig(appId));
      } else {
      }
    } catch (e) {
    }
  }

 dispose() {
   await _engine?.destroy();
   await _engine?.leaveChannel();
  }
```

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Adnroid
 - Version 10

**Comment by LichKing-2234** [comment]
you should call leaveChannel before destroy.
