### ISSUE TITLE
A problem occurred configuring root project 'agora_rtc_engine'.

### ISSUE THREAD

**Issue by abhayzadoo** [AgoraIO/Agora-Flutter-SDK#380]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

 Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'agora_rtc_engine'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin agora_rtc_engine could not be built due to the issue above.

Please Help.

**Comment by LichKing-2234** [comment]
pls follow this step.

```
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```
