### ISSUE TITLE
CAN_NOT_PUBLISH_MULTIPLE_VIDEO_TRACKS during screen sharing using example code in Flutter web

### ISSUE THREAD

**Issue by mrtordoide** [AgoraIO/Agora-Flutter-SDK#384]
Hello,

When I screen share, only the local user can see the share but none of the remote users receive it. On top of it, there is a error in browser console saying, CAN_NOT_PUBLISH_MULTIPLE_VIDEO_TRACKS. I don't know if this is a bug but I am a bit confused here. Thanks for the help!

Below is my implementation of the RtcEngine for video call and screensharing:

```
Future<void> initialize() async {
    _engine = await RtcEngine.createWithContext(RtcEngineContext(config.appId));
    this._addListener();
    await _engine.enableVideo();
    await _engine.startPreview();
    setState(() {
      startPreview = true;
    });
    await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await this._updateClientRole(role);
    await _engine.joinChannel(null, config.channelId, null, 0, null);
    await _engine.muteLocalAudioStream(muted);
  }
```
For screen sharing:
```
_startScreenShare() async {
    final helper = _engine.getScreenShareHelper();
    helper.setEventHandler(RtcEngineEventHandler(
        joinChannelSuccess: (String channel, int uid, int elapsed) {
      _infoStrings
          .add('ScreenSharing joinChannelSuccess $channel $uid $elapsed');
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content:
            Text('ScreenSharing joinChannelSuccess $channel $uid $elapsed'),
      ));
    }, userJoined: (uid, elapsed) {
      print("Screensharing userjoined");
    }));
    await helper.initialize(RtcEngineContext(config.appId));
    await helper.disableAudio();
    await helper.enableVideo();
    await helper.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await helper.setClientRole(ClientRole.Broadcaster);
    await helper.joinChannel(
        null, config.channelId, null, config.screenSharingUid);
    var windowId = 0;
    if (!kIsWeb && (Platform.isWindows || Platform.isMacOS)) {
      final windows = _engine.enumerateWindows();
      if (windows.isNotEmpty) {
        windowId = windows[0].id;
      }
    }
    await helper.startScreenCaptureByWindowId(windowId);
    setState(() {
      screenSharing = true;
    });
  }
```

**Comment by LichKing-2234** [comment]
pls follow our example, you should call this api before join channel.

**Comment by LichKing-2234** [comment]
but it can be optimized, I will do it as soon as possible.

**Comment by mrtordoide** [comment]
Sure! and actually, I just got it working after you pointed out calling api before joining channel and it is working. Seems like I was confused about this because I was only testing it on web implementations. It is working fine while viewing from Mobile implementations. Thanks!

**Comment by LichKing-2234** [comment]
mobile? screen share not support on it yet. maybe you means desktop?

**Comment by mrtordoide** [comment]
Mobile is only receiving screen share stream but yes, Desktop web sharing the screen here. 

Related to this, I had one more issue and that is regarding rendering of remote video streams. Are remote video streams automatically updated by rtc engine or should we implement somethings in call back to update the remote video stream state changing?

[Web] For instance, user A is already in channel and user B joins, in this case, user A can see his local video but the second user’s remote video is a blank space for user A. But for user B, both videos displays. This happens when joining for the first time. But after joining too, when a remote user B mutes his video and unmute his video back, it does not update new video for user A. Could you let me know if this is something I need to configure on my side with call backs or it should be handled auto?

**Comment by LichKing-2234** [comment]
@mrtordoide is our example working?

**Comment by mrtordoide** [comment]
Yes, the screen sharing example is working now but not the updating of remote video streams. Could you check my previous comment regarding the issue? @LichKing-2234

**Comment by LichKing-2234** [comment]
I mean the remote video is working on our example?

**Comment by mrtordoide** [comment]
@LichKing-2234 It is also not working in the example for me. I tried JoinChannelVideo option too. The remote user video does not load.

**Comment by mrtordoide** [comment]
@LichKing-2234 I am facing this issue in dev/flutter2 where `RtcRemoteView.SurfaceView` is not working. I will create another issue with more details.
