### ISSUE TITLE
getUserInfoByUserAccount doesn't return data when given user has role as audience

### ISSUE THREAD

**Issue by AV2RY** [AgoraIO/Agora-Flutter-SDK#386]
I'm making voice chat app with RTC and RTM using the username for joining and using getUserInfoByUserAccount call to get their id but it doesn't return the uid of a user who has role as audience. Is that a bug or a normal behavior?

1. Create and join channel using joinChannelWithUserAccount with two different users (in my case one has role as broadcaster and the other one has audience)
2. Create and join RTM channel with same channelName with the two users.
3. onMemberJoined method of RTM, call rtc getUserInfoByUserAccount to get the uid of the user who joined.

**Expected behavior**
The uid of the user who has role as audience should be got but it works only if the user has broadcaster role.

**Comment by NohchoBx** [comment]
+1

**Comment by LichKing-2234** [comment]
you should call this API at the event of RTC.
