### ISSUE TITLE
An API to get the mute state of all users

### ISSUE THREAD

**Issue by aitaro** [AgoraIO/Agora-Flutter-SDK#387]
**Is your feature request related to a problem? Please describe.**
There is no way to get the mute state of remote audio. Since remoteAudioStateChanged can detect the mute state only when the state is changed, it is not possible to know who is in the mute state and who is not in the mute state when joining the channel.

**Describe the solution you'd like**
I need some API to get the mute state of all users joining the channel.

**Comment by LichKing-2234** [comment]
Sorry, we did not support it yet. The best way is to implement it on your server.

**Comment by aitaro** [comment]
Thanks for providing information. I don't want to implement it on my server if possible. Mute data will be double-managed, and it makes my app more prone to bugs.
I would appreciate it if you could consider implementing this feature.
