### ISSUE TITLE
RtcRemoteView.SurfaceView() not working in example project (Flutter Web)

### ISSUE THREAD

**Issue by mrtordoide** [AgoraIO/Agora-Flutter-SDK#388]
**Describe the bug**
In dev/flutter2 branch, while running the example project, everything is working fine except for `RtcRemoteView.SurfaceView()`.

**To Reproduce**
1. Run the example project in dev/flutter2
2. Go to JoinChannelVideo menu
3. Join Channel with atleast one remote user.

**Expected behavior**
Only local video loads, remote videos do not load.

**Screenshots**
Please see this screen recording where left side are my remote users and right is the local: https://streamable.com/u7aw0p

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 92

**Comment by tjcampanella** [comment]
I have had this same issue. Has anyone figured out the fix?

**Comment by mrtordoide** [comment]
> I have had this same issue. Has anyone figured out the fix?

I haven't had any success. Still looking for a fix.

**Comment by mrtordoide** [comment]
So, I was able to get it working by making some changes in rtc engine callback handlers where I noticed that whenever a new user joins, the video loads if I run `remoteUid = remoteUid.of(remoteUid.reversed)` in each of the callback setState methods. But it is still not very reliable.

**Comment by tjcampanella** [comment]
Interesting I am eager to see what one of the developers has to say about this.

**Comment by LichKing-2234** [comment]
because the video track not be subscribed when the `userJoined` event is received. I have fixed it.
