### ISSUE TITLE
Camera doesn't work in web example, dev/flutter2 branch

### ISSUE THREAD

**Issue by marinat** [AgoraIO/Agora-Flutter-SDK#389]
I'm just trying to run example, I modified only agora config file.

I cloned project from repo, chose dev/flutter2 branch. 
I run project on mac os in chrome from android studio Flutter 2.2.3, click 'JoinChannelVideo' menu item and give all needed permissions, but camera preview is black. Then I get `[log] error ErrorCode.StartCamera` in console.

@LichKing-2234

**Comment by LichKing-2234** [comment]
just get error when first run?

**Comment by LichKing-2234** [comment]
I have tested it, it works when I give camera permission.

**Comment by marinat** [comment]
@LichKing-2234 Thanks for reply.
This error appears when I click on 'Join channel' like on your last screenshot and give permission to using mic. But before I click on it I still have no working camera preview, just black surface. Pls show which config do you use for agora except appId.

**Comment by LichKing-2234** [comment]
you can open the chrome console, and see the error logs.

**Comment by marinat** [comment]
> you can open the chrome console, and see the error logs.

I've got this:
<img width="704" alt="Снимок экрана 2021-08-12 в 10 17 26" src="https://user-images.githubusercontent.com/978076/129154434-64395dbe-0f9a-4d2b-a048-c9c4aefeafe6.png">

On mobile devices all ok, internet is stable through wifi

**Comment by LichKing-2234** [comment]
seem like no error? 
try to fetch the error log while printing `[log] error ErrorCode.StartCamera`?

**Comment by marinat** [comment]
> seem like no error?
> try to fetch the error log while printing `[log] error ErrorCode.StartCamera`?

I've tried to open skype settings to check is my camera work at all, and now after restart app all works! F** magic! Thank you for your help anyway!
