### ISSUE TITLE
Pwa support

### ISSUE THREAD

**Issue by AlirezaDaryani** [AgoraIO/Agora-Flutter-SDK#391]
I want to develop application on mobile devices and pwa , is there any support for web for sdk?

**Comment by mrtordoide** [comment]
You can check example in [dev/flutter2](https://github.com/AgoraIO/Agora-Flutter-SDK/tree/dev/flutter2) branch.

**Comment by AlirezaDaryani** [comment]
Ok, I will, But when it will be merge with release?

**Comment by LichKing-2234** [comment]
Pls follow https://github.com/AgoraIO/Agora-Flutter-SDK/tree/dev/flutter2-iris
