### ISSUE TITLE
Unhandled Exception: PlatformException(4, not supported, null, null)

### ISSUE THREAD

**Issue by nizwar** [AgoraIO/Agora-Flutter-SDK#394]
I got this problem while calling `setClientRole`, this happened from 4.0.5 and newest

![Screen Shot 2021-08-17 at 01 31 24](https://user-images.githubusercontent.com/33113137/129612455-610d98b6-e425-403b-876e-c49f36597fdc.png)

and this is my code
![Screen Shot 2021-08-17 at 00 35 18](https://user-images.githubusercontent.com/33113137/129605668-4a76fc9c-fd3b-4ed4-8d30-1c750baacfee.png)

its working fine with 4.0.2, and i'm testing with IOS (android not tested yet)

**Comment by EmmanuelJoshua** [comment]
Checkout their example code from that SDK, they made some changes I guess.

**Comment by nizwar** [comment]
i just read that `setClientRole` only be able to get called  with `LiveBroadcasting` profile
```dart 
await rtc.setChannelProfile(ChannelProfile.LiveBroadcasting);
await rtc.setClientRole(ClientRole.Audience);`
