### ISSUE TITLE
agora sdk update for flutter v1.26

### ISSUE THREAD

**Issue by jin-dub** [AgoraIO/Agora-Flutter-SDK#399]
I took a mail from agora 

---

iOS 15 beta and MacOS Monterey 12 beta are scheduled to be released in the next few months. Based on our thorough testing of these against the Agora Video, Voice, and Real-Time Messaging SDKs, we have found that there is a compatibility issue which leads to a crash.
To ensure this issue does not affect your user experience, we strongly recommend that you upgrade to the recommended version of the Video, Voice, and Real-Time Messaging (RTM) SDKs.
If your app is running with Agora Video and/or Voice SDKs, please upgrade to the latest version below based on your SDK platform.
iOS Audio SDK – Latest SDK version 3.5.0.1 / Agile SDK version 3.4.7
iOS Video SDK – Latest SDK version 3.5.0.2 / Agile SDK version 3.4.7
Mac Audio SDK – Latest SDK version 3.5.0.1 / Agile SDK version 3.4.7
Mac Video SDK – Latest SDK version 3.5.0.2 / Agile SDK version 3.4.7
Electron SDK – Latest SDK version 3.4.6
Unity SDK – Latest SDK version 3.4.6
Flutter - Latest SDK version 4.0.6
React Native – Latest SDK version 3.4.6
If you are running with Agora Real-Time Messaging (RTM) SDK, please upgrade to the latest version below based on your SDK platform.
iOS SDK - Latest SDK version 1.4.8
MacOS SDK – Latest SDK version 1.4.8
If you do not upgrade, your app will crash after you initialize the Agora SDK. 
If you have any questions, please feel free to contact support@agora.io or submit a ticket to our Support Team. 
Thank you!
 Team Agora
 
 
 ---
 
 
But i using flutter v1.26

Is there any solution for me?

**Comment by LichKing-2234** [comment]
you can use this version.
https://pub.dev/packages/agora_rtc_engine/versions/3.4.6
