### ISSUE TITLE
iOS 15 / MacOS Monterey 12 Compatibility Issue 

### ISSUE THREAD

**Issue by kadariyaujwal** [AgoraIO/Agora-Flutter-SDK#400]
Shall we get a new version soon? or is it already fixed in flutter sdk ? And which version? 

Agora Suggests these:
iOS Audio SDK – Latest SDK version 3.5.0.1 
iOS Video SDK – Latest SDK version 3.5.0.2 

Please let me know from which version of agora_rtc_engine the compatibility issue will be resolved / has been resolved.

Thanks.

**Comment by kadariyaujwal** [comment]
Important Notice: iOS 15 / MacOS Monterey 12 Compatibility Issue Handling
Published:
2021-08-14 18:45
Hi developers,



iOS 15 beta and MacOS Monterey 12 beta are scheduled to be released in the next few months. Based on our thorough testing of these against the Agora Video, Voice, and Real-Time Messaging SDKs, we have found that there is a compatibility issue which leads to a crash.



To ensure this issue does not affect your user experience, we strongly recommend that you upgrade to the recommended version of the Video, Voice, and Real-Time Messaging (RTM) SDKs.



If your app is running with Agora Video and/or Voice SDKs, please upgrade to the latest version below based on your SDK platform.

iOS Audio SDK – Latest SDK version 3.5.0.1 / Agile SDK version 3.4.7
iOS Video SDK – Latest SDK version 3.5.0.2 / Agile SDK version 3.4.7
Mac Audio SDK – Latest SDK version 3.5.0.1 / Agile SDK version 3.4.7
Mac Video SDK – Latest SDK version 3.5.0.2 / Agile SDK version 3.4.7
Electron SDK – Latest SDK version 3.4.6
Unity SDK – Latest SDK version 3.4.6
Flutter - Latest SDK version 4.0.6
React Native – Latest SDK version 3.4.6


If you are running with Agora Real-Time Messaging (RTM) SDK, please upgrade to the latest version below based on your SDK platform.

iOS SDK - Latest SDK version 1.4.8
MacOS SDK – Latest SDK version 1.4.8


**If you do not upgrade, your app will crash after you initialize the Agora SDK.**

**Comment by LichKing-2234** [comment]
4.0.6 for flutter2

3.4.6 for flutter1
