### ISSUE TITLE
Can't build example on android (br: dev/flutter2)

### ISSUE THREAD

**Issue by marinat** [AgoraIO/Agora-Flutter-SDK#408]
Got this errors:
`e: /FlutterLibraries/Agora-Flutter-SDK/android/src/main/java/io/agora/rtc/base/RtcChannel.kt: (348, 56): Unresolved reference: pauseAllChannelMediaRelay
e: /FlutterLibraries/Agora-Flutter-SDK/android/src/main/java/io/agora/rtc/base/RtcChannel.kt: (352, 56): Unresolved reference: resumeAllChannelMediaRelay
e: /FlutterLibraries/Agora-Flutter-SDK/android/src/main/java/io/agora/rtc/base/RtcEngine.kt: (1025, 27): Unresolved reference: pauseAllChannelMediaRelay
e: /FlutterLibraries/Agora-Flutter-SDK/android/src/main/java/io/agora/rtc/base/RtcEngine.kt: (1029, 27): Unresolved reference: resumeAllChannelMediaRelay`
@LichKing-2234

**Comment by marinat** [comment]
Same on ios: 
`/FlutterLibraries/Agora-Flutter-SDK/ios/Classes/Base/RtcChannel.swift:395:61: error: value of type 'AgoraRtcChannel' has no member 'pauseAllChannelMediaRelay'
            callback.code(self[params["channelId"] as! String]?.pauseAllChannelMediaRelay())
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~
    /FlutterLibraries/Agora-Flutter-SDK/ios/Classes/Base/RtcChannel.swift:399:61: error: value of type 'AgoraRtcChannel' has no member 'resumeAllChannelMediaRelay'
            callback.code(self[params["channelId"] as! String]?.resumeAllChannelMediaRelay())
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by reeteshranjan** [comment]
Today I pulled the latest on `dev/flutter2` and getting the same build error. @LichKing-2234 could you please look at it urgently?

**Comment by LichKing-2234** [comment]
I will fix it today

**Comment by LichKing-2234** [comment]
Fixed
