### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by shenlanchenwei** [AgoraIO/Agora-Flutter-SDK#411]
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![WeChat594197e894628853a9f2d11cbe9f667e](https://user-images.githubusercontent.com/6754634/131802154-a4a5a12a-e073-48ec-baae-9b43d8e7adfb.png)

**Comment by LichKing-2234** [comment]
这种问题一般是你的android build tools版本太低

**Comment by LichKing-2234** [comment]
可以试试4.1.0

**Comment by shenlanchenwei** [comment]
buildscript {
    ext.kotlin_version = '1.4.31'
}

**Comment by LichKing-2234** [comment]
那就是kotlin版本和gradle版本不匹配
