### ISSUE TITLE
Implementation of real-time messaging in flutter web to Real-time Messaging

### ISSUE THREAD

**Issue by htv-nguyenlc** [AgoraIO/Agora-Flutter-SDK#416]
Can I execute real-time message for flutter web now?

**Comment by htv-nguyenlc** [comment]
Sorry, I found another thread, and it doesn't support flutter-web yet. So I will close this issue .https://github.com/AgoraIO/Agora-Flutter-RTM-SDK/issues/83

**Comment by ThangD** [comment]
@htv-nguyenlc I think Agora-Flutter-RTM is another package.
@LichKing-2234 Could you please help to confirm?
