### ISSUE TITLE
Remote video not working.

### ISSUE THREAD

**Issue by AmmarHazem** [AgoraIO/Agora-Flutter-SDK#418]
**Describe the bug**
Remote video not working.

**To Reproduce**
1. Run your example project
2. Click on JoinChannelVideo
3. Click on Join Channel
4. The local video will start but the remote video will not show 

Although in the remoteVideoStateChanged call back I'm getting a status of VideoRemoteState.Starting 

**Expected behavior**
The remote video should be working

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS & Android
 - Version: Flutter SDK version is 4.0.6

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - OS: iOS 14.7
 - Device: [e.g. Nokia C20]
 - OS: Android 11

Please help me fix this issue asap.

**Comment by LichKing-2234** [comment]
please provide SDK log

**Comment by AmmarHazem** [comment]
That was a network issue from my side. Thank you.
