### ISSUE TITLE
how to create channels dynamically for one-to-one voice calls?

### ISSUE THREAD

**Issue by haoyuant** [AgoraIO/Agora-Flutter-SDK#421]
Hello I am fairly new to this service and not sure if it is the right tool that I should use.
I want to make an app that allows users to make voice call to other individual to have one-to-one chat, but the demo I checked seems to be sharing the same channel for all users, if there a way to create a new channel programmatically when a user wants to call the other one?

**Comment by AdminBizzfinity** [comment]
hello I am also facing the same issue regarding video call.

**Comment by LichKing-2234** [comment]
you can let different clients join different channels by using different channel IDs.

**Comment by jaypal1046** [comment]
@AdminBizzfinity @haoyuant you can create a server to generate a token for you. You can use either nodejs or golang for creating a server.
The link below contains the full code along with its explaination for golang server:
https://www.agora.io/en/blog/how-to-build-a-token-server-using-golang/?utm_campaign=build-a-video-call-flutter-app-with-agora&utm_source=youtube&utm_medium=organic-social
The following link is for nodejs server:
https://www.agora.io/en/blog/how-to-build-a-token-server-for-agora-applications-using-nodejs/

**Comment by haoyuant** [comment]
Many Thanks @jaypal1046 :)  I think it would be good to have a clearer demo/tutorial for this scenario, looks like many people are also confused when I was searching the solution online.
