### ISSUE TITLE
AgoraRtcWrapper.bundle.js for flutter web

### ISSUE THREAD

**Issue by mehrbat** [AgoraIO/Agora-Flutter-SDK#430]
Can someone please explain to me 

- where does AgoraRtcWrapper.bundle.js come from? does it get created when I add web support to my flutter project?
- what is the correct way of updating it?

Thanks heaps in advance.

**Comment by LichKing-2234** [comment]
You can refer to https://github.com/AgoraIO/Agora-Flutter-SDK/blob/dev/flutter2/README.md#web

**Comment by Akash-Manjhi** [comment]
@LichKing-2234  I have added AgoraRtcWrapper.bundle.js inside  web  folder and added script 
<script src="AgoraRtcWrapper.bundle.js" type="application/javascript"></script>
I am using:-   agora_rtc_engine: ^4.1.0-alpha.2
but while running in chrome(web) it gives error "No implementation found for method create on channel agora_rtc_engine".
Can you please put some light in this, it will be very helpful.
Thanks in advance.

**Comment by Ben-chedli** [comment]
Hi all,
I am currently facing the same issue, added AgoraRtcWrapper.bundle.js inside web folder then <script src="AgoraRtcWrapper.bundle.js" type="application/javascript"></script> in my index.html file, after importing agora_rtc_engine: ^4.1.0-alpha.2, running the project on chrome(web) gives "
![image](https://user-images.githubusercontent.com/64413708/153442205-95baf82c-6b68-4439-b7ee-883bb9794655.png)
"

**Comment by LichKing-2234** [comment]
pls use the branch dev/flutter2-iris before we release it.

**Comment by Ben-chedli** [comment]
Hi @LichKing-2234 ,
thank you for the quick reply, but I just don't understand from the description what should I do in order to import the plugin ! As I mentioned earlier I already downloaded 'AgoraRtcWrapper.bundle.js' and put it in the web folder of my app then added '<script src="AgoraRtcWrapper.bundle.js" type="application/javascript"></script>' to my 'index.html' ! Is there something else I should do ? Am I not supposed to add 'agora_rtc_engine: ^4.1.0-alpha.2' in pubspec.yaml ? Sorry If my questions are obvious and thanks again for the support.
Best regards

**Comment by plutoless** [comment]
@Ben-chedli the dev/flutter2-iris is a dev branch in this repository. you will have to use the source as local dependency instead of using the published one.

**Comment by Ben-chedli** [comment]
@plutoless Hi and thank you for your reply,
So you mean I need to add the package in my pubspec.yaml like this 
agora_rtc_engine:
    git:
      url: git'https://github.com/AgoraIO/Flutter-SDK'
      ref: dev/flutter2-iris

**Comment by plutoless** [comment]
@Ben-chedli you can refer to this post https://stackoverflow.com/questions/51238420/how-to-use-local-flutter-package-in-another-flutter-application for how to import local dependency. to get the source code you will need to clone this repo and switch to the branch we mentioned.

**Comment by Ben-chedli** [comment]
Hi again @plutoless ,
I was able to add the dependency and run the example, thank you for the help.
Now though I am facing this issue evetime I run the example.. any idea why is this happening ?

![Capture](https://user-images.githubusercontent.com/64413708/154069994-c2bc865c-f107-46d6-b7fb-8df21cfed3d0.JPG)

**Comment by littleGnAl** [comment]
Hello @Ben-chedli, try adding a `Container` with `height`/`width` as the parent widget.

**Comment by Ben-chedli** [comment]
Hi @littleGnAl ,
I tried to strip it to the most basic display so it shows just my local camera feed, still the same issue every time I click join !

![Capture_prob_01](https://user-images.githubusercontent.com/64413708/154077122-a0ce38b7-40a5-464d-a09a-ec5e2d0a31d1.JPG)

**Comment by littleGnAl** [comment]
@Ben-chedli It's a bug, we will fix it these few days. 
Btw, you'd better edit your comment, seems it leaks something.

**Comment by littleGnAl** [comment]
@Ben-chedli This issue had been fixed, pls update the latest code of `dev/flutter2-iris` branch

**Comment by Ben-chedli** [comment]
Hi @littleGnAl,
Thank you for the support, this is the result when I try to join a channel as local from the web and then try to join the same channel from my android device as remote, is the plugin supposed to be compatible cross platforms ?

![Capture](https://user-images.githubusercontent.com/64413708/154486671-8c793974-6679-4917-8891-7bdda8e109dc.JPG)

**Comment by littleGnAl** [comment]
The example is compatible with cross platforms, did you run the same example on your Android devices?

**Comment by Ben-chedli** [comment]
@littleGnAl no the project we tested on the android device is our released app built with agora_rtc_engine: ^3.2.1, we're now trying to release a web app that could communicate with that released Android/iOS app.
So in order to do that, do we need to update that app with the latest code of dev/flutter2-iris branch too ?

**Comment by LichKing-2234** [comment]
Have you use string uid?

**Comment by Ben-chedli** [comment]
@littleGnAl no actually, just added channel id and app id in the config

**Comment by littleGnAl** [comment]
@Ben-chedli Can you try running the example on other platform (Android/iOS/macOS/Windows) to see it work or not?

**Comment by Ben-chedli** [comment]
@littleGnAl yes the example runs well on an android device and I don't see the "[AgoraSurfaceView] may not be set error" printed in the console, even when I toggle rendered by SurfaceView instead of the default TextureView.

**Comment by littleGnAl** [comment]
@Ben-chedli 
If you join the channel with `ChannelMediaOptions`, make sure you set `publishLocalVideo` to `true`.
It's hard to guess what went wrong, I think a reproducible demo should be helpful for your case.

**Comment by littleGnAl** [comment]
@Ben-chedli 
There's a relative issue that had been fixed, you can try `agora_rtc_engine: ^5.0.0` to see if it works or not.
