### ISSUE TITLE
新的版本安卓编译报错

### ISSUE THREAD

**Issue by liangdas** [AgoraIO/Agora-Flutter-SDK#435]
**Describe the bug**

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/love/work/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-4.0.7/android/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'agora_rtc_engine'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin agora_rtc_engine could not be built due to the issue above.

**Comment by LichKing-2234** [comment]
gradle版本与kotlin版本不匹配

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO/Agora-Flutter-SDK/issues/411

**Comment by liangdas** [comment]
Agora-Flutter-SDK kotlin  1.3.72   
项目 ext.kotlin_version = '1.5.0'  
项目 gradle:3.5.4

**Comment by liangdas** [comment]
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin agora_rtc_engine...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                 2,843ms


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/love/work/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-4.0.7/android/build.gradle' line: 29
