### ISSUE TITLE
升级agora_rtc_engine: ^4.0.7 安卓编译报错

### ISSUE THREAD

**Issue by liangdas** [AgoraIO/Agora-Flutter-SDK#436]
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin agora_rtc_engine...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done 2,843ms

FAILURE: Build failed with an exception.

Where:
Build file '/Users/love/work/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-4.0.7/android/build.gradle' line: 29

Agora-Flutter-SDK kotlin 1.3.72
项目 ext.kotlin_version = '1.5.0'
项目 gradle:3.5.4

我看 Agora-Flutter-SDK kotlin=1.3.72 但我的工程不能使用1.3.72 因为有其他SDK需要更高版本

**Comment by liangdas** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/love/.gradle/caches/transforms-2/files-2.1/564d237739bcec4032e506e160761eed/core-1.7.0-beta01/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by liangdas** [comment]
加了这段代码就好了
configurations.all {
    resolutionStrategy {
        force 'androidx.core:core-ktx:1.6.0'
    }
}

**Comment by liangdas** [comment]
debug 模式下可以正常编译，release模式报错

Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     495.4s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin agora_rtc_engine...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                 2,377ms


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/love/work/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-4.0.7/android/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'agora_rtc_engine'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


The plugin agora_rtc_engine could not be built due to the issue above.

**Comment by LichKing-2234** [comment]
kotlin 1.5 需要 gradle 6.1之后的版本

**Comment by LichKing-2234** [comment]
同时，注意gradle和gradle插件的版本关系
https://developer.android.google.cn/studio/releases/gradle-plugin

**Comment by liangdas** [comment]
是混淆的原因，flutter命令模式自动开了混淆，导致编译失败，加上 --no-shrink命令就可以关闭混淆
flutter build apk --split-per-abi --no-shrink --target-platform android-arm64,android-arm --release

另外 也可以在gradle文件加上禁止混淆的配置
release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
            useProguard false
        }
