### ISSUE TITLE
[dev/flutter2] SurfaceView.screenShare() options

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Agora-Flutter-SDK#440]
Include SurfaceView() options for screenShare() constructor. 
These include renderMode, mirrorMode, etc.

In particular screenShare() starts in renderMode.Hidden which is not what you want for screen sharing and would want to make the entire screen visible to the user.

**Comment by LichKing-2234** [comment]
Supported.

**Comment by rgb1380** [comment]
@LichKing-2234 thanks heaps for the prompt update.
