### ISSUE TITLE
[Web] [Screensharing] Audio feedback issue

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Agora-Flutter-SDK#441]
- I have joined as the only user to a broadcast channel as host. 
- I enable screen sharing
- My audio feed starts echoing back to me.
- I remove screen sharing, the audio feedback is gone.

It seems that the local screensharing is playing back the audio that is picked up from the device resulting in echo.

The code that initialises screensharing is taken from the sample:

``` dart
    await helper.initialize(RtcEngineContext(agoraAppId));
    await helper.disableAudio();
//    await helper.adjustPlaybackSignalVolume(0);
//    await helper.adjustAudioMixingVolume(0);
    await helper.enableVideo();
    await helper.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await helper.setClientRole(ClientRole.Broadcaster);
``` 

Note that I even tried to adjust the playback signal volume on the screen sharing feed but that did not help either.

**Comment by LichKing-2234** [comment]
Fixed
