### ISSUE TITLE
[Question] listen to the number of connected user 

### ISSUE THREAD

**Issue by ZeraW** [AgoraIO/Agora-Flutter-SDK#445]
hi ,  is there a way to listen to the number of connected user inside a call , 
i need this to end the call when the 2nd user kill the app " RtcEngineEventHandler( userOffline: (uid, reason)" not working 
so if the first user can track the number of connected users though agora lib i can end the call whenever the number goes down to 1 user . 

also is there a way to disable these massages cuz it's annoying to work with : 
V/AudioTrack(12187): processAudioBuffer(403): obtainBuffer(312) returned 320 = 184 + 136 err 0
V/AudioTrack(12187): processAudioBuffer(403): obtainBuffer(160) returned 168 = 32 + 136 err 0
V/AudioTrack(12187): processAudioBuffer(403): obtainBuffer(128) returned 136 = 128 + 8 err 0
V/AudioTrack(12187): processAudioBuffer(403): obtainBuffer(320) returned 8 = 8 + 0 err 0
V/AudioTrack(12187): processAudioBuffer(403): obtainBuffer(320) returned 8 = 8 + 0 err 0

**Comment by LichKing-2234** [comment]
not support it. You can use the `userJoined` event to count users.

**Comment by ZeraW** [comment]
> Not support it. You can use the `userJoined` event to count users.

well this works only when user join i need solution for when user leave ( by killing the app ) `userOffline`  doesn't work if user kill the app

**Comment by ZeraW** [comment]
> > Not support it. You can use the `userJoined` event to count users.
> 
> well this works only when user join i need solution for when user leave ( by killing the app ) `userOffline` doesn't work if user kill the app

well it actually works but with 1min delay or something
