### ISSUE TITLE
agora_rtc_engine & cloud_firestore null safety not working together in  release mode

### ISSUE THREAD

**Issue by NilkanthMF** [AgoraIO/Agora-Flutter-SDK#446]
**Describe the bug**

Hello everyone
I used agora_rtc_engine with the FirebaseFirestore database

```
firebase_core: ^1.7.0
cloud_firestore: ^2.5.3
agora_rtc_engine: ^4.0.7
```

Firestore working fine but after I added agora plugins firestore database not reading & writing data in release apk
debug apk working perfectly
realtime database also work in release apk

Error: [cloud_firestore/unavailable] The service is currently unavailable. This is most likely a transient condition and may be corrected by retrying with a backoff.

**To Reproduce**

```
try{
      FirebaseFirestore.instance.collection('meetings').doc('test').set({
        'meetingStatus': 1,
        'meetingName': 'meeting_name',
        'meetingSubject': 'meeting_subject',
      }).then((value) {
        print('Add Data Successfully');
      },onError: (error){
        print('Error: $error');
      });
    }
    catch (error) {
      print('catch Error=> $error');
    }
```
debug mode working fine, problem occurred in release mode
i try to above code but not print any statement or was not added in firebase and same time I also added in realtime database. and realtime database in added data.
and when I try to read data using doc id (already added in firestore database) then occur exception Error: [cloud_firestore/unavailable] The service is currently unavailable. This is most likely a transient condition and may be corrected by retrying with a backoff.

**Expected behavior**
cloud_firestore & agora_rtc_engine working together in Null Safety 

**Information**
 Flutter -- version
Flutter 2.3.0-2.0.pre.86 • channel master • https://github.com/flutter/flutter.git
Framework • revision 67aaa0e79b (5 months ago) • 2021-05-10 08:09:02 -0400
Engine • revision f5b97d0b23
Tools • Dart 2.14.0 (build 2.14.0-74.0.dev)

**Comment by meet-mobilefirst** [comment]
Same issue for me. Any solutions ?

**Comment by shivam17099** [comment]
Same problem, Stucked in this for the last 4 days. Any suggestion would be appreciated.

**Comment by riddhimobilefirst** [comment]
Does any one find the solutions? Also happening with me. Please let me know if you find any workarounds or solutions.

**Comment by tetteu777** [comment]
i'm facing the same issue here

**Comment by AnAnD4T1** [comment]
me too, same issue

**Comment by cuong0993** [comment]
Add 

shrinkResources false
minifyEnabled false

to android/app/build.gradle file fix the issue for me
https://github.com/AgoraIO/Agora-Flutter-SDK/issues/359#issuecomment-872305467

**Comment by NilkanthMF** [comment]
@cuong0993 Thanks for a great helping hand.
