### ISSUE TITLE
Is Pinch to zoom or zoom feature supported in agora flutter? 

### ISSUE THREAD

**Issue by fldvlpr** [AgoraIO/Agora-Flutter-SDK#448]
Hello @jacob-hutchings @LichKing-2234 @PRWrl @plutoless @Matrixbirds 

I've been trying live stream broadcast demo and I'm not able to find out any way to set configs or parameters for zoom or pinch to zoom video while broadcasting video.

Also I'm getting "_engine?.isCameraZoomSupported()" to false every time in 3 different devices.

So, can anyone please tell me if there are any particular list of params or properties available for settings zoom feature in agora streaming?

Thank You

**Comment by LichKing-2234** [comment]
have you called enableVideo and startPreview?

**Comment by fldvlpr** [comment]
@LichKing-2234 

I've applied gesture recognizers to my RTCLocalView Property,

Set<Factory<OneSequenceGestureRecognizer>>? gestureRecognizers = Set()
    ..add(Factory<PanGestureRecognizer>(() => PanGestureRecognizer()))
    ..add(Factory<ScaleGestureRecognizer>(() => ScaleGestureRecognizer()))
    ..add(Factory<TapGestureRecognizer>(() => TapGestureRecognizer()))
    ..add(Factory<VerticalDragGestureRecognizer>(
        () => VerticalDragGestureRecognizer()));
        
        But, it's not working for pinch to zoom property,
        
        Let me know if there is anything else to perform?

**Comment by bhavin-concetto** [comment]
@fldvlpr  have you found the solution?

**Comment by LichKing-2234** [comment]
android or ios?

**Comment by bhavin-concetto** [comment]
In both

**Comment by LichKing-2234** [comment]
pls provide our sdk log

**Comment by bhavin-concetto** [comment]
@LichKing-2234  It solved now after I refer example again with Container wrapper.
