### ISSUE TITLE
Error while building iOS app

### ISSUE THREAD

**Issue by hardikvij195** [AgoraIO/Agora-Flutter-SDK#450]
Hi,

I have upgraded my flutter to latest version and its throwing me this error and im not able to build the app on iOS.

   Command CompileSwiftSources failed with a nonzero exit code
    ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/hardikvij/Development/AppSynergies/MingleWiseNew/ios/Pods/AgoraRtcEngine_iOS/AgoraFDExtension.framework/AgoraFDExtension' for architecture arm64

Please Help.
Thanks in Advance

**Comment by hardikvij195** [comment]
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/hardikvij/Development/AppSynergies/MingleWiseNew/ios/Pods/AgoraRtcEngine_iOS/AgoraSoundTouch.framework/AgoraSoundTouch' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by marinat** [comment]
@hardikvij195 which version of flutter do you use, I have same problem

**Comment by hardikvij195** [comment]
I upgraded my flutter to 2.5.3 and it was throwing pod issues but now I have downgraded to 2.2.3 and its working fine for me now @marinat

**Comment by uzoeddie** [comment]
@hardikvij195 Hello, you can try the commands below. I had the same issue as you.

1. Change platform version inside Podfile to something higher than 8. I used 10.0
2. Add after `flutter_additional_ios_build_settings(target)` in the Podfile
```
target.build_configurations.each do |config|
    config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
end
```
3. Go into ios folder and delete Podfile.lock
4. Naviagate back to the root folder and run
    - flutter clean
    - flutter pub get

I hope it works for you.

**Comment by marinat** [comment]
@uzoeddie it works! Many thanks!

**Comment by zionnite** [comment]
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
  end
end

**Comment by hardikvij195** [comment]
@uzoeddie  r u using the latest flutter version ?

**Comment by uzoeddie** [comment]
> @uzoeddie r u using the latest flutter version ?

@hardikvij195 At the time, I was using the latest flutter version. I had the issue when i updated my flutter version to latest.

**Comment by LichKing-2234** [comment]
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io
