### ISSUE TITLE
The process cannot access the file because it is being used by another process. 

### ISSUE THREAD

**Issue by anasssanba1** [AgoraIO/Agora-Flutter-SDK#452]

**Comment by LichKing-2234** [comment]
any detail?

**Comment by anasssanba1** [comment]
this is the error log: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:bundleLibResDebug'.
> java.nio.file.FileSystemException: C:\Users\lenovo\Desktop\flutter learning\projects\_chatfun\build\agora_rtc_engine\intermediates\library_java_res\debug\res.jar: The process cannot access the file because it is being used by another process.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
Exception: Gradle task assembleDebug failed with exit code 1
flutter doctor -v result :
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale   
    en-US)
    • Flutter version 2.5.0 at C:\Users\lenovo\flutter learning\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (4 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\lenovo\Desktop\flutter learning\android-sdk        
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\lenovo\Desktop\flutter learning\android-sdk    
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio      
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28)
      (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome
      94.0.4606.61
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge
      93.0.961.38

• No issues found!

idon't know what causing the issue yet

**Comment by LichKing-2234** [comment]
try flutter clean?

**Comment by anasssanba1** [comment]
i fixed it by adding  this:
packagingOptions {
    pickFirst 'lib/x86/libc++_shared.so'
    pickFirst 'lib/x86_64/libjsc.so'
    pickFirst 'lib/arm64-v8a/libjsc.so'
    pickFirst 'lib/arm64-v8a/libc++_shared.so'
    pickFirst 'lib/x86_64/libc++_shared.so'
    pickFirst 'lib/armeabi-v7a/libc++_shared.so'
}
to android/app/build.gradle
thank you !
