### ISSUE TITLE
Getting blank view " RtcRemoteView.SurfaceView" 

### ISSUE THREAD

**Issue by panchalAlpit** [AgoraIO/Agora-Flutter-SDK#460]
Some time ago it's working fine but after update the Flutter and "agora_rtc_engine" it's not working.
When the audience joins with the live broadcast so getting a blank view.

`    List<Widget> _getRenderViews() {
       final List<Widget> list = [RtcLocalView.SurfaceView(),];

    for(int i=0;i<_listRequestUser.length;i++){
      if(_listRequestUser[i].accepted ){
              
        list.add(RtcRemoteView.SurfaceView(uid: int.parse(_listRequestUser[i].agoraUserId),));        
        
      }
    }
![1633938064936](https://user-images.githubusercontent.com/48007084/136754084-4e6597b1-f5cd-4fdf-87e7-3ba0806344a6.JPEG)
    
    return list;
  }`

**Comment by panchalAlpit** [comment]
> does the audience user publish his video stream?

Yes

**Comment by panchalAlpit** [comment]
Please send me link again

> You can try our example to test it first.

**Comment by panchalAlpit** [comment]
> You can test the example named `JoinChannelVideo`.

My code:-
await _engine.joinChannel(null, widget.channelName, null, 0);

Example code:-
 await _engine.joinChannel(config.token, channelId, null, config.uid);
 
 Now it's mandatory to use tokens. Because I'm not used the token before and it's working. After adding the token in "joinChannel" method, So all previous methods not working.

**Comment by panchalAlpit** [comment]
> if you not use token, just set null

In my code, I have already set null but still not working.
And I have checked the one-by-one line in your "JoinChannelVideo" class example and only getting the deference is "engine.joinChannel". So I'm still not understand what's getting wrong in my code.

**Comment by panchalAlpit** [comment]
> > If I set the Client role "ClientRole.Broadcaster", So below Method is not call and If I set the "ClientRole.Audience", So it's call. So is it ok or not?
> > ` userJoined: (uid, elapsed) {
> > ```
> >     LLPrint(name: "ChekcAgora userJoined Uid", value: uid.toString());        
> > 
> >   } `
> > ```
> 
> Not call, only for broadcaster.

No, Right now it's not call in "ClientRole.Broadcaster" in my code.

**Comment by panchalAlpit** [comment]
> Hello @panchalAlpit
> 
> > Some time ago it's working fine but after update the Flutter and "agora_rtc_engine" it's not working.
> > When the audience joins with the live broadcast so getting a blank view.
> 
> * Which flutter version you used, can you show the `flutter doctor -v`?
> * Which `agora_rtc_engine ` version you are using?
> * Can you replace your [appId](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/1800a851aab7c88ce2bc7d48029dd8f62eb07203/example/lib/config/agora.config.dart#L2) and set the [token](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/1800a851aab7c88ce2bc7d48029dd8f62eb07203/example/lib/config/agora.config.dart#L5) to `null` in the example, then try run the example? So that we can be sure that the default implementation is workable.
>   ```dart
>   /// Get your own App ID at https://dashboard.agora.io/
>   const appId = 'your app id';
>   
>   /// Please refer to https://docs.agora.io/en/Agora%20Platform/token
>   const token = null;
>   
>   /// Your channel ID
>   const channelId = 'the channel id';
>   
>   /// Your int user ID
>   const uid = 0;
>   
>   /// Your string user ID
>   const stringUid = '0';
>   ```

[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/pct93/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    
    
    agora_rtc_engine: ^4.0.7

**Comment by panchalAlpit** [comment]
> And can you check is there any unexpected log output?

Yes, I have checked and I have not set any unexpected logout

**Comment by LichKing-2234** [comment]
I think the best way is to provide your demo to us, then we can test it and find the cause.

**Comment by LichKing-2234** [comment]
Could you pls create a private repo and invite me?

**Comment by markmusic2727** [comment]
Any updates? I have the same issue. RtcRemoteView.SurfaceView works on Desktop web but not on Mobile web.
