### ISSUE TITLE
fatal error: module 'agora_rtc_engine' not found

### ISSUE THREAD

**Issue by rakeshkathoju** [AgoraIO/Agora-Flutter-SDK#483]
in pubspec.yaml fille my sdk environment
environment:
  sdk: ">=2.9.2 <3.0.0"

agora_rtc_engine: ^4.0.7
agora_rtm: ^1.0.1

are the versions that i was using 

***
Xcode's output:
↳
    /Users/myMac/Downloads/ijeeni/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'agora_rtc_engine' not found
    @import agora_rtc_engine;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
**To Reproduce**

**Screenshots**
<img width="843" alt="Screenshot 2021-10-27 at 18 04 46" src="https://user-images.githubusercontent.com/23329327/139067197-bd88788a-2474-448a-8c30-be205087efb5.png">

<img width="1015" alt="Screenshot 2021-10-27 at 18 05 08" src="https://user-images.githubusercontent.com/23329327/139067213-e2456377-bc05-47f7-8546-960644ced0d4.png">

**Comment by LichKing-2234** [comment]
pls show the contents of Developement pods.

**Comment by Aadiyaara** [comment]
Hi @LichKing-2234 , I am facing the same issue, and here is the screenshot of Dev Pods.
![image](https://user-images.githubusercontent.com/31363105/139591356-2d14138a-8592-4b0f-a7cf-4c656e8d2e6e.png)

**Comment by rakeshkathoju** [comment]
<img width="686" alt="Screenshot 2021-10-31 at 22 54 23" src="https://user-images.githubusercontent.com/23329327/139594952-850eebe6-715d-48a0-92b0-9d18aec7588c.png">

**Comment by LichKing-2234** [comment]
Have you tried our example? maybe you can create a new swift file to migrate to the latest version of swift?

**Comment by yelkamel** [comment]
I have the same issue

**Comment by Aadiyaara** [comment]
@LichKing-2234 Actually I am facing this issue ever since I have updated to the latest version of XCode, yes the example app can also be not built for release due to this error. XCode Version 13.1 (13A1030d)

**Comment by Aadiyaara** [comment]
Found this to be the solution for me. https://github.com/flutter/flutter/issues/54599#issuecomment-644336055

**Comment by LichKing-2234** [comment]
> Found this to be the solution for me. [flutter/flutter#54599 (comment)](https://github.com/flutter/flutter/issues/54599#issuecomment-644336055)

is it working for all?

**Comment by bholendraofficial** [comment]
It's now working

**Comment by bholendraofficial** [comment]
Please create a complete library otherwise close your library.

**Comment by LichKing-2234** [comment]
> Please create a complete library otherwise close your library.

Our library is complete,  but I have no idea about this issue, have you tried our example? It works for me.

**Comment by alpitebiztrait** [comment]
@LichKing-2234  @bholendraofficial @Aadiyaara I'm facing the same issue. How can I solve this?
Please help guys. Two days to I'm stuck with this issue. and I missed my project deadline date because of this.
Please help gyus.

**Comment by LichKing-2234** [comment]
pls try https://github.com/flutter/flutter/issues/54599#issuecomment-644336055

**Comment by silversquall** [comment]
Any updates on this ? i am facing the same issue with the following env : 
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.3 21E230 darwin-x64, locale en-GB)

**Comment by NaarGes** [comment]
> Found this to be the solution for me. [flutter/flutter#54599 (comment)](https://github.com/flutter/flutter/issues/54599#issuecomment-644336055)

I was facing same issue and this solution worked for me

**Comment by malukishtiaq** [comment]
> > Found this to be the solution for me. [flutter/flutter#54599 (comment)](https://github.com/flutter/flutter/issues/54599#issuecomment-644336055)
> 
> I was facing same issue and this solution worked for me

try this solution please. it worked for me.

Delete **.packages, .dart_tool, .flutter-plugins, .flutter-plugins-dependencies** file from Root of project.

Delete Project Root> iOS> .symlinks

/Users/[my pc name]/Library/Developer/Xcode/DerivedData


export PATH="$PATH:/Users/[my pc name]/Documents/development/flutter/bin" && flutter clean && flutter pub get && cd ios && pod deintegrate && pod install && flutter run

**Comment by vmwsree** [comment]
I can run the app from xcode but I cant from android studio, also agora rtc is the first in line, so may be other pods can also have same issue
