### ISSUE TITLE
Fatal issue - C++ Exception in createAgoraRtcEngine

### ISSUE THREAD

**Issue by jin-dub** [AgoraIO/Agora-Flutter-SDK#485]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone SE, 7, 6+ etc..
 - OS: [e.g. iOS8.1] ios 14~15

**Additional context**

![image](https://user-images.githubusercontent.com/71740585/139607687-44f936e9-7390-4fc0-be28-83ae8a12829e.png)

**Comment by LichKing-2234** [comment]
seem like it crash on iOS 15?

**Comment by LichKing-2234** [comment]
have you upgraded to the latest version?

**Comment by jin-dub** [comment]
I using agora 4.0.6 and flutter 2.5.3
iOs 14 also crashed

**Comment by LichKing-2234** [comment]
pls try 4.0.7

**Comment by jin-dub** [comment]
> pls try 4.0.7

Thanks!
If the problem is not solved, I will open it again
