### ISSUE TITLE
IOS to Android Video call Echo from the iPhone

### ISSUE THREAD

**Issue by louisschprs** [AgoraIO/Agora-Flutter-SDK#492]
**Describe the bug**
When making a video call from android to ios there is an echo produced by the iPhone and is heard on the android device. I tested it in ideal environments and followed agoras recommendations on reducing echo. But I still receive an echo. 

When the Android user speaks he can hear himself 1 second later.  When the iOS user speaks he hears no echo. 

I have narrowed it down to the iPhone only on speakerphone. Modern iPhones have multiple microphones, I don't know if this would cause any issues. 

**To Reproduce**
Make a Video Call from an Android device to an iOS device.

**Expected behavior**
For the iPhone to apply some sort of Echo Cancelation and the Android user to not hear an echo

**Screenshots**
Not applicable 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13]
 - OS: [e.g. iOS14.8]
 - agora_rtc_engine 4.0.7
 -

**Additional context**
I have tested with multiple different iPhones calling android devices and it always an echo coming from the iPhone I have not had any call where this was not the case to me this is a consistent issue that I have no Idea how to solve.

**Comment by LichKing-2234** [comment]
seems related to https://github.com/AgoraIO/Agora-Flutter-SDK/issues/466

**Comment by louisschprs** [comment]
How is this related to #466? #466  deals with the speakerphone causing the person not to hear the other person talking. This issue deals with an echo produced by the iPhone.

**Comment by LichKing-2234** [comment]
@louisschprs are two devices too near?

**Comment by louisschprs** [comment]
@LichKing-2234 Hi, I have separated the 2 devices into different rooms on the same network, I have also called someone who was 50 km away via the internet. In all my calls the Android user hears an echo produced by the iPhone user. The iPhone user however has no echo on their side. 

The echo that you hear is your own voice playing back to you. 
When two iPhone users call each other both hear an echo.

**Comment by LichKing-2234** [comment]
I will test it tomorrow.

**Comment by louisschprs** [comment]
Okay, thank you. I think it is the iPhones echo cancellation interfering with the Agora Echo Cancelation. But I have no Idea how to switch on and off one or the other.

**Comment by LichKing-2234** [comment]
Btw, which version of our SDK you used?

**Comment by louisschprs** [comment]
I'm using the Flutter package agora_rtc_engine version 4.0.7. I'm not sure what the native SDK version is that this package is using.

**Comment by louisschprs** [comment]
` agoraEngine.setAudioProfile(AudioProfile.SpeechStandard, AudioScenario.ChatRoomGaming);
    agoraEngine.enableAudioVolumeIndication(1, 1, true);`

This is my audio profile settings

**Comment by louisschprs** [comment]
Hi @LichKing-2234 any news from the testing?

**Comment by LichKing-2234** [comment]
It works for me, could you pls provide the sdk log file?

**Comment by louisschprs** [comment]
Sure, how would I find the file on xCode and on android?

**Comment by LichKing-2234** [comment]
Pls refer to the comment on `setLogfile` method.

**Comment by louisschprs** [comment]
Okay. would you require the logfile from the device that produces the echo or the one that hears the echo

**Comment by LichKing-2234** [comment]
@louisschprs Yes

**Comment by louisschprs** [comment]
Which one?

> Okay. would you require the logfile from the **device that produces the echo** or **the one that hears the echo**

**Comment by LichKing-2234** [comment]
Providing both of them is best.

**Comment by mirrorlink** [comment]
I Also have this issue, seems to be only on iOS 14 devices. On an old iPhone6 Device, for example, that does not happen. But out QA team found 100% of the time an iphone withy iOS14 without headplugs will cause echo.

**Comment by mirrorlink** [comment]
I use the

```

    AudioProfile audioProfile = AudioProfile.SpeechStandard;
    AudioScenario audioScenario = AudioScenario.Education;

    await currEngine!.setAudioProfile(audioProfile, audioScenario);
```

**Comment by mirrorlink** [comment]
![IMG_0963](https://user-images.githubusercontent.com/58230638/143257116-dae019f4-f71b-4636-9c87-e6114db0fc3b.PNG)
I was thinking that maybe it has to do with this new 'audio profile' feature that iOS has.

**Comment by louisschprs** [comment]
I tested the Agora example app, did not find an echo. Then Created a new app and ported only the calling functionality over to see if it is something else in my app potentially causing the issue. The isolated version did not produce an echo.

So there is something inside the app causing issues on iOS and to be honest I cannot find where the problem is.

**Comment by dganzella** [comment]
[agorasdk.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/7596592/agorasdk.log)

Here is the log of the iphone (a pain in the arse to get it, damn i hate ios) (ps. im mirrorlink, just different account)

**Comment by dganzella** [comment]
Im gonna try a few things:

1) not setting the audio profile
2) not using a custom capturer (we do it to render masks on the users faces)

and see if I get any result

**Comment by mirrorlink** [comment]
After some tests, it seems that this issue is related to use a custom native frame capturer, that implements AgoraVideoSourceProtocol and use a AgoraVideoFrameConsumer

**Comment by mirrorlink** [comment]
hey @LichKing-2234 do you know if agoraio flutter plugin support adding masks? I know it already supports virtual background, but having masks would be great so I woudlnt need to mess up with native code. I know there is a face detection, but it seems to be missing the face rotation and also an option to render an image over. Thanks!!

**Comment by mirrorlink** [comment]
@LichKing-2234 it seems now agora has a agora_rtc_rawdata plugin. Does this plugin work alongside with the "enableVirtualBackground" method? or, if I implement the agora_rtc_rawdata , the enableVirtualBackground will not work? thanks!

**Comment by mirrorlink** [comment]
So, just to close this issue, I think it ended up being a problem when in my code I had a custom AVSession created. It was a very very old code, but the new agora_rtc_rawdata should do the trick much better.

**Comment by louisschprs** [comment]
I have an update on my situation. It turns out that the problem was caused by an external package and not Agora itself. 
Before implementing Agora I implemented Flutter WebRTC, this proved time consuming and we decided to go with Agora. However, I never removed the package from the pubspec file. Once removed the echo disappeared.
