### ISSUE TITLE
[dev/flutter2][web] The AudioContext was not allowed to start 

### ISSUE THREAD

**Issue by dfdgsdfg** [AgoraIO/Agora-Flutter-SDK#496]
**Describe the bug**
Crash main.dart.js like below

> The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**To Reproduce**
```bash
flutter build web
cd web/build
npx http-server
open "http://localhost:8080"
```

**Expected behavior**
Just work

**Screenshots**
<img width="922" alt="스크린샷 2021-11-12 오후 11 33 06" src="https://user-images.githubusercontent.com/474775/141483535-4dcb3da4-d360-4e56-b662-0789bf7490d3.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: latest chrome/safari

**Additional context**
Only represent with `build` command. With `run` command, everything is just okay.

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by dfdgsdfg** [comment]
@LichKing-2234 Sorry. Only represent my project.

Thanks.

**Comment by tp** [comment]
@dfdgsdfg Did you find the underlying issue? We have the same error message in a project, but not sure about the severity yet.
