### ISSUE TITLE
Agora is working fine on android but not building my app in ios

### ISSUE THREAD

**Issue by chetan-pro** [AgoraIO/Agora-Flutter-SDK#497]
While I am trying to run my flutter app on an ios simulator or a real device it shows an error 

Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        27.6s
Xcode build done.                                           88.0s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching
    destinations:
    { platform:iOS Simulator,
    id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placehol
    der, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:73031A38-F4CC-4F87-BC49-06C5BDDAB5BA,
    OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:6B053CBD-5960-4178-A992-9250F6305527,
    OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:65CFC751-EF8C-4359-A9DF-456512B4D9A1,
    OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:CDC81819-04DD-4085-8C98-EBEBCF2C0E08,
    OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:474733A9-05B7-42F7-BFF3-767F10D2DD26,
    OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:62C1A6BA-3C45-4E61-B2A9-520FD2A9F119,
    OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:4D613B02-8656-4EE6-85AA-BCC16A902BBF,
    OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:6C423F15-94AC-4495-9384-316ABE30B1C4,
    OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:E7B40B2E-7114-44C1-9952-A4FBFEF660AE,
    OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:5D92B249-2E90-41B2-B2E5-E9C859EAB1E7,
    OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:1722DF2E-2C8D-4A94-AD21-12CDCB33C9E0,
    OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:1E431408-A288-47DD-81C0-2EC4F425326F,
    OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:4F157D8D-63B0-441F-B7E2-B5A1D05323BA,
    OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:C024E1FD-879A-400F-9C3B-974D16DDD927,
    OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:A689244D-9320-4695-B88C-EF597CB69A82,
    OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:5F7CA197-80E3-4CFE-9C2A-0F714C12DB27,
    OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:6BCF27F1-7F0C-4ABD-B6B1-02FAE81C2A22,
    OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:8E2529D5-1E0E-4D67-86D9-A7EEB914E897,
    OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:3F539FE7-C323-46DA-B605-68F93C06E2EB,
    OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:AC72B6E2-3CB5-425D-B544-483E79B0E412,
    OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:40683EFC-139D-4D6B-8422-DFC00533BCAD,
    OS:15.0, name:iPod touch (7th generation) }
    { platform:iOS,
    id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS
    Device }
    { platform:iOS, id:00008030-00150D6E2186802E, name:Manish’s iPhone }
    ** BUILD FAILED **

Xcode's output:
↳
    ld: building for iOS Simulator, but linking in dylib built for iOS,
    file '/Users/apple/Desktop/flutter/im
    connect/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.framework/
    AgoraAIDenoiseExtension' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
    ld: framework not found agora_rtc_engine
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
    ld: framework not found agora_rtc_engine
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
    error: the following command failed with exit code 1 but produced no
    further output
    Ld
    /Users/apple/Library/Developer/Xcode/DerivedData/Runner-czowfkceholpzf
    fvizoymeyzcwur/Build/Intermediates.noindex/Runner.build/Debug-iphonesi
    mulator/Runner.build/Objects-normal/arm64/Binary/Runner normal arm64
    (in target 'Runner' from project 'Runner')
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target 'nanopb' from
    project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target 'Toast' from
    project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'TOCropViewController' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'Reachability' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target 'OrderedSet'
    from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'MTBBarcodeScanner' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target 'BSImageView'
    from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'BSGridCollectionViewLayout' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target 'Alamofire'
    from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'MobileVLCKit' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'flutter_downloader-FlutterDownloaderDatabase' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'GoogleDataTransport' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'GoogleUtilities' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'FirebaseCoreDiagnostics' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'FirebaseCore' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'FirebaseInstallations' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'FirebaseDynamicLinks' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'FirebaseInstanceID' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'FirebaseMessaging' from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target 'Firebase'
    from project 'Pods')
    /Users/apple/Desktop/flutter/im connect/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target
    'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 15.0.99. (in target
    'AgoraRtcEngine_iOS' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 13.

****************this is my pod file
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'AgoraRtcEngine_iOS'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by LichKing-2234** [comment]
You can try this.
https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/issues/8#issuecomment-968656044

**Comment by adfdev** [comment]
> You can try this. [AgoraLibrary/flutter_agora_rtc_rawdata#8 (comment)](https://github.com/AgoraLibrary/flutter_agora_rtc_rawdata/issues/8#issuecomment-968656044)

Don't work with iOS simulator, only with physical and this fix not working. Any solution?

**Comment by MonsieurZbanowanYY** [comment]
Same issue for me...

**Comment by MonsieurZbanowanYY** [comment]
Okay, I fixed this:

1. add in the Podfile:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
     
```
2. delete podfile.lock
3. Flutter clean
4. pod install
I think it will help you.

**Comment by mfurkanyuceal** [comment]
> Okay, I fixed this:
> 
> 1. add in the Podfile:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
>      
> ```
> 
> 2. delete podfile.lock
> 3. Flutter clean
> 4. pod install
>    I think it will help you.

Thanks, it works :)

**Comment by zionnite** [comment]
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'

This worked for me but i will love to update it so anyone who have similar issue wont have to figure out what he or she need to do but simply copy paste the code into the podfile


```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
  end
end
```


what i did was to add the `end, end end` to the already existing code else it will generate another error


@MonsieurZbanowanYY , thanks for this, u save me, have been on this issue for more than 4 days now, your code acutally helped me

**Comment by MonsieurZbanowanYY** [comment]
> > post_install do |installer|
> > installer.pods_project.targets.each do |target|
> > flutter_additional_ios_build_settings(target)
> > target.build_configurations.each do |config|
> > config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
> > config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
> 
> This worked for me but i will love to update it so anyone who have similar issue wont have to figure out what he or she need to do but simply copy paste the code into the podfile
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
>     end
>   end
> end
> ```
> 
> what i did was to add the `end, end end` to the already existing code else it will generate another error
> 
> @MonsieurZbanowanYY , thanks for this, u save me, have been on this issue for more than 4 days now, your code acutally helped me

Yop, you're right, I could have add the end, end, end right away to be more "copy&paste" friendly 👍 . Next time, I will definitely don't forget about it! 😆

**Comment by kleberapsilva** [comment]
Same issue for me...
