### ISSUE TITLE
On iOS the feed from the front camera always initially freezes

### ISSUE THREAD

**Issue by matthewfx** [AgoraIO/Agora-Flutter-SDK#501]
**Describe the bug**
On iOS, the front camera initially freezes and I need to switch to the back one and again the front one to make it working. 
I don't experience it on Android.

**To Reproduce**
No steps are needed it happens every time.

**Expected behavior**
The feed from the front camera is not frozen.

**Desktop (please complete the following information):**
iOS 15

**Smartphone (please complete the following information):**
 iPhone 13 Pro Max, iPhone Xs Max

**Comment by LichKing-2234** [comment]
Is our example working?

**Comment by matthewfx** [comment]
It's fixed itself automagically... 🤷‍♂️
I'm sorry for bothering you
