### ISSUE TITLE
In Live Broadcasting for remoteLocalView show black screen. 

### ISSUE THREAD

**Issue by BhaveshTechnomads** [AgoraIO/Agora-Flutter-SDK#505]
Future<void> _initAgoraRtcEngine()async{
    _engine = await RtcEngine.create(APP_ID);
    await _engine.enableVideo();
    await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await _engine.setClientRole(widget.role!);
  }

  void _addAgoraEventHandlers() {
    _engine.setEventHandler(RtcEngineEventHandler(error: (code) {
      setState(() {
        final info = 'onError: $code';
        _infoStrings.add(info);
      });
    }, joinChannelSuccess: (channel, uid, elapsed) {
      print("Join Channel Success");
      setState(() {
        final info = 'onJoinChannel: $channel, uid: $uid';
        _infoStrings.add(info);
        localChannelJoinSuccess = true;
        print("LocalView Success");
      });
      if (widget.role == ClientRole.Broadcaster) {
        print("BroadCast Role");
        hostWidget = RtcLocalView.SurfaceView();
        setState(() {});
        //list.add(RtcLocalView.SurfaceView());
      }else{
        print("Local View");
        if(localChannelJoinSuccess){
          list.add(RtcLocalView.SurfaceView());
        }
        //  list.insert(0, RtcLocalView.SurfaceView());
        setState(() {});
      }
    },leaveChannel: (stats) {
      setState(() {
        _infoStrings.add('onLeaveChannel');
        _users.clear();
      });
    },userJoined: (uid, elapsed) async {
      await Future.delayed(Duration(milliseconds: 500));
      Map<int, String> users = {};
      final userInfo = await _engine.getUserInfoByUid(uid);
      users[uid] = userInfo.userAccount;
      if("New" == userInfo.userAccount){
        hostWidget = RtcRemoteView.SurfaceView(uid: uid);
      }else{
        _users.add(uid);
          _users.forEach((int uid) {
            list.add(RtcRemoteView.SurfaceView(uid: uid));
          });
        setState(() {});
      }
      setState((){
        final info = 'userJoined: $uid';
        _infoStrings.add(info);
      });
    }, userOffline: (uid, elapsed) {
      setState((){
        final info = 'userOffline: $uid';
        _infoStrings.add(info);
        _users.remove(uid);
      });
    }, firstRemoteVideoFrame: (uid, width, height, elapsed) {
      setState(() {
        final info = 'firstRemoteVideo: $uid ${width}x $height';
        _infoStrings.add(info);
      });
    },
    ));
  

> }

**Comment by LichKing-2234** [comment]
Have you tried our example?

**Comment by BhaveshTechnomads** [comment]
Join Channer Time just add.

**Comment by BhaveshTechnomads** [comment]
After Successful channel Joining.
=>  await _engine.enableLocalVideo(true);
