### ISSUE TITLE
pod install fails if switching to dev/flutter2-iris from dev/flutter2

### ISSUE THREAD

**Issue by reeteshranjan** [AgoraIO/Agora-Flutter-SDK#514]
**Describe the bug**
I am building my app against `dev/flutter2` using a local clone. I switched to `dev/flutter2-iris` and build started failing with errors related to pod configuration.

**To Reproduce**
Steps to reproduce the behavior are as follows. I am trying the following in my flutter app that builds properly with `dev/flutter2` branch.

```bash
$ cd ios/
$ rm -f Podfile.lock
$ rm -rf Pods/
$ pod install
Analyzing dependencies
firebase_core: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
[!] Unable to find a specification for `AgoraRtcWrapper` depended upon by `agora_rtc_engine`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I have tried the following and issue persists.
```bash
$ pod cache clean --all
$ pod repo update
Updating spec repo `trunk`
$ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
firebase_core: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
[!] Unable to find a specification for `AgoraRtcWrapper` depended upon by `agora_rtc_engine`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I switch back to the `dev/flutter2` branch and build starts working without any clean-ups required.

```bash
$ flutter pub get
$ cd ios/
$ pod install
Analyzing dependencies
firebase_core: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '8.9.0' defined in 'firebase_core'
Downloading dependencies
Installing AgoraRtcEngine_iOS (3.4.6)
```

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1

**Comment by reeteshranjan** [comment]
Relevant question: are we expected to switch to `dev/flutter2-iris` from `dev/flutter2`? I do not see `dev/flutter2` branch getting updates and all recent work is added to `dev/flutter2-iris`, hence clarifying.

**Comment by littleGnAl** [comment]
@reeteshranjan You should use `dev/flutter2` as it is the stable branch at this time, sorry for the confusion of the branch name, `dev/flutter2-iris` is our development branch to support more desktop features, and we do not guarantee the branch not break before our work is done.

**Comment by reeteshranjan** [comment]
Thank you so much for the clarification! Once this new branch is stable, do we need to switch to it, or would you merge things back to `dev/flutter2`?

**Comment by littleGnAl** [comment]
No, the code will be merged into `master` and release a new version of `agora_rtc_engine`, `dev/flutter2` will be deleted after it.

**Comment by reeteshranjan** [comment]
Thanks!
