### ISSUE TITLE
Is there anyway to record a video call and save it as a file ?

### ISSUE THREAD

**Issue by developmentkws** [AgoraIO/Agora-Flutter-SDK#516]
Please help me, 
I want to record video call and save it as a file.

What I tried yet,

I tried to use Camera plugin to record video, But its not working means ,
I am not able to record video and do video call at same time.

When I remove code for videocall, Video recording working. But when I try to videocall and Record video together , It throws :

E/flutter ( 6851): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference)
E/flutter ( 6851): #0      CameraController.startVideoRecording
package:camera/src/camera_controller.dart:508
E/flutter ( 6851): <asynchronous suspension>

**Comment by Hwan-seok** [comment]
Try use Agora Cloud Recording Service
https://docs.agora.io/en/cloud-recording/cloud_recording_api_rest?platform=RESTful
