### ISSUE TITLE
Library not loaded: @rpath/AgoraDav1dExtension.framework/AgoraDav1dExtension

### ISSUE THREAD

**Issue by Jokemac** [AgoraIO/Agora-Flutter-SDK#518]
Flutter use: agora_rtc_engine: ^4.0.7
iOS use: AgoraAudio_iOS '3.6.0'

dyld[2501]: Library not loaded: @rpath/AgoraDav1dExtension.framework/AgoraDav1dExtension
  Referenced from: /private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/agora_rtc_engine.framework/agora_rtc_engine
  Reason: tried: '/usr/lib/swift/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/agora_rtc_engine.framework/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/usr/lib/swift/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/usr/lib/swift/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/System/Library/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file)
Library not loaded: @rpath/AgoraDav1dExtension.framework/AgoraDav1dExtension
  Referenced from: /private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/agora_rtc_engine.framework/agora_rtc_engine
  Reason: tried: '/usr/lib/swift/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/agora_rtc_engine.framework/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/usr/lib/swift/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Application/5DFCF3BB-EFA6-48DA-AADE-29C6BF075A6E/lovenote.app/Frameworks/AgoraDav1dExtension.framework/AgoraDav1dExtension' (no such file), '/private/var/containers/Bundle/Applicatio

**Comment by LichKing-2234** [comment]
you should not use them together.

**Comment by Jokemac** [comment]
I have used AgoraAudio_iOS in my iOS project, what should I do if I need to use it in my Flutter project at the same project?

**Comment by LichKing-2234** [comment]
You should remove one of them from your project, and use the same one between two projects.
