### ISSUE TITLE
AgoraSurfaceView not working in iOS

### ISSUE THREAD

**Issue by savadmv** [AgoraIO/Agora-Flutter-SDK#519]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:71:9)
<asynchronous suspension>
#2      StateVideoCall.initAgora (package:***-****_****/screens/video_call.dart:30:5)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'AgoraSurfaceView', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:236:5)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:639:44)
<asynchronous suspension>

 - Device: [iPhoneSE]
 - Version 15.1

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by shenlanchenwei** [comment]
not working in iOS +1

**Comment by shenlanchenwei** [comment]
> 不适用于 iOS +1

Flutter SDK 2.5.1

**Comment by savadmv** [comment]
> is our example working?

NO

**Comment by littleGnAl** [comment]
Pls try `agora_rtc_engine: ^5.0.0`
