### ISSUE TITLE
[dev/flutter2] On web Agora causes images to become garbage

### ISSUE THREAD

**Issue by vlidholt** [AgoraIO/Agora-Flutter-SDK#521]
**Describe the bug**
Sometimes, especially after initiating screen share (but it also happens with just video calls too), Flutter images gets error graphics. Images get back to normal after resizing the window.

**To Reproduce**
Turn screen share on/off, do screen share, resize the window.

**Expected behavior**
Expecting no garbage images.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/1539812/145408417-160ca4c1-f80a-4b66-aaa9-4935791a4dd4.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by LichKing-2234** [comment]
Sorry, I don't understand, where are the garbage images?

**Comment by vlidholt** [comment]
The black squares should be pictures and icons, but when starting Agora they sometimes turn into error graphics.

**Comment by LichKing-2234** [comment]
Could you pls share the correct picture?

**Comment by vlidholt** [comment]
With agora running:
<img width="1499" alt="Screenshot 2021-12-17 at 09 52 57" src="https://user-images.githubusercontent.com/1539812/146516990-967796ed-96aa-4b36-bf46-4a6faba7677e.png">

Without agora running:
<img width="1378" alt="Screenshot 2021-12-17 at 09 53 14" src="https://user-images.githubusercontent.com/1539812/146517044-925f48ec-859a-4ca3-b98f-b72a7ca6ac42.png">

**Comment by LichKing-2234** [comment]
have you tried html render mode?

**Comment by tp** [comment]
> have you tried html render mode?

Using the HTML renderer on desktop is a workaround that worked for our scenario (and we haven't seen any other regression in the app with that, just overall doesn't seem ideal to diverge from the stock behavior).

But as the investigation in the Flutter ticket linked above shows, this is by now affecting many different apps and use-cases, many of which unrelated to video. So I think you can close this for now and we have to wait for a fix from Flutter and/or Chrome.
