### ISSUE TITLE
[Android] Sometimes when coming back from background, the videos will get stuck flipping between 2 frames

### ISSUE THREAD

**Issue by mirrorlink** [AgoraIO/Agora-Flutter-SDK#527]
Sometimes when coming back from background, the videos will get stuck flicking between 2 frames

**To Reproduce**
Enter a session with an android device and a web device.
With android, send the app to background and foreground multiple times.

Device: Android S20 android 11
Web: Chrome, windows 10

**Expected behavior**
All remote videos and local video should work perfectly. But what happens is that both the local video and the remote video from web is stuck flicking between 2 frames.

**Screenshots**

https://user-images.githubusercontent.com/58230638/145845748-93b6087c-2402-4d19-b09f-fd778e2b6f47.mp4

https://user-images.githubusercontent.com/58230638/145846502-71aa169b-a7bb-4e84-9e77-14d633550e0e.mp4

**Additional Context**

- This bug can be achieved by receiving a call too. But it will also only happen sometimes.
- This bug can be achieved by opening the camera app and taking a photo too
- This bug can be achieved by opening instagram and posting a story too
- Rotating the device as to rebuild the UI, seem to make the videos go normal again.

**Comment by mirrorlink** [comment]
This can be fixed by updating to flutter 2.8 and by implementing foreground services

**Comment by Hwan-seok** [comment]
Hi @mirrorlink, 

I am experiencing the same issue as you. 
Could you explain a little bit more how to fix this?
Thank you!

**Comment by mirrorlink** [comment]
hey @Hwan-seok how are stuff going in korea?

Sure, just use

```
    if (Platform.isAndroid) {
      FlutterBackground.enableBackgroundExecution();
    }
```
```
  flutter_background: 
    git:
      url: https://github.com/mirrorlink/flutter_background.git
      ref: master
```

**Comment by Hwan-seok** [comment]
Thanks for asking We are great but kinda going bad :(

When do you trigger the enable method? 
Did you do that on applifecycle methods like `onInactive`? or always actiavte before live streaming?

**Comment by mirrorlink** [comment]
> Thanks for asking We are great but kinda going bad :(
> 
> When do you trigger the enable method? Did you do that on applifecycle methods like `onInactive`? or always actiavte before live streaming?

I usually call FlutterBackground.enableBackgroundExecution(); at the initState of the page in my app which handles the agoraioCall, and the disableBackgroundExecution on the dispose.

I understand your confusion. I dont think these methods are meant to be called on the applifecycle methods. its not like "when im going to background ,make sure to continue execution", its more like "on this page, if I ever go to background, please continue execution same as if it was in foreground".

**Comment by Hwan-seok** [comment]
> > Thanks for asking We are great but kinda going bad :(
> > When do you trigger the enable method? Did you do that on applifecycle methods like `onInactive`? or always actiavte before live streaming?
> 
> I usually call FlutterBackground.enableBackgroundExecution(); at the initState of the page in my app which handles the agoraioCall, and the disableBackgroundExecution on the dispose.
> 
> I understand your confusion. I dont think these methods are meant to be called on the applifecycle methods. its not like "when im going to background ,make sure to continue execution", its more like "on this page, if I ever go to background, please continue execution same as if it was in foreground".

Thank you very much for the help! I clearly understand about that
I appreciate you.

**Comment by AhmedKhalidOkab** [comment]
i need set name in the all member enter to the meeting how i can do it ?
