### ISSUE TITLE
[dev/flutter2] Video calling showing blank screen on web

### ISSUE THREAD

**Issue by shreyansh2211** [AgoraIO/Agora-Flutter-SDK#531]
I have implemented agora flutter SDK for android, iOS and web. Everything is working fine. But when we are enabling video on web site, there is just black screen although i can see other user who are on android and ios at web end. 

`  await _engine.enableVideo();`
` await _engine.enableLocalVideo(true);`

Is video supported on web, if yes what's different than mobile device that we need to implement.  I have given camera and microphone permission and webcam is opening.

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by LichKing-2234** [comment]
BTW, do you using the web on mobile?

**Comment by littleGnAl** [comment]
Hello @shreyansh2211 
Pls try `master` branch to see the issue still exists or not

**Comment by Ben-chedli** [comment]
@LichKing-2234 i am now facing the same issue when i run a deployed version of our web app on a mobile browser, we're using agora_rtc_engine: 5.1.1 and just copy/pasted the code from this example https://pub.dev/packages/agora_rtc_engine/example 
works fine on desktop browser but not on device browser after deploying !

![im_2](https://user-images.githubusercontent.com/64413708/171611896-ac54044f-b4b5-4adc-9757-f954119286d0.JPG)


![im_1](https://user-images.githubusercontent.com/64413708/171611913-e0bee2c0-acb9-4eca-8688-4af4582f60ba.jpg)
