### ISSUE TITLE
is it updated flutter 2.8.0 ?

### ISSUE THREAD

**Issue by sahmirzali** [AgoraIO/Agora-Flutter-SDK#532]

**Comment by LichKing-2234** [comment]
Any update on flutter 2.8.0?

**Comment by sahmirzali** [comment]
Yes, major update on Camera

**Comment by LichKing-2234** [comment]
Our SDK use native API to access the camera, I think It is not affected.

**Comment by sahmirzali** [comment]
Okay. But did you look up 2.8 updates?

**Comment by mirrorlink** [comment]
> Okay. But did you look up 2.8 updates?

Im using 2.8, and 4.0.7 seems to work just fine
