### ISSUE TITLE
userJoined is never called

### ISSUE THREAD

**Issue by hadi-norouzi** [AgoraIO/Agora-Flutter-SDK#533]
I build an app and have my own token server it generate token for me and push it to other user through push notification.

when i request a call and join to a channel it's fine, i can see my video but when other user join the same channel ```userJoined``` callback is never called to set remoteUid for remote SurfaceView.

**Comment by LichKing-2234** [comment]
maybe you use the same uid?

**Comment by CodingAleCR** [comment]
@hadi-norouzi you should be using the hook `remoteVideoStateChanged` to set the remote uid for the surface I think.
