### ISSUE TITLE
remoteVideoStats and localVideoStats callbacks not called on Flutter Web

### ISSUE THREAD

**Issue by ratherNotB** [AgoraIO/Agora-Flutter-SDK#547]
remoteVideoStats and localVideoStats callbacks are never called on Flutter Web.

If these callbacks are not supported for Flutter Web, can you please advise as to how I can obtain the dimensions (width and height) of remote video streams?

Thank you

**Comment by LichKing-2234** [comment]
not support this event on web now.

**Comment by ThangD** [comment]
@LichKing-2234 @littleGnAl Do we have any event to know remote video stats on Web? Thank so much.

**Comment by plutoless** [comment]
@ThangD with web sdk you can get remote video stats via this api
https://docs.agora.io/en/Video/API%20Reference/web_ng/interfaces/remotevideotrackstats.html
maybe you can quickly check if this api is already supported in flutter web.
