### ISSUE TITLE
ClientRole.Audience doesn't working Please check

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#549]
I try to join my channel as an audience but it's not working it joined as a broadcaster

My code is 
```

import 'dart:async';

import 'package:agora_rtc_engine/rtc_engine.dart';
import 'package:agora_rtc_engine/rtc_local_view.dart' as RtcLocalView;
import 'package:agora_rtc_engine/rtc_remote_view.dart' as RtcRemoteView;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:user/settings/agora.dart';
import 'package:user/theme/colors.dart';

import '../utils/setting.dart';

class UserLiveStreaming extends StatefulWidget {
  /// non-modifiable channel name of the page
  final String channel;
  final String eventId;

  /// non-modifiable client role of the page
  final ClientRole role;
  final String token;
  final String name;

  /// Creates a call page with given channel name.
  const UserLiveStreaming(
      {Key key, this.channel, this.role, this.token, this.eventId, this.name})
      : super(key: key);

  @override
  _UserLiveStreamingState createState() => _UserLiveStreamingState();
}

class _UserLiveStreamingState extends State<UserLiveStreaming> {
  final _users = <int>[];
  final _infoStrings = <String>[];
  bool muted = false;
  RtcEngine _engine;
  TextEditingController msg = TextEditingController();
  int _remoteUid;

  @override
  void dispose() {
    // clear users
    _users.clear();
    // destroy sdk
    _engine.leaveChannel();
    _engine.destroy();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    // initialize agora sdk
    initAgora();
  }

  Future<void> initAgora() async {
    // retrieve permissions
    print('after engine');
    //create the engine
    _engine = await RtcEngine.create(appId);
    VideoEncoderConfiguration configuration = VideoEncoderConfiguration();
    configuration.dimensions = VideoDimensions(width: 1920, height: 1080);
    await _engine.setVideoEncoderConfiguration(configuration);
    _engine.setClientRole(ClientRole.Audience);
    print('form engine');
    _engine.setEventHandler(
      RtcEngineEventHandler(
        joinChannelSuccess: (String channel, int uid, int elapsed) {
          print("local user $uid joined");
        },
        userJoined: (int uid, int elapsed) {
          print("remote user $uid joined");
          setState(() {
            _remoteUid = uid;
          });
        },
      ),
    );

    await _engine.joinChannel(widget.token, widget.channel, null, 0);
  }

  Widget _remoteVideo() {
    if (_remoteUid != null) {
      return RtcRemoteView.SurfaceView(uid: _remoteUid);
    } else {
      return Center(
        child: Text(
          'Calling...',
          textAlign: TextAlign.center,
        ),
      );
    }
  }

  void _onCallEnd(BuildContext context) {
    _engine.leaveChannel();
    Navigator.pop(context);
  }

  void _onToggleMute() {
    setState(() {
      muted = !muted;
    });
    _engine.muteLocalAudioStream(muted);
  }

  void _onSwitchCamera() {
    _engine.switchCamera();
  }

  @override
  Widget build(BuildContext context) {
    print('hello from user event');
    CollectionReference chats = FirebaseFirestore.instance.collection('chat');
    return Scaffold(
      body: Center(
        child: Stack(
          children: <Widget>[
            _remoteVideo(),
            // Positioned(
            //   top: 40,
            //   left: 20,
            //   child: GestureDetector(
            //     onTap: () => _onCallEnd(context),
            //     child: Padding(
            //       padding: const EdgeInsets.all(8.0),
            //       child: Icon(Icons.close),
            //     ),
            //   ),
            // ),
            Positioned(
                bottom: 20,
                child: Container(
                  margin: EdgeInsets.only(left: 20, right: 20),
                  color: Colors.white,
                  // height: 50,
                  width: MediaQuery.of(context).size.width - 40,
                  child: Row(
                    children: [
                      Expanded(
                          child: TextField(
                              // expands: true,
                              controller: msg,
                              maxLines: 8,
                              minLines: 1,
                              decoration: InputDecoration(
                                border: OutlineInputBorder(),
                                hintText: 'Enter text message',
                              ))),
                      Container(
                        width: 50,
                        child: IconButton(
                            icon: Icon(Icons.send),
                            onPressed: () {
                              chats.add({
                                'event_id': widget.eventId,
                                'message': msg.text,
                                'time': DateTime.now(),
                                'name': widget.name,
                              });
                              Get.snackbar(
                                'Message',
                                'Message sent',
                                colorText: Colors.white,
                                snackPosition: SnackPosition.BOTTOM,
                                backgroundColor: primary,
                                margin: EdgeInsets.all(10),
                                duration: Duration(seconds: 2),
                              );
                              msg.clear();
                            }),
                      ),
                    ],
                  ),
                )),
          ],
        ),
      ),
    );
  }
}

```

**Comment by LichKing-2234** [comment]
You should setChannelProfile to LiveBroadcasting first.

**Comment by ziasultan2** [comment]
Thanks for the answer I need one more help. How can I show the broadcasting event to the audience

**Comment by ziasultan2** [comment]
> 

I did this and it works fine in Broadcasting and can listen sound in audience but I can't see the broadcaster video in audience part. Please give me a suggestion

Here is my code

```
import 'dart:async';

import 'package:agora_rtc_engine/rtc_engine.dart';
import 'package:agora_rtc_engine/rtc_local_view.dart' as RtcLocalView;
import 'package:agora_rtc_engine/rtc_remote_view.dart' as RtcRemoteView;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:user/settings/agora.dart';
import 'package:user/theme/colors.dart';

import '../utils/setting.dart';

class UserLiveStreaming extends StatefulWidget {
  /// non-modifiable channel name of the page
  final String channel;
  final String eventId;

  /// non-modifiable client role of the page
  final ClientRole role;
  final String token;
  final String name;

  /// Creates a call page with given channel name.
  const UserLiveStreaming(
      {Key key, this.channel, this.role, this.token, this.eventId, this.name})
      : super(key: key);

  @override
  _UserLiveStreamingState createState() => _UserLiveStreamingState();
}

class _UserLiveStreamingState extends State<UserLiveStreaming> {
  final _users = <int>[];
  final _infoStrings = <String>[];
  bool muted = false;
  RtcEngine _engine;
  TextEditingController msg = TextEditingController();
  int _remoteUid;

  @override
  void dispose() {
    // clear users
    _users.clear();
    // destroy sdk
    _engine.leaveChannel();
    _engine.destroy();
    super.dispose();
  }

  clear() {
    _users.clear();
    // destroy sdk
    _engine.leaveChannel();
    _engine.destroy();
  }

  @override
  void initState() {
    super.initState();
    // initialize agora sdk
    initAgora();
  }

  Future<void> initAgora() async {
    // retrieve permissions
    print('after engine');
    //create the engine

    _engine = await RtcEngine.create(appId);
    await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await _engine.setClientRole(ClientRole.Audience);
    print('form engine');
    _engine.setEventHandler(
      RtcEngineEventHandler(
        joinChannelSuccess: (String channel, int uid, int elapsed) {
          print("local user $uid joined");
        },
        userJoined: (int uid, int elapsed) {
          print("remote user $uid joined");
          setState(() {
            _remoteUid = uid;
          });
        },
        userOffline: (int uid, UserOfflineReason) {
          clear();
          Get.back();
        },
      ),
    );

    await _engine.joinChannel(widget.token, widget.channel, null, 0);
  }

  Widget _remoteVideo() {
    if (_remoteUid != null) {
      return RtcRemoteView.SurfaceView(
        uid: _remoteUid,
        renderMode: VideoRenderMode.Fit,
      );
    } else {
      return Center(
        child: Text(
          'Calling...',
          textAlign: TextAlign.center,
        ),
      );
    }
  }

  void _onCallEnd(BuildContext context) {
    _engine.leaveChannel();
    Navigator.pop(context);
  }

  void _onToggleMute() {
    setState(() {
      muted = !muted;
    });
    _engine.muteLocalAudioStream(muted);
  }

  void _onSwitchCamera() {
    _engine.switchCamera();
  }

  @override
  Widget build(BuildContext context) {
    CollectionReference chats = FirebaseFirestore.instance.collection('chat');
    return Scaffold(
      body: Stack(
        children: <Widget>[
          Center(
            child: _remoteVideo(),
          ),
          Align(
              alignment: Alignment.bottomCenter,
              child: Container(
                margin: EdgeInsets.only(left: 20, right: 20),
                color: Colors.white,
                // height: 70,
                width: MediaQuery.of(context).size.width - 40,
                child: Row(
                  children: [
                    Expanded(
                        child: TextField(
                            // expands: true,
                            controller: msg,
                            maxLines: 8,
                            minLines: 1,
                            decoration: InputDecoration(
                              border: OutlineInputBorder(),
                              hintText: 'Enter text message',
                            ))),
                    Container(
                      width: 50,
                      child: IconButton(
                          icon: Icon(Icons.send),
                          onPressed: () {
                            chats.add({
                              'event_id': widget.eventId,
                              'message': msg.text,
                              'time': DateTime.now(),
                              'name': widget.name,
                            });
                            Get.snackbar(
                              'Message',
                              'Message sent',
                              colorText: Colors.white,
                              snackPosition: SnackPosition.BOTTOM,
                              backgroundColor: primary,
                              margin: EdgeInsets.all(10),
                              duration: Duration(seconds: 2),
                            );
                            msg.clear();
                          }),
                    ),
                  ],
                ),
              )),
        ],
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print('remote uid $_remoteUid');
          Get.defaultDialog(
            title: "WARNING!!!",
            content: Text("Are you sure you want to quit?"),
            onConfirm: () {
              clear();
              Get.back();
            },
            onCancel: () => Get.back(),
          );
        },
        child: Icon(Icons.close),
      ),
    );
  }
}


```

**Comment by Junama** [comment]
I have the same issue. I cant see the ClientRole.Audience

**Comment by Junama** [comment]
class CallVideoPage extends StatefulWidget {
  final IndigoUser indigoUser;
  final String channel;
  final ClientRole role;
  final AssetImage imageIcon;
  CallVideoPage(
      {Key key, this.indigoUser, this.channel, this.role, this.imageIcon})
      : super(key: key);

  @override
  _CallVideoPage createState() => _CallVideoPage();
}

class _CallVideoPage extends State<CallVideoPage>
    with TickerProviderStateMixin {
  var appId = "95718ad2372c4d9f8ea894341d0feb46";
  //vence en 24 hs. ver con back para generar Token.
  var token =
      "00695718ad2372c4d9f8ea894341d0feb46IADvFXR3wjscm+byuYPb6OWLn6Jk87TJehodeIhpBrphH0D6g3QAAAAAEADC8VeA7sXmYQEAAQDuxeZh";

  final _users = <int>[];
  final _infoStrings = <String>[];
  bool muted = false;
  RtcEngine _engine;
  int _uid;

  @override
  void dispose() {
    _users.clear();
    _engine.leaveChannel();
    _engine.destroy();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    initialize();
  }

  Future<void> initialize() async {
    if (appId.isEmpty) {
      setState(() {
        _infoStrings.add(
          'APP_ID missing, please provide your APP_ID in settings.dart',
        );
        _infoStrings.add('Agora Engine is not starting');
      });
      return;
    }

    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    var configuration = VideoEncoderConfiguration();
    configuration.dimensions = VideoDimensions(width: 1920, height: 1080);
    await _engine.setVideoEncoderConfiguration(configuration);
    await _engine.joinChannel(token, widget.channel, null, 0);
  }

  /// Create agora sdk instance and initialize
  Future<void> _initAgoraRtcEngine() async {
    _engine = await RtcEngine.create(appId);
    await _engine.enableVideo();
    await _engine.enableAudio();
    await _engine.startPreview();
    await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await _engine.setClientRole(widget.role);
  }

  /// Add agora event handlers
  void _addAgoraEventHandlers() async {
    _engine.setEventHandler(RtcEngineEventHandler(error: (code) {
      setState(() {
        final info = 'onError: $code';
        _infoStrings.add(info);
      });
    }, joinChannelSuccess: (channel, uid, elapsed) {
      setState(() {
        final info = 'onJoinChannel: $channel, uid: $uid';
        _infoStrings.add(info);
        _uid = uid;
      });
    }, leaveChannel: (stats) {
      setState(() {
        _infoStrings.add('onLeaveChannel');
        _users.clear();
      });
    }, userJoined: (uid, elapsed) {
      setState(() {
        final info = 'userJoined: $uid';
        _infoStrings.add(info);
        _users.add(uid);
      });
    }, userOffline: (uid, elapsed) {
      setState(() {
        final info = 'userOffline: $uid';
        _infoStrings.add(info);
        _users.remove(uid);
      });
    }, firstRemoteVideoFrame: (uid, width, height, elapsed) {
      setState(() {
        final info = 'firstRemoteVideo: $uid ${width}x $height';
        _infoStrings.add(info);
      });
    }));
  }

  /// Helper function to get list of native views
  List<Widget> _getRenderViews() {
    final list = <StatefulWidget>[];
    if (widget.role == ClientRole.Broadcaster) {
      list.add(RtcLocalView.SurfaceView());
    }
    _users.forEach((int uid) => list
        .add(RtcRemoteView.SurfaceView(channelId: widget.channel, uid: uid)));

    return list;
  }

  /// Video view
  Widget _videoView(view) {
    return Expanded(child: Container(child: view));
  }

  /// Video view row
  Widget _expandedVideoRow(List<Widget> views) {
    final wrappedViews = views.map<Widget>(_videoView).toList();
    return Expanded(
      child: Row(
        children: wrappedViews,
      ),
    );
  }

  /// Video layout
  Widget _viewRows() {
    final views = _getRenderViews();
    switch (views.length) {
      //detalla cuantos participantes tiene.
      case 1: 
        return Container(
            child: Column(
          children: <Widget>[_videoView(views[0])],
        ));
      case 2:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow([views[0]]),
            _expandedVideoRow([views[1]])
          ],
        ));
      case 3:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow(views.sublist(0, 2)),
            _expandedVideoRow(views.sublist(2, 3))
          ],
        ));
      case 4:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow(views.sublist(0, 2)),
            _expandedVideoRow(views.sublist(2, 4))
          ],
        ));
      default:
    }
    return Container();
  }

  Widget _toolbar() {
    if (widget.role == ClientRole.Audience) {
      return Container();
    }
    return Container(
      alignment: Alignment.bottomCenter,
      padding: const EdgeInsets.symmetric(vertical: 48),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          RawMaterialButton(
            onPressed: _onToggleMute,
            child: Icon(
              muted ? Icons.mic_off : Icons.mic,
              color: muted ? Colors.white : Colors.blueAccent,
              size: 20.0,
            ),
            shape: CircleBorder(),
            elevation: 2.0,
            fillColor: muted ? Colors.blueAccent : Colors.white,
            padding: const EdgeInsets.all(12.0),
          ),
          RawMaterialButton(
            onPressed: () async => _onCallEnd(context),
            child: Icon(
              Icons.call_end,
              color: Colors.white,
              size: 35.0,
            ),
            shape: CircleBorder(),
            elevation: 2.0,
            fillColor: Colors.redAccent,
            padding: const EdgeInsets.all(15.0),
          ),
          RawMaterialButton(
            onPressed: _onSwitchCamera,
            child: Icon(
              Icons.switch_camera,
              color: Colors.blueAccent,
              size: 20.0,
            ),
            shape: CircleBorder(),
            elevation: 2.0,
            fillColor: Colors.white,
            padding: const EdgeInsets.all(12.0),
          )
        ],
      ),
    );
  }

  /// Info panel to show logs
  Widget _panel() {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 48),
      alignment: Alignment.bottomCenter,
      child: FractionallySizedBox(
        heightFactor: 0.5,
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 48),
          child: ListView.builder(
            reverse: true,
            itemCount: _infoStrings.length,
            itemBuilder: (BuildContext context, int index) {
              if (_infoStrings.isEmpty) {
                return Container(); // return type can't be null, a widget was required
              }
              return Padding(
                padding: const EdgeInsets.symmetric(
                  vertical: 3,
                  horizontal: 10,
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Flexible(
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          vertical: 2,
                          horizontal: 5,
                        ),
                        decoration: BoxDecoration(
                          color: Colors.yellowAccent,
                          borderRadius: BorderRadius.circular(5),
                        ),
                        child: Text(
                          _infoStrings[index],
                          style: TextStyle(color: Colors.blueGrey),
                        ),
                      ),
                    )
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }

  void _onCallEnd(BuildContext context) {
    Navigator.pop(context);
  }

  void _onToggleMute() {
    setState(() {
      muted = !muted;
    });
    _engine.muteLocalAudioStream(muted);
  }

  void _onSwitchCamera() {
    _engine.switchCamera();
  }

  @override
  Widget build(BuildContext context) {
    return _uid == null
        ? Center(child: CircularProgressIndicator(backgroundColor: Colors.white))
        : Scaffold(
            appBar: AppBar(
              title: Text("Instituto Cardiovascular Lezica",
                  style: TextStyle(fontSize: 18.5)),
              leadingWidth: 25.0,
              actions: [
                Padding(
                  padding: const EdgeInsets.only(right: 6.0),
                  child: CircleAvatar(
                    child: ClipOval(
                      child: Image(
                        image: widget.imageIcon,
                      ),
                    ),
                    backgroundColor: Colors.white,
                  ),
                )
              ],
            ),
            backgroundColor: Colors.black,
            body: Center(
              child: Stack(
                children: <Widget>[
                  _viewRows(),
                  _panel(),
                  _toolbar(),
                ],
              ),
            ),
          );
  }
}
