### ISSUE TITLE
Wrong info in readme

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/Agora-Flutter-SDK#550]
**Describe the bug**

> The API-Example-ReactNative project is an open-source demo that will show you different scenes on how to integrate Agora SDK APIs into your project.

Should be

> This project is an open-source demo that will show you different scenes on how to integrate Agora SDK APIs into your project.

**Comment by LichKing-2234** [comment]
可以直接提PR么

**Comment by yamasite** [comment]
https://github.com/AgoraIO/Agora-Flutter-SDK/pull/552
