### ISSUE TITLE
Issue with agora_rtc_engine 4.2.0

### ISSUE THREAD

**Issue by adityaagarwal-coder** [AgoraIO/Agora-Flutter-SDK#561]
**Describe the bug**
a problem occurred configuring project ':agora_rtc_engine'. > could not load compiled classes for build file 'e:\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-4.2.0\android\build.gradle' from cache.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![Screenshot (383)](https://user-images.githubusercontent.com/82513880/149293069-086b9413-c788-469e-b835-1ec97ba3258d.png)

**Additional context**

**Comment by littleGnAl** [comment]
Can you print the `flutter doctor`?
