### ISSUE TITLE
Problem to update agora sdk to last update (flutter)

### ISSUE THREAD

**Issue by zitob9** [AgoraIO/Agora-Flutter-SDK#563]
Running "flutter pub get" in final...
The current Dart SDK version is 2.13.4.

Because agora_rtc_engine >=4.2.0-rc.0 depends on json_annotation >=4.2.0 which requires SDK version >=2.14.0 <3.0.0, agora_rtc_engine >=4.2.0-rc.0 is forbidden.
So, because doctor_consultation depends on agora_rtc_engine ^4.2.0, version solving failed.
pub get failed (1; So, because doctor_consultation depends on agora_rtc_engine ^4.2.0, version solving failed.)

**Comment by littleGnAl** [comment]
`agora_rtc_engine: ^4.2.0` require Flutter SDK 2.5.3

**Comment by zitob9** [comment]
@

> `agora_rtc_engine: ^4.2.0` require Flutter SDK 2.5.3

thank you for your help, please can you tell me what is the last version of agora works with flutter 2.2.3

**Comment by zitob9** [comment]
> 

thank you for your help, please can you tell me what is the last version of agora works with flutter 2.2.3

**Comment by zitob9** [comment]
@littleGnAl 
thank you for your help, please can you tell me what is the last version of agora works with flutter 2.2.3

**Comment by littleGnAl** [comment]
@zitob9 Pls try `4.0.7`
