### ISSUE TITLE
Agora not working in production mode on Android

### ISSUE THREAD

**Issue by Rizardomon** [AgoraIO/Agora-Flutter-SDK#567]
I am testing to use the Agora package (https://pub.dev/packages/agora_rtc_engine) platform with the Callkeep package (https://pub.dev/packages/callkeep) ,to play a phone call.
I have created the function that generates the temporary token using node and hosting it in the Firebase cloud functions, I have tested it in development environment and the token is being generated, and I am getting the expected results in this environment.
After I build the APK, install it again and try to use the connection by APK, it does not show the same behavior and does not enter the now channel.

The token from the API:
![image](https://user-images.githubusercontent.com/57680110/149958558-cfc2d528-8fd7-431e-98b8-409a6b378042.png)

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by joumanam** [comment]
were you able to fix this issue?
