### ISSUE TITLE
Please help me: No implementation found for method create on channel agora_rtc_engine

### ISSUE THREAD

**Issue by DiamondTran** [AgoraIO/Agora-Flutter-SDK#572]
**No implementation found for method create on channel agora_rtc_engine**
I using the latest version

Devices:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1415]

Error:
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
<asynchronous suspension>
#1      RtcEngine.createWithContext
package:agora_rtc_engine/src/rtc_engine.dart:161
<asynchronous suspension>
#2      DesktopAppController.initPlatformState
package:live_window/…/controller/desktop_home_controller.dart:19
<asynchronous suspension>

**Comment by LichKing-2234** [comment]
for windows? pls use the `dev/flutter2-iris` branch.

**Comment by TrieuCan** [comment]
> for windows? pls use the `dev/flutter2-iris` branch.


I can't pubget dev/flutter2

**Comment by DiamondTran** [comment]
@LichKing-2234 thanks u <3. i'm will try
