### ISSUE TITLE
App crashing in debug mode

### ISSUE THREAD

**Issue by MasoomRaza752** [AgoraIO/Agora-Flutter-SDK#574]
I use agora rtc enging version 4.2.0 in my app for video calling but when i import dependency it show me the error
 "E/FlutterLoader(13632): Flutter initialization failed.
E/FlutterLoader(13632): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.video_call_test-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.video_call_test-2/lib/arm, /data/app/com.example.video_call_test-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
this is my flutter doctor information

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

• No issues found!

**Comment by LichKing-2234** [comment]
`couldn't find "libflutter.so"`

pls check your build.gradle

**Comment by MasoomRaza752** [comment]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.kmz.TheCounsler"
        minSdkVersion 21
        targetSdkVersion 30
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.android.gms:play-services-safetynet:18.0.1'
    implementation 'com.google.firebase:firebase-appcheck-safetynet:16.0.0-beta04'
    implementation 'androidx.browser:browser:1.3.0'
}

**Comment by MasoomRaza752** [comment]
this is my build.gradle file code

**Comment by MasoomRaza752** [comment]
when i comment this dependency than app will running fine but adding this dependency create the issue and app crashing

**Comment by LichKing-2234** [comment]
seem like a bug from flutter.
https://github.com/flutter/flutter/issues/57237

**Comment by MasoomRaza752** [comment]
how can i get libflutter.so file

**Comment by MasoomRaza752** [comment]
minSdkVersion 25
targetSdkVersion 29
compileSdkVersion 31

please chek these value are right or wrong beacuse when i give minSdk to 31 my emulator shows minSdk is 25 and did not show any other error please guide about this

**Comment by MasoomRaza752** [comment]
i use agora 3.1.3 its working fine but 4.2.0 is not working and giving errror flutter not initialize and libflutter.so file not found
please help

**Comment by littleGnAl** [comment]
Please try `agora_rtc_engine: 5.1.0`.
