### ISSUE TITLE
Please help me: rtc_render_view is NOT SUPPORT TargetPlatform.windows

### ISSUE THREAD

**Issue by duchieupham** [AgoraIO/Agora-Flutter-SDK#575]
**TargetPlatform.windows is not yet supported by the plugin**

I'm using dev/flutter2-iris branch for building desktop windows app. It was failed when joinChannel() as host, then calling rtc_local_view.SurfaceView extends  RtcSurfaceView. 

At class RtcSurfaceView , I found the logic code in build() Widget having no support windows. 

Next, onWarning warns 'code 8 msg' and 'code 16 msg'. code 104 msg for timeout is warned after.
Please help me the solution for these. 

ERROR:
...\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\internal\rtc_engine_event_handler.cc:40 agora::iris::rtc::RtcEngineEventHandler::onWarning warn 8 msg nullptr
...\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\internal\rtc_engine_event_handler.cc:40 agora::iris::rtc::RtcEngineEventHandler::onWarning warn 16 msg nullptr
...\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\internal\rtc_engine_event_handler.cc:40 agora::iris::rtc::RtcEngineEventHandler::onWarning warn 104 msg nullptr

**Comment by LichKing-2234** [comment]
Pls refer to our example, `SurfaceView` does not support desktop.
