### ISSUE TITLE
set Beauty Effect Options not working

### ISSUE THREAD

**Issue by Hawaii88** [AgoraIO/Agora-Flutter-SDK#587]
**Set up Beauty Effect Options not working**

I use agora_rtc_engine: ^4.0.7 to set with flutter. already adjust following the document but still not working.

To Reproduce
_engine.setBeautyEffectOptions(
    true,
    BeautyOptions(
         lighteningContrastLevel: LighteningContrastLevel
         lighteningLevel: value / 10,
         rednessLevel: value / 10,
         smoothnessLevel: value / 10,
      ),

**Expected behavior**
It's suppost to working on frontend.

**Screenshots**
So i attacted video screenshot to show how I adjust.
[666045070.413774.mp4.zip](https://github.com/AgoraIO/Agora-Flutter-SDK/files/8030104/666045070.413774.mp4.zip)

Smartphone:
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS15.2.1]

**Comment by LichKing-2234** [comment]
Pls try the latest version, it has been fixed.
