### ISSUE TITLE
If rtc_remote_view.SurfaceView for particular user is not present then also we hear his voice

### ISSUE THREAD

**Issue by GJJ2019AppSynergies** [AgoraIO/Agora-Flutter-SDK#588]
Im not sure if its a bug or some confusion but according to this bug its should not happen right https://github.com/AgoraIO-Community/react-native-agora/issues/350

**Comment by plutoless** [comment]
could you pls make the question a little more clear? you expect to hear the user's voice or not?

**Comment by GJJ2019AppSynergies** [comment]
if rtc_remote_view.SurfaceView for particular uid is not present on screen then we should not hear other user voice right ?
or there is any work-around for that ?

**Comment by GJJ2019AppSynergies** [comment]
Okay I research some docs i can use muteAllRemoteAudioStreams & muteRemoteAudioStream for control over audio
Thank you for quick response @plutoless
