### ISSUE TITLE
Unresolved reference: toUInt in version 4.2.1 

### ISSUE THREAD

**Issue by sadaqatkarimi** [AgoraIO/Agora-Flutter-SDK#591]
/Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/Extensions.kt: (9, 18): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/Extensions.kt: (62, 18): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/Extensions.kt: (102, 18): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/Extensions.kt: (120, 18): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/MediaObserver.kt: (36, 51): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (121, 11): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (131, 11): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (149, 59): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (157, 60): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (181, 62): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (194, 11): Unresolved reference: toUInt

e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (211, 11): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (228, 11): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (250, 11): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (268, 11): Unresolved reference: toUInt
e: /Users/everythingapple/developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.1/android/src/main/java/io/agora/rtc/base/RtcChannelEvent.kt: (307, 74): Unresolved reference: toUInt

**Comment by sadaqatkarimi** [comment]
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.7 19H1615 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by littleGnAl** [comment]
Hello @sadaqatkarimi, what's the kotlin version you use?

**Comment by sadaqatkarimi** [comment]
solve by upgrading kotlin extionsion to   ext.kotlin_version = '1.6.10'
