### ISSUE TITLE
Building for iOS Simulator

### ISSUE THREAD

**Issue by ceto2016** [AgoraIO/Agora-Flutter-SDK#601]
**Describe the bug**
i use the package in my project but when build ios 
but i get this and build stoped with this error 

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '[/Users/c/Desktop/flutter/projects/pharma-line-1/ios/Pods/AgoraRtcEngine_iOS/AgoraCore.framework/AgoraCore]()' for architecture arm64

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.

<img width="1378" alt="Screen Shot 1443-07-20 at 6 44 49 PM" src="https://user-images.githubusercontent.com/66456782/154996787-04e745ac-2062-45de-806e-d186ef8a8e36.png">

**Comment by littleGnAl** [comment]
Pls try `agora_rtc_engine: ^5.0.0`

**Comment by isiyemijoe** [comment]
I'm currently using 5.0.0 and I'm still facing this issue

**Comment by LichKing-2234** [comment]
Pls try
https://stackoverflow.com/questions/63607158/xcode-building-for-ios-simulator-but-linking-in-an-object-file-built-for-ios-f/63955114#63955114

**Comment by ceto2016** [comment]
@LichKing-2234 @isiyemijoe  
after pod install open Xcode then go to Pods => AgoraIrisRTC_iOS target  => build Setting => EXCLUDED ARCHS and replace all values with arm64 it will work 
<img width="842" alt="Screen Shot 1443-08-14 at 6 04 51 AM" src="https://user-images.githubusercontent.com/66456782/158514701-7a7e4045-9ff3-4728-b092-12a8b955d372.png">
