### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by wangemng** [AgoraIO/Agora-Flutter-SDK#602]
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/wangmeng/AndroidStudioProjects/YueMeng/meeting/ios/Pods/AgoraIrisRTC_iOS/AgoraCIExtension.framework/AgoraCIExtension' for architecture arm64

 Xocde 13.2.1 
 agora_rtc_engine: ^5.0.0

**Comment by littleGnAl** [comment]
Try adding this line to see helpful or not
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/1b44bcdb534a8acac94daaf1347608b515c9a962/example/ios/Podfile#L51

**Comment by PublioDev** [comment]
I am facing the same error but using a M1 apple laptop, excluding arm64 arch is not an option. ¿Any ideas?

**Comment by louisschprs** [comment]
We have the same issue ```building for iOS Simulator, but linking in dylib built for iOS, file '/Users/user/Documents/Work/repos/drrabbyt/ios/Pods/AgoraIrisRTC_iOS/AgoraCIExtension.framework/AgoraCIExtension' for architecture arm64```
