### ISSUE TITLE
iOS build warnings

### ISSUE THREAD

**Issue by krishnashetty0** [AgoraIO/Agora-Flutter-SDK#604]
**Describe the bug**
I am seeing warning messages when I try to build for iOS platform. Please have a look on the attached screenshot
<img width="565" alt="Screenshot 2022-02-25 at 4 01 35 PM" src="https://user-images.githubusercontent.com/7000544/155700167-44c1ddd7-7ef5-4776-9831-0dbf6fd71d10.png">

**To Reproduce**
build flutter app for iPhone

**Comment by littleGnAl** [comment]
@krishnashetty0 Can you try `agora_rtc_engine: ^5.0.0`

**Comment by krishnashetty0** [comment]
I still got some warnings with agora_rtc_engine: ^5.0.0

**Comment by LichKing-2234** [comment]
You can ignore these warning, we support all methods, may someone is deprecated.
