### ISSUE TITLE
building for iOS Simulator, but linking in dylib built for iOS

### ISSUE THREAD

**Issue by Ashfaqroy** [AgoraIO/Agora-Flutter-SDK#611]
building for iOS Simulator, but linking in dylib built for iOS, file '/Users/newuser/flutterproject/workshop/befriend/ios/Pods/AgoraIrisRTC_iOS/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension' for architecture arm64
![Screenshot 2022-03-03 at 8 14 09 AM](https://user-images.githubusercontent.com/49291321/156489275-ad16c299-3b22-4485-85a1-6367626fb7b1.png)

**Comment by littleGnAl** [comment]
Duplicated issue here https://github.com/AgoraIO/Agora-Flutter-SDK/issues/601

**Comment by demagomes** [comment]
I have got the same issue and tried solution of https://github.com/AgoraIO/Agora-Flutter-SDK/issues/601 but it still doesn't work. Weirdly, the example app works on the simulator, but adding the agora pub AgoraIrisRTC_iOS breaks the app with the error below:

`Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file
'/Users/ademargomes/Dev/code/sellfie/ios/Pods/AgoraIrisRTC_iOS/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExten
sion' for architecture arm64


Could not build the application for the simulator.
Error launching application on iPhone 12.`
