### ISSUE TITLE
Video doesn't switch on, on MacOS 

### ISSUE THREAD

**Issue by RivaanRanawat** [AgoraIO/Agora-Flutter-SDK#613]
**Describe the bug**
Video doesn't switch on on MacOS, works on Android, iOS, & Web but not on MacOS. Instead of displaying video, displays TARGETPLATFORM.MACOS IS NOT YET SUPPORTED BY PLATFORM. I read the documentation where this is not written. I can listen to other callers even if my video isn't working.

**Expected behavior**
My Video should show up

**Screenshots**
<img width="901" alt="Screenshot 2022-03-05 at 10 47 48 PM" src="https://user-images.githubusercontent.com/46225838/156893587-e5343d7e-82da-4446-b9cc-8dc40b54af9c.png">

**Desktop**
 - OS: MAC
 - Version: 12.2.1
 
 Any help would be appreciated!

**Comment by littleGnAl** [comment]
Hello @RivaanRanawat , can you provide a reproducible demo?

**Comment by masuidrive** [comment]
I have the same issue.

Created black flutter project and copy "main.dart" from https://pub.dev/packages/agora_rtc_engine/example and comment out "permission request" line.

<img width="621" alt="Screen Shot 2022-03-11 at 13 25 55" src="https://user-images.githubusercontent.com/12104/157802008-50e09d0c-4fa7-445f-9737-ff6dedd9bfb3.png">

Versions:
agora_rtc_engine: ^5.0.0
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (8 days ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
macOS: 12.2.1
Xcode: 13.1
