### ISSUE TITLE
[FLUTTER] Access denied finding property "net.dns1" 

### ISSUE THREAD

**Issue by manhnguyengithub** [AgoraIO/Agora-Flutter-SDK#616]
When i try **agora_rtc_engine**, i found this error in run log
I/GDPAndroid(23256): getCpuTemperature valid path:/sys/class/thermal/thermal_zone0/temp
E/libc    (23256): Access denied finding property "net.dns1"
E/libc    (23256): Access denied finding property "net.dns2"
E/libc    (23256): Access denied finding property "net.dns3"
E/libc    (23256): Access denied finding property "net.dns4"

and i just see a loading, no video streaming

can some one fix it for me

**Comment by LichKing-2234** [comment]
You can ignore this log, have you double-check your appId and token?

**Comment by manhnguyengithub** [comment]
> You can ignore this log, have you double-check your appId and token?

thank you!
