### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'Iterable<dynamic>'

### ISSUE THREAD

**Issue by UCetinkaya94** [AgoraIO/Agora-Flutter-SDK#617]
**Describe the bug**
`Unhandled Exception: type 'Null' is not a subtype of type 'Iterable<dynamic>'` is printed throughout a voice call when `enableAudioVolumeIndication` is called.

The exception happens here, at line 1570 in `events.dart` https://github.com/AgoraIO/Agora-Flutter-SDK/blob/1b44bcdb534a8acac94daaf1347608b515c9a962/lib/src/events.dart#L1570

`newData[0]` sometimes contains null.
<img width="233" alt="2" src="https://user-images.githubusercontent.com/67158575/157825229-f4012117-2b9f-4156-a05a-cfd83f382fc1.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: 12.2.1

**Smartphone (please complete the following information):**
 - Device: tested on the iOS simulator (iPhone 13) and Android Emulator (Pixel 6)
 - OS: iOS, Android,
 - Version 15.2, 12

**Additional context**
agora_rtc_engine version 5.0.0

**Comment by littleGnAl** [comment]
This is a known issue and had been fixed in our dev branch, a new release will be released later.

**Comment by UCetinkaya94** [comment]
Thanks 🙏🏻

**Comment by littleGnAl** [comment]
@UCetinkaya94 This issue had been fixed, you can try the pre-release version [agora_rtc_engine: ^5.0.1-rc.1](https://pub.dev/packages/agora_rtc_engine/versions/5.0.1-rc.1), or wait for the next release.
