### ISSUE TITLE
Execution failed for task ':agora_rtc_engine:compileProfileKotlin'.

### ISSUE THREAD

**Issue by AJAY-AGARIAN** [AgoraIO/Agora-Flutter-SDK#623]
`Generating` flutter profile apk ends up getting agora related error:
**Execution failed for task ':agora_rtc_engine:compileProfileKotlin'.**

Command:
flutter build apk --profile

I am using the latest Android Studio version as well as all dependencies are up to date
Agora Packages:
> agora_rtc_engine: ^5.0.0
> agora_rtm: ^1.0.1 

Note: App runs fine on debug 

Expanded error message:

e: C:\Users\Ajay\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.0.0\android\src\main\kotlin\io\agora\agora_rtc_engine\Agor
aRtcEnginePlugin.kt: (253, 18): Type mismatch: inferred type is String? but String was expected
e: C:\Users\Ajay\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.0.0\android\src\main\kotlin\io\agora\agora_rtc_engine\Agor
aSurfaceViewFactory.kt: (16, 1): Class 'AgoraSurfaceViewFactory' is not abstract and does not implement abstract base class member public abstract
fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\Users\Ajay\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.0.0\android\src\main\kotlin\io\agora\agora_rtc_engine\Agor
aSurfaceViewFactory.kt: (20, 3): 'create' overrides nothing
e: C:\Users\Ajay\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.0.0\android\src\main\kotlin\io\agora\agora_rtc_engine\Agor
aTextureViewFactory.kt: (12, 1): Class 'AgoraTextureViewFactory' is not abstract and does not implement abstract base class member public abstract
fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\Users\Ajay\Downloads\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.0.0\android\src\main\kotlin\io\agora\agora_rtc_engine\Agor
aTextureViewFactory.kt: (17, 3): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileProfileKotlin'.
> Compilation error. See log for more details

**Comment by littleGnAl** [comment]
Hello @AJAY-AGARIAN , can you print the `flutter doctor`, and which kotlin version do you use?

**Comment by AJAY-AGARIAN** [comment]
**Kotlin version**: **211-1.6.10-release-923-AS7442.40**

**Flutter doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.11.0-0.0.pre.870, on Microsoft Windows [Version 10.0.19042.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[√] Android Studio (version 2021.1)
[√] VS Code, 64-bit edition (version 1.64.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by suyie001** [comment]
the same problem. How to fix it?

**Comment by AJAY-AGARIAN** [comment]
> 

DIdn't get any fix till now, opened a StackOverflow query too.

**Comment by littleGnAl** [comment]
It's a breaking change of flutter SDK, but we only support the stable version of flutter SDK
https://github.com/flutter/engine/pull/30807

**Comment by AJAY-AGARIAN** [comment]
Does that mean downgrading flutter from pre versions to stable version solves the problem? The current stable flutter version is 2.10.3 as mentioned here: [https://docs.flutter.dev/development/tools/sdk/releases](https://docs.flutter.dev/development/tools/sdk/releases
)

**Comment by AJAY-AGARIAN** [comment]
Switching to a stable release and then building profile apk succeeded.

Steps:
1. Run **flutter channel stable** in terminal to switch to the stable release of flutter
2. Check the flutter version now using: **flutter --version** , it should show  version: **2.10.3** (Current stable version)
3. Run **flutter clean**
4. Run **flutter build apk --profile**, this time apk should be successfully built.
