### ISSUE TITLE
V5.0.0 setEventHandler reported NoSuchMethodError: The getter 'iterator' was called on null

### ISSUE THREAD

**Issue by guopeng1994** [AgoraIO/Agora-Flutter-SDK#624]
while setting rtc engine setEventHandler function, this error occurred

when set a breakpoint, i found that inside setEventHandler function,  it used a process function(line 236), this process func occurred en error while process the method name 'AudioVolumeIndication', and because of the data with this method have an attribute which value is null, so inside AudioVolumeIndication case , create a list form this null value failed, and error occurred

i tested in real phone, emulator, same error

see this picture
![image](https://user-images.githubusercontent.com/30316642/158161793-7da15bd6-9348-4dec-bee4-5f5b74eed089.png)

i don't know why my speakers are null

maybe you should return [] but not null, so that list conversion should complete

**Comment by littleGnAl** [comment]
This issue had been fixed, you can try the pre-release version [agora_rtc_engine: ^5.0.1-rc.1](https://pub.dev/packages/agora_rtc_engine/versions/5.0.1-rc.1), or wait for the next release.

**Comment by guopeng1994** [comment]
@littleGnAl ok, thanks i will try that version

**Comment by guopeng1994** [comment]
good work! waiting for the next release version.
