### ISSUE TITLE
Update the Pub.dev listings

### ISSUE THREAD

**Issue by fisforfaheem** [AgoraIO/Agora-Flutter-SDK#625]
it needs to be updated...because it looks like it's not properly listed .

Also please improve the video calling performance for Pakistani local users

**Comment by littleGnAl** [comment]
Sorry @fisforfaheem, I'm not very sure what does pub.dev listings mean, can you give more detail about this?

**Comment by fisforfaheem** [comment]
it fixed auto: 
![Uploading image.png…]()
