### ISSUE TITLE
android 31 打包出错

### ISSUE THREAD

**Issue by suyie001** [AgoraIO/Agora-Flutter-SDK#629]
使用agora_rtc_engine: ^5.0.1，flutter sdk 2.10，compileSdkVersion 31。
运行构建的时候得到报错为下：

Could not determine the dependencies of task ':agora_rtc_engine:compileDebugJavaWithJavac'.
> Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

在没有使用声网的其他项目兼容android 31都没问题，sdk build tools 我也重装过，应该不是build tools的问题。

**Comment by littleGnAl** [comment]
It seems related to https://github.com/AgoraIO/Agora-Flutter-SDK/issues/608

**Comment by sayhellotogithub** [comment]
[](https://user-images.githubusercontent.com/9547097/163512713-cb4f24f4-a7a6-4d81-a64f-30b14dc52811.png)please remove buildToolsVersion safeExtGet('buildToolsVersion', '31.0.0')
896FA7BD-4445-450F-B647-C22AB87D8DDF

**Comment by sayhellotogithub** [comment]
please remove buildToolsVersion safeExtGet('buildToolsVersion', '31.0.0')
![](https://user-images.githubusercontent.com/9547097/163512713-cb4f24f4-a7a6-4d81-a64f-30b14dc52811.png)
