### ISSUE TITLE
missing export in rtc_engine.dart    5.0.1

### ISSUE THREAD

**Issue by nobodyyu** [AgoraIO/Agora-Flutter-SDK#630]
export 'src/rtc_render_view.dart' show RtcSurfaceView

AgoraRenderWidget 不見了
不加這行。外面想要用 RtcSurfaceView 會找不到

麻煩了。加油

**Comment by littleGnAl** [comment]
Hello @nobodyyu, you should use `lib/rtc_local_view.dart`/`lib/rtc_remote_view.dart` instead.
