### ISSUE TITLE
Android apk size increased after version 5

### ISSUE THREAD

**Issue by lotus-x** [AgoraIO/Agora-Flutter-SDK#631]
**Describe the bug**
Below are some screenshots comparing version 4.2.1 & 5.0.1 (Using basic example, only agora and persmission handler are dependencies)

**To Reproduce**
Repeatedly generated apks few times

**Expected behavior**
Android releases shouldn't be affected by the new version that supports desktop right?

**Screenshots**

Version 4.2.1
![image](https://user-images.githubusercontent.com/43782734/159416486-0a06f997-742a-4496-abdd-b1b3ed6c9731.png)

Version 5.0.1
![image](https://user-images.githubusercontent.com/43782734/159416649-43b4a4b4-2f33-4820-9e5b-722c12792ec3.png)

**Comment by littleGnAl** [comment]
The symbol is packaged unexpectedly, we will fix it in the next release, you can add the `packagingOptions` to your `build.gradle` file to temporarily remove it at this time
```gradle
packagingOptions {
      exclude "**/libAgoraRtcWrapperSymbol.so"
 }
```

**Comment by lotus-x** [comment]
Thank you
