### ISSUE TITLE
Virtual background images do not load and result in a white screen

### ISSUE THREAD

**Issue by takuya-ohmuro** [AgoraIO/Agora-Flutter-SDK#633]
**Describe the bug**
When I load a virtual background image on iOS, I get a white screen when loading fails.

**To Reproduce**
1. Try setting an image as a virtual background in iOS.

The paths in the image are correct and the rest of the operation is working fine.
If there are any mistakes, please let me know.

```
_engine?.enableVirtualBackground(
        true,
        VirtualBackgroundSource(
          backgroundSourceType: VirtualBackgroundSourceType.Img,
          source: 'assets/images/live/test-back.jpeg',
        ),
      );
```

**Expected behavior**
I am assuming that the set local image will be displayed as the background.

**Screenshots**
![IMG_76B49D1864A6-1](https://user-images.githubusercontent.com/34786680/159701897-c3b706a1-56d5-44d6-b90d-66b60f9f9f73.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone11Pro
 - OS: iOS15.4
- Flutter: 2.10.3
- agora : 5.0.1

**Comment by littleGnAl** [comment]
@takuya-ohmuro You should use `_engine.getAssetAbsolutePath` to get the absolute path for the asset

**Comment by takuya-ohmuro** [comment]
@littleGnAl 
Thanks for the reply, I tried getAssetAbsolutePath but it still doesn't load properly.

```
String? _path = await _engine
          ?.getAssetAbsolutePath('assets/images/live/test-back2.png');
      await _engine?.enableVirtualBackground(
        true,
        VirtualBackgroundSource(
          backgroundSourceType: VirtualBackgroundSourceType.Img,
          source: _path,
        ),
      );
```
Here is the source obtained by getAssetAbsolutePath.
`"source":"[/private/var/containers/Bundle/Application/8CF3F199-236D-4FB1-A796-5F6AA0798482/Runner.app/Frameworks/App.framework/flutter_assets/assets/images/live/test-back2.png]`

<img width="257" alt="スクリーンショット 2022-03-25 9 43 50" src="https://user-images.githubusercontent.com/34786680/160032861-e2a8b7f5-0216-4bf7-b26b-a900522b8681.png">

Is the Path wrong?

**Comment by takuya-ohmuro** [comment]
I tried the same build on android but got a white screen.

**Comment by littleGnAl** [comment]
@takuya-ohmuro 
Sorry for the late response, we confirmed that it's a bug, we will fix it in the next release.

**Comment by takuya-ohmuro** [comment]
Thank you for your confirmation.

**Comment by littleGnAl** [comment]
`agora_rtc_engine: 5.1.0` has fixed this issue and here is an example of how to use `enableVirtualBackground `
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/example/lib/examples/advanced/enable_virtualbackground/enable_virtualbackground.dart
