### ISSUE TITLE
AgoraRtcWrapper error on iOS App

### ISSUE THREAD

**Issue by fflores-facephi** [AgoraIO/Agora-Flutter-SDK#635]
After updating the plugin version to 5.0.1, I get the following error when launching the iOS app:

**Library not loaded: @rpath/AgoraRtcWrapper.framework/AgoraRtcWrapper
  Referenced from: /private/var/containers/Bundle/Application/5718DF1D-D918-4DAD-AFCC-47012BD6B6ED/ios.app/Frameworks/agora_rtc_engine.framework/agora_rtc_engine**

**Comment by LichKing-2234** [comment]
have you run pod install successd?

**Comment by fflores-facephi** [comment]
Yes, I have, but I got the same result.

All these references to agora appear in the file podfile.lock, but none is AgoraRtcWrapper

  - AgoraRtcEngine_iOS (3.6.2):
    - AgoraRtcEngine_iOS/AINS (= 3.6.2)
    - AgoraRtcEngine_iOS/AV1Dec (= 3.6.2)
    - AgoraRtcEngine_iOS/ContentInspect (= 3.6.2)
    - AgoraRtcEngine_iOS/FullAudioFormat (= 3.6.2)
    - AgoraRtcEngine_iOS/JND (= 3.6.2)
    - AgoraRtcEngine_iOS/ReplayKit (= 3.6.2)
    - AgoraRtcEngine_iOS/ROIEnc (= 3.6.2)
    - AgoraRtcEngine_iOS/RtcBasic (= 3.6.2)
    - AgoraRtcEngine_iOS/SuperResolution (= 3.6.2)
    - AgoraRtcEngine_iOS/VideoPreprocess (= 3.6.2)
    - AgoraRtcEngine_iOS/VirtualBackground (= 3.6.2)

**Comment by littleGnAl** [comment]
Maybe you should run `flutter clean` first

**Comment by fflores-facephi** [comment]
We have changed the PODFILE file of the client application, replacing "AgoraRtcEngine_iOS" with "AgoraIrisRTC_iOS" and the error no longer appears.

Thanks!!!
