### ISSUE TITLE
Cannot render view in web of ios/android platform

### ISSUE THREAD

**Issue by duchieupham** [AgoraIO/Agora-Flutter-SDK#638]
**Describe the bug**
I'm facing with problem that Agora cannot render view in web of ios/android platform. It's a blank space although user joinChannel successful. 
The audio still work, but the video is not presented.

**Screenshots**
I saw the problem in library source code. My expect checking is "kIsWeb &&  (defaultTargetPlatform == TargetPlatform.iOS)", but the checking code has 3 cases and does not contain my case. If user open web browser on ios/android devices, it never go into kIsWeb case.

[
![agora_rtc_render_view](https://user-images.githubusercontent.com/95468742/160590240-bd9d20a3-812d-4161-807c-c35cc1926e80.png)
](url)

I hope you can help me this problem. Do I have any solution?

**Comment by littleGnAl** [comment]
Hello @duchieupham, which version of `agora_rtc_engine` do you use?

**Comment by duchieupham** [comment]
I'm using this!

![agora_version](https://user-images.githubusercontent.com/95468742/160593358-b63db331-dab6-4768-b2e0-20642220e1b8.png)

**Comment by littleGnAl** [comment]
Pls try `agora_rtc_engine: 5.0.1`

**Comment by duchieupham** [comment]
It's not work for me when I'm using agora_rtc_engine: 5.0.1. :(

**Comment by littleGnAl** [comment]
Maybe you should try our example or a reproducible demo is helpful.
