### ISSUE TITLE
Can not hear playback when call startAudioRecordingDeviceTest

### ISSUE THREAD

**Issue by ThangD** [AgoraIO/Agora-Flutter-SDK#639]
**Describe the bug**
Test input device with startAudioRecordingDeviceTest(2000) but do not hear any playback recording

**Expected behavior**
We can hear playback with interval setting when running startAudioRecordingDeviceTest

**Desktop 
 - OS: Window
 - Version 11

**Comment by littleGnAl** [comment]
Hello @ThangD, the `audioVolumeIndication` callback will be triggered but without any playback after the `startAudioRecordingDeviceTest` function is called.
see the doc for reference https://docs.agora.io/cn/Voice/API%20Reference/flutter/v5.0.0/API/class_rtcdevicemanager.html#api_iaudiodevicemanager_startrecordingdevicetest

**Comment by ThangD** [comment]
@littleGnAl Thank you for your information. Which method can we use for test the input sound (like record and play ). Thanks.

**Comment by littleGnAl** [comment]
@ThangD Maybe you can try `startAudioPlaybackDeviceTest`
