### ISSUE TITLE
Need complete guide on windows plateform

### ISSUE THREAD

**Issue by Manishmg3994** [AgoraIO/Agora-Flutter-SDK#640]
AS per mentioned by your readme.md , i was unable to understand the whole process of integrating agora with desktop
,so i wish someone to help me

**Comment by littleGnAl** [comment]
Hello @Manishmg3994, sorry for making you confused, the [agora_rtc_engine](https://pub.dev/packages/agora_rtc_engine) supports Windows by default, you can add the dependency to your `pubspec.yaml` directly.

**Comment by Manishmg3994** [comment]
thanks ,but i need a favour from agora for my new startup

**Comment by littleGnAl** [comment]
If you need Agora to help on the development on behalf, please submit a ticket via https://agora-ticket.agora.io/ with the request. The support team will help you engage the partnership team.
