### ISSUE TITLE
Could not download iris-rtc-3.5.2.aar

### ISSUE THREAD

**Issue by baseplate77** [AgoraIO/Agora-Flutter-SDK#641]
There was internet connection but still for some reason it failed to download. any known anything please let me known

`* What went wrong:
Execution failed for task ':agora_rtc_engine:generateDebugRFile'.
> Could not resolve all files for configuration ':agora_rtc_engine:debugCompileClasspath'.
   > Could not download iris-rtc-3.5.2.aar (com.github.agorabuilder:iris-rtc:3.5.2)
      > Could not get resource '[https://www.jitpack.io/com/github/agorabuilder/iris-rtc/3.5.2/iris-rtc-3.5.2.aar]()'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 55s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by littleGnAl** [comment]
It is most likely the network issue

**Comment by baseplate77** [comment]
i have double check my internet connection, I am sure it is not because of that

**Comment by chaochaox1990** [comment]
> Could not resolve all files for configuration ':agora_rtc_engine:profileRuntimeClasspath'.
   > Could not resolve com.github.agorabuilder:iris-rtc:3.5.2.
     Required by:
         project :agora_rtc_engine
      > Could not resolve com.github.agorabuilder:iris-rtc:3.5.2.
         > Could not get resource 'http://172.16.27.229:8081/nexus/repository/maven-public/com/github/agorabuilder/iris-rtc/3.5.2/iris-rtc-3.5.2.pom'.
            > Could not HEAD 'http://172.16.27.229:8081/nexus/repository/maven-public/com/github/agorabuilder/iris-rtc/3.5.2/iris-rtc-3.5.2.pom'.
               > Connect to 172.16.27.229:8081 [/172.16.27.229] failed: connect timed out
   > Could not resolve io.flutter:flutter_embedding_profile:1.0.0-40a99c595137e4b2f5b2efa8ff343ea23c1e16b8.
     Required by:
         project :agora_rtc_engine
      > Could not resolve io.flutter:flutter_embedding_profile:1.0.0-40a99c595137e4b2f5b2efa8ff343ea23c1e16b8.
         > Could not get resource 'http://172.16.27.229:8081/nexus/repository/maven-public/io/flutter/flutter_embedding_profile/1.0.0-40a99c595137e4b2f5b2efa8ff343ea23c1e16b8/flutter_embedding_profile-1.0.0-40a99c595137e4b2f5b2efa8ff343ea23c1e16b8.pom'.
            > Could not GET 'http://172.16.27.229:8081/nexus/repository/maven-public/io/flutter/flutter_embedding_profile/1.0.0-40a99c595137e4b2f5b2efa8ff343ea23c1e16b8/flutter_embedding_profile-1.0.0-40a99c595137e4b2f5b2efa8ff343ea23c1e16b8.pom'.
               > Connect to 172.16.27.229:8081 [/172.16.27.229] failed: connect timed out

**Comment by chaochaox1990** [comment]
not working suddenly

**Comment by littleGnAl** [comment]
The library has been published to maven, you can try temporarily removing the jitpack to see if works or not
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/a558c31ac8985e4c6425d26c13bc5bbd6e1122d8/android/build.gradle#L26

**Comment by Codesait** [comment]
> The library has been published to maven, you can try temporarily removing the jitpack to see if works or not
> 
> https://github.com/AgoraIO/Agora-Flutter-SDK/blob/a558c31ac8985e4c6425d26c13bc5bbd6e1122d8/android/build.gradle#L26


![](https://files.slack.com/files-pri/TN2MVC81E-F03AHSP5CBS/screenshot_2022-04-02_at_1.08.16_pm.png)

**Comment by GauravCalidig** [comment]
Facing Same Issue

**Comment by littleGnAl** [comment]
Related issue https://github.com/AgoraIO/Agora-Flutter-SDK/issues/650
