### ISSUE TITLE
An easier way to get remote users already live in the channel when a local user joins the channel.

### ISSUE THREAD

**Issue by agent515** [AgoraIO/Agora-Flutter-SDK#644]
**Is your feature request related to a problem? Please describe.**
I want a local user to get the details about the remote users who are already in the channel when the local user joins the channel.

I know you've mentioned [this](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/174#issuecomment-691664325) comment from https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/174. For very basic information such as users' info, this seems quite extra work.

**Describe the solution you'd like**
Provide a map of the users (basic info such as id, name, role) already in the channel in the `joinChannelSuccess` callback. This way should seem more intuitive.

**Describe alternatives you've considered**
[This](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/174#issuecomment-691664325) is not very clear to me. I would appreciate clear documentation and including getting user details in the channel in examples.

**Additional context**

**Comment by littleGnAl** [comment]
You can only get UID from the SDK, something like the user name,  the user role, etc, should be business logic, which should be maintained by yourself.
