### ISSUE TITLE
M1 Mac arm64 issue with AgoraCI Extension

### ISSUE THREAD

**Issue by louisschprs** [AgoraIO/Agora-Flutter-SDK#646]
**Describe the bug**
On a M1 Mac building for our flutter application fails with the following message 
`building for iOS Simulator, but linking in dylib built for iOS, file '/Users/morne/Documents/Work/repos/drrabbyt/ios/Pods/AgoraIrisRTC_iOS/AgoraCIExtension.framework/AgoraCIExtension' for architecture arm64`

**To Reproduce**
1. Add agora_rtc_engine: ^5.0.1 to the pubspec file 
2. run `flutter pub get`
3. run `pods install`
4. Click build with a simulator selected 
5. See the error `building for iOS Simulator, but linking in dylib built for iOS, file '/Users/morne/Documents/Work/repos/drrabbyt/ios/Pods/AgoraIrisRTC_iOS/AgoraCIExtension.framework/AgoraCIExtension' for architecture arm64`

**Expected behavior**
For the build to complete 

**Screenshots**

![](https://cdn.discordapp.com/attachments/598193500210724891/961641666547187742/Screenshot_2022-04-07_at_17.00.32.png)

**Desktop (please complete the following information):**
 - OS: [ iOS 15.4 ]
 - Host OS: Mac OS Monterey 12.3 
 - Architecture: arm64 (M1 Mac chip)
 - Version Agora RTC Engine v5.0.1
 - XCode 13

**Additional context**
Xcode Build fails with the following message 
`building for iOS Simulator, but linking in dylib built for iOS, file '/Users/morne/Documents/Work/repos/drrabbyt/ios/Pods/AgoraIrisRTC_iOS/AgoraCIExtension.framework/AgoraCIExtension' for architecture arm64`

**Comment by aryalg** [comment]
.

**Comment by littleGnAl** [comment]
This issue will be fixed in the next release.

**Comment by littleGnAl** [comment]
This issue is fixed, pls try upgrade agora_rtc_engine: 5.1.0
https://pub.dev/packages/agora_rtc_engine
