### ISSUE TITLE
SDK ERROR

### ISSUE THREAD

**Issue by vengatesan125** [AgoraIO/Agora-Flutter-SDK#654]
* AppData\Local\Pub\Cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraRtcEnginePlugin.kt: (251, 18): Type mismatch: inferred type is String? but String was expected
* AppData\Local\Pub\Cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (16, 1): Class 'AgoraSurfaceViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
* AppData\Local\Pub\Cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (20, 3): 'create' overrides nothing
* AppData\Local\Pub\Cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (12, 1): Class 'AgoraTextureViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
* AppData\Local\Pub\Cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (17, 3): 'create' overrides nothing
* FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.

**Comment by littleGnAl** [comment]
Seems the related issue https://github.com/AgoraIO/Agora-Flutter-SDK/issues/623

**Comment by vengatesan125** [comment]
* Issue solved, thanks.
* I upgrade my flutter version 2.10.2 to latest.
* thanks for once again. save my time.
