### ISSUE TITLE
Flutter App freezes on disconnecting from video call

### ISSUE THREAD

**Issue by nathanielajayi7** [AgoraIO/Agora-Flutter-SDK#658]
**Describe the bug**
Using the audio call feature, everything works fine and as should, but the video call does not terminate properly. The app is frozen with logs that look like this :

`Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
2
I/GDPAndroid(30079): getCpuTemperature valid path:/sys/class/thermal/thermal_zone0/temp
E/spdlog  (30079): [2022-04-22 17:41:13.971] [0] [error] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/internal/rtc_engine_event_handler.cc:56 onError err 1017 msg nullptr
3
I/GDPAndroid(30079): getCpuTemperature valid path:/sys/class/thermal/thermal_zone0/temp
E/spdlog  (30079): [2022-04-22 17:41:19.973] [0] [error] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/internal/rtc_engine_event_handler.cc:56 onError err 1017 msg nullptr
3
I/GDPAndroid(30079): getCpuTemperature valid path:/sys/class/thermal/thermal_zone0/temp
E/spdlog  (30079): [2022-04-22 17:41:25.976] [0] [error] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/internal/rtc_engine_event_handler.cc:56 onError err 1017 msg nullptr
W/aratam.buynsel(30079): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
2
I/GDPAndroid(30079): getCpuTemperature valid path:/sys/class/thermal/thermal_zone0/temp
2
W/System  (30079): A resource failed to call release.
I/GDPAndroid(30079): getCpuTemperature valid path:/sys/class/thermal/thermal_zone0/temp
`

**To Reproduce**
1. Set Up Agora on Fluttter
2.  Init engine and set event handler, then call leaveChannel and pop screen after 
3. App freezes in state
4. Weird CPU logs and memory leaks

**Expected behavior**
Terminate Agora screen and go back like with audio call
![Screenshot (47)](https://user-images.githubusercontent.com/54505255/164759912-dde862d0-6220-4b0a-b56d-dd60b6de8e08.png)
![Screenshot (46)](https://user-images.githubusercontent.com/54505255/164759915-e0bbe0c3-f40c-449b-aef3-520423c6ec41.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Flutter 2.10.3
 - Agora 5.1.0

**Smartphone (please complete the following information):**
 - Device: LG G7 ThinQ
 - OS: Android 10

**Additional context**

**Comment by littleGnAl** [comment]
Do you grant the camera permission? BTW I think a reproducible demo for this case is helpful.

**Comment by nathanielajayi7** [comment]
Yes. The video call works all fine, the issue is onDisconnect. When user
leaves or you leave the channel, the call is supposed to end and go back to
the previous screen but it just stops and kills the app.


Would it be okay to share an APK with you about this problem?

**Comment by littleGnAl** [comment]
The "leave channel" case works fine in our example https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/example/lib/examples/basic/join_channel_video/join_channel_video.dart, I think it is related to your business logic, a reproducible demo for this case is helpful than the APK.

**Comment by nathanielajayi7** [comment]
> The "leave channel" case works fine in our example https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/example/lib/examples/basic/join_channel_video/join_channel_video.dart, I think it is related to your business logic, a reproducible demo for this case is helpful than the APK.

Falling back to version 4.1.0 works fine and the hanging issue is gone. Thanks.

**Comment by programmermasrawy** [comment]
i have the same problem 
gives me : 
rtc_engine_event_handler.cc:56 onError err 1017 msg 
is there any magic solution for this i 've got mad for that...

**Comment by nathanielajayi7** [comment]
Falling back to Agora 4.x fixed this issue for me

**Comment by ArpitPatel21** [comment]
I am facing the same issue.... after disconnecting the call it shows black screen and working in the background...!!! can anyone tell me how to fix it. ✌️
