### ISSUE TITLE
Unhandled Exception: MissingPluginException on Windows

### ISSUE THREAD

**Issue by jack84156** [AgoraIO/Agora-Flutter-SDK#659]
**Describe the bug**
that's what i get when i pub get your plugin 
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
Exception: Gradle task assembleDebug failed with exit code 1

also ..

Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

**Additional context**

my gradle-7.4.1 - latest --- classpath 'com.android.tools.build:gradle:7.1.3'

my flutter sdk 2.10.5 latest 

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
[√] Android Studio (version 2021.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

that kind of error should not happen with plugin like Agora :)

**Comment by littleGnAl** [comment]
Hello @jack84156 , which version of `agora_rtc_engine` do you use?

**Comment by AlexXmoe** [comment]
agora_rtc_engine: ^5.1.0

**Comment by jack84156** [comment]
i am using the latest version ^5.1.0

**Comment by bermohmtnm** [comment]
i have the same problem too

**Comment by littleGnAl** [comment]
I'm so sorry that I can not reproduce this issue on my local machine, I think a reproducible demo for this case is necessary.

**Comment by jack84156** [comment]
waiting for customer to response , what should response for ?

**Comment by AlexXmoe** [comment]
@jack84156 we have common versions . did you try to use other agora version

**Comment by bermohmtnm** [comment]
hi guys , i tried to use old gradle version . and this solved the issue , but wonder how come agora does not care of updates !!!

**Comment by AlexXmoe** [comment]
@bermohmtnm  i tried with 7 versions .. but the same message error . it wont pub get  .. the problem is that i can't use old gradle because i have other plugins that require up to date  gradle versions

**Comment by bermohmtnm** [comment]
well , lets see @littleGnAl what to say ..

**Comment by littleGnAl** [comment]
Sorry guys, I try to reproduce this issue with `gradle-7.4.1`, `com.android.tools.build:gradle:7.1.3` but with no luck, a minimum demo can reproduce this issue is helpful, or reproducing by using our example is helpful too. https://github.com/AgoraIO/Agora-Flutter-SDK/tree/master/example.

**Comment by sam4523** [comment]
sorry i was not know it is duplicated here  .. any updates @jack84156 , @littleGnAl ?

**Comment by littleGnAl** [comment]
I have updated gradle version in our example and CI passed, I think this issue is not related to the gradle.
https://github.com/AgoraIO/Agora-Flutter-SDK/pull/663

**Comment by sam4523** [comment]
i cannot downlead the link you shared here 
https://github.com/AgoraIO/Agora-Flutter-SDK/tree/master/example.

**Comment by littleGnAl** [comment]
@sam4523 You should clone the repo

**Comment by sam4523** [comment]
yes sorry my bad

**Comment by sam4523** [comment]
i just finish running the example , i got the same Jack error message
Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
:(

**Comment by smit-sk** [comment]
I have same issue. 
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (17, 3): 'create' overrides nothing


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by littleGnAl** [comment]
@sam4523 Is there any error log in logcat?

**Comment by littleGnAl** [comment]
@smit-sk I think it's not a related issue, pls raise a new issue for your case, thanks.

**Comment by sam4523** [comment]
@smit-sk i think you have a difference issue as what @littleGnAl  said

**Comment by jack84156** [comment]
still the same issue , can i upload my repo to check it ? @littleGnAl

**Comment by reemXmoe** [comment]
i have the same issue

**Comment by reemXmoe** [comment]
@jack84156 did you solve this yet ?

**Comment by jack84156** [comment]
yes i solved it .. finally after too mush search 

i am wondering why this issue special happened with agora plugin .. but anyway here is the solution 

in gradle file .. android level if you had develop your app since awhile  you will find the following 




```
subprojects {
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
}


subprojects {
    subprojects {
        project.evaluationDependsOn(':app')
    }
}
```
just remove the extra doublicated  subprojects like following 

```
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
 project.evaluationDependsOn(':app')
}
```

**Comment by AlexXmoe** [comment]
@jack84156  thaaaaaaaaaaaaaaaaanks wow yes you right  it work with me too .. really thanks

**Comment by littleGnAl** [comment]
@jack84156 Good to see your issue fixed. The Flutter SDK sorts the plugins with the name's lexicographical order, you may see that the registration of `agora_rtc_engine` is sorted to first in `GeneratedPluginRegistrant`, most of the time the `agora_rtc_engine` faces the problem first if there's an issue with the Flutter SDK.

Here's another issue we face before https://github.com/flutter/flutter/issues/91018

**Comment by AlexXmoe** [comment]
@littleGnAl Oh , i just see it you even put the solution there as exactly mine , if you share that link with me before you will save my hard time looking for solution .. anyway thanks

**Comment by jack84156** [comment]
@littleGnAl Oooh i just see it , you even put the solution in that issue as mine exactly , if you share that issue with me before you will saved my hard time looking for solution , anyway thanks
