### ISSUE TITLE
wrapping version issue 

### ISSUE THREAD

**Issue by bermohmtnm** [AgoraIO/Agora-Flutter-SDK#661]
**Describe the bug**
i used the quick star example but i got the following
Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine) 

**To Reproduce**
1. pub get agora_rtc_engine: ^5.1.0
2. copied the quick star example 
3. i make sure every thing fine
4. i got the previous error message 

**Expected behavior**
to work as expected in doc .

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Device: [redmi note 9]
 - OS: [android]

**Additional context**

when i got that error message so i decided to flutter clean then it is completely not install the plugin with new error message which is 

FAILURE: Build failed with an exception.

Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.

Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/
BUILD FAILED in 52s
Exception: Gradle task assembleDebug failed with exit code 1 
  

my flutter sdk is 2.10.5  and the gradle-7.4.1 .. with latest classpath 'com.android.tools.build:gradle:7.1.3'

everything seem good in my flutter doctor 

thanks

**Comment by AlexXmoe** [comment]
hey i am facing the same error

**Comment by littleGnAl** [comment]
It seems it's duplicated issue https://github.com/AgoraIO/Agora-Flutter-SDK/issues/659

**Comment by littleGnAl** [comment]
Duplicated. Pls keep track here https://github.com/AgoraIO/Agora-Flutter-SDK/issues/659
