### ISSUE TITLE
MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

### ISSUE THREAD

**Issue by AlexXmoe** [AgoraIO/Agora-Flutter-SDK#662]
**Describe the bug**
Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [edge]

**Smartphone (please complete the following information):**
 - Device: [Samsung galaxy note 10]
 - OS: [android]
 

**Additional context**
 i keep this error message every time i use the quick star example  
Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

**Comment by littleGnAl** [comment]
Hello @AlexXmoe, can you print the `flutter doctor`? And which version of `agora_rtc_engine` do you use?

**Comment by AlexXmoe** [comment]
i am using the latest version 5.1.0 

flutter doctor

[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
[√] Android Studio (version 2021.1)
[√] Connected device (2 available)
[√] HTTP Host Availability

• No issues found!

**Comment by littleGnAl** [comment]
It seems it's duplicated issue https://github.com/AgoraIO/Agora-Flutter-SDK/issues/659

**Comment by littleGnAl** [comment]
Duplicated. Pls keep track here https://github.com/AgoraIO/Agora-Flutter-SDK/issues/659
