### ISSUE TITLE
cannot pub get the plugin with my up to date files  

### ISSUE THREAD

**Issue by sam4523** [AgoraIO/Agora-Flutter-SDK#664]
i am getting this code every time i install agora plugin 
No implementation found for method create on channel agora_rtc_engine

if i am not wrong i think agora does not use the latest version of the following .. some of my versions

![j](https://user-images.githubusercontent.com/98433037/165254243-fae20c89-bf68-4709-991a-79cda02c610b.png)

![jj](https://user-images.githubusercontent.com/98433037/165256097-7e684529-10db-4a04-9838-9fae3711baad.png)

my flutter doctor 
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 8.1.1415.168], )
[√] Android toolchain - develop for Android devices (Android SDK version 30.1.0-rc1)
[x] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 202216.1.2)
[√] Android Studio (version 2021.1)
[√] Connected device (1 available)
• One issues found!

i tried with these agora versions but no luck 

5.1.0 
50.1
5.0.0
4.2.2

No implementation found for method create on channel agora_rtc_engine

i am not sure if it versions issue . but i have everything up to date . thanks

**Comment by littleGnAl** [comment]
Duplicated https://github.com/AgoraIO/Agora-Flutter-SDK/issues/659
