### ISSUE TITLE
message error 

### ISSUE THREAD

**Issue by reemXmoe** [AgoraIO/Agora-Flutter-SDK#668]
i am using agora_rtc_engine: ^5.1.0
and that's what get when i install it 

![s](https://user-images.githubusercontent.com/104551969/165691216-ce2eb79d-bfdc-4657-9a22-6c8e6f225f67.png)

and this my gardle file  . Although I put compileSdkVersion
![2](https://user-images.githubusercontent.com/104551969/165690279-f22b4763-724f-4ade-832f-faab202f27fc.png)

my flutter doctor 
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (10 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Mohammed\AppData\Local\Android\sdk
    • Platform android-Tiramisu, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • ANE LX1 (mobile)  • 89UDU18716003747 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 100.0.4896.127

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

this is happen only when try to  install the plugin

**Comment by littleGnAl** [comment]
It's most likely the Flutter SDK issue, you'd better report it to the Flutter repo.

**Comment by reemXmoe** [comment]
thanks , but i don't think it is Flutter SDK issue at all . my app is published on appstore & google play since 3 years .. i have decide to update it to new version and include the agora plugin into it . but with no luck  .. also i am getting  new error message 

Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

**Comment by littleGnAl** [comment]
> Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
Is there any other logs apart from this?

**Comment by reemXmoe** [comment]
no .. i am getting this with previous errors message in my form

**Comment by reemXmoe** [comment]
sometimes it accept to install . but when i run my project it give me that error

**Comment by littleGnAl** [comment]
I think it's related to https://github.com/AgoraIO/Agora-Flutter-SDK/issues/659

**Comment by reemXmoe** [comment]
yes exactly .. you hit it

**Comment by littleGnAl** [comment]
Duplicated. Pls keep track here https://github.com/AgoraIO/Agora-Flutter-SDK/issues/659
