### ISSUE TITLE
Screen share on example is not working (Chrome & window)

### ISSUE THREAD

**Issue by ThangD** [AgoraIO/Agora-Flutter-SDK#669]
**Describe the bug**
Try to run screen share feature on window and web (chrome) but not working as expected

**To Reproduce**
1. Run example app with web
2. Run ScreenSharing
4. Screen share is duplicate multiple times as image attached
![image](https://user-images.githubusercontent.com/7744981/165896702-f0052315-aa2c-4ac5-9b44-f555002a9b0e.png)

**Expected behavior**
Screen share feature work normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Chrome

**Additional context**
Try to run on Window, but exception occurs 
![image](https://user-images.githubusercontent.com/7744981/165896986-45a69e04-6d5c-44ab-9b2a-c56838edfbd3.png)

Try to run on MACOS, the white screen for screen share
![image](https://user-images.githubusercontent.com/7744981/166647780-7f29bfbe-a3ee-4e0d-9e99-e335665cdd85.png)

**Comment by ThangD** [comment]
I just added this feature on window and the duplicate screen also display (seem like recursion function). @littleGnAl Could you pls help to confirm this is the flutter agora issue or missing anything else? Thanks.

**Comment by littleGnAl** [comment]
> Screen share is duplicate multiple times

This is called [Droste effect](https://en.wikipedia.org/wiki/Droste_effect). You should avoid capturing the preview window to avoid this.
