### ISSUE TITLE
no videoElement be created on mobile safari

### ISSUE THREAD

**Issue by chenyifan88** [AgoraIO/Agora-Flutter-SDK#670]
IAgoraRTCRemoteUser - videoTrack - player is undefined on mobile safari. so I see a black screen only.
I debug on mac safari,  the player property is not undefined. 

<img width="1122" alt="截屏2022-04-29 下午10 28 56" src="https://user-images.githubusercontent.com/40348648/165965322-2e624068-d408-4e2f-bb7c-9d236720cb28.png">

**Comment by littleGnAl** [comment]
Hello @chenyifan88 , can you share your example code?
