### ISSUE TITLE
muteAllRemoteAudioStreams not working

### ISSUE THREAD

**Issue by Losspost** [AgoraIO/Agora-Flutter-SDK#674]
**Describe the bug**
When calling muteAllRemoteAudioStreams in the flutter sdk it will not mute the audio streams. It is still possible to hear all users. 

**To Reproduce**
1. join voice channel
2. call muteAllRemoteAudioStreams inside the code3. 

**Expected behavior**
Mute all remote Audio stream, can't hear the other users anymore.

**Desktop (please complete the following information):**

- Flutter 2.13.0-0.0.pre.914 • channel master • https://github.com/flutter/flutter.git
- Framework • revision ceea3a6175 (vor 2 Tagen) • 2022-05-05 03:04:06 -0400
- Engine • revision f14e879b94
- Tools • Dart 2.18.0 (build 2.18.0-85.0.dev) • DevTools 2.13.0
- Flutter Web
- agora_rtc_engine: ^5.1.0

Initialize engine:
```
Future<StreamController> initEngine() async {

    _agoraUid = _userService.currentUser!.uid.hashCode;
    _engine = await RtcEngine.createWithContext(RtcEngineContext(appId));

    _addListeners();
  }
```

Join Channel:
```
Future<void> joinAudio(String channelName) async {
    // get Token for channel
    String token = await getAgoraToken(_agoraUid, channelName);
    await _engine.enableAudio();
    await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await _engine.setClientRole(ClientRole.Broadcaster);

    await _engine
        .joinChannel(token, channelName, null, _agoraUid)
        .catchError((onError) {
      print(onError);
      logSink.log('error ${onError.toString()}');
    });

    _engine.muteAllRemoteAudioStreams(true);
  }
```

**Comment by littleGnAl** [comment]
Hello @Losspost, I'm sorry that I can't reproduce this issue, can you provide a reproducible demo for this case?
