### ISSUE TITLE
Execution failed for task ':agora_rtc_engine:generateDebugRFile'

### ISSUE THREAD

**Issue by Ahsan166** [AgoraIO/Agora-Flutter-SDK#676]
Execution failed for task ':agora_rtc_engine:generateDebugRFile'.
> Could not resolve all files for configuration ':agora_rtc_engine:debugRuntimeClasspath'.
   > Could not find native-full-sdk.aar (com.github.agorabuilder:native-full-sdk:3.5.2).
     Searched in the following locations:
         https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.aar

**Comment by littleGnAl** [comment]
Duplicated https://github.com/AgoraIO/Agora-Flutter-SDK/issues/650
