### ISSUE TITLE
Connection problem with Agora

### ISSUE THREAD

**Issue by nizwar** [AgoraIO/Agora-Flutter-SDK#687]
**Describe the bug**
Suddenly agora not working and sounds like robotic while using some services carrier, and i think its not only on our app, it almost into all apps that use agora services such as our competitor.

when i print networkQuality it said tx = Unknown, rx = Unknown

**To Reproduce**
1. Implement your agora code
2. Use vodafone's carrier service, especially in qatar this problem occured

**Expected behavior**
We're aware if it was carrier service problem, but we can't tell our user to use vpn or implement cloud proxy since it was only happened on 1 carrier. we dont want to affect any user who didnt use vodafone

**Screenshots**
https://user-images.githubusercontent.com/33113137/169647991-9685da94-d212-493d-87e8-e78f10a4cb3b.mov

**Smartphone (please complete the following information):**
 - Happened on all devices

**Additional context**
With VPN its working fine, but when i switch it off, its happened again.

**Comment by nizwar** [comment]
I've open ticket on agora support, and it turned out that the vodafone carrier was blocked your VoIP, and then they suggest me to use SDK 3.7.0 while it was only available for iOS Native @LichKing-2234 @littleGnAl kindly upgrade it please

**Comment by littleGnAl** [comment]
Thanks, @nizwar, we will upgrade the native SDK 3.7.0 on the next release
