### ISSUE TITLE
Windows plugin fails to compile when example is run

### ISSUE THREAD

**Issue by dengking** [AgoraIO/Agora-Flutter-SDK#690]
error:

![image](https://user-images.githubusercontent.com/14926769/170439034-74a73c23-625d-47d5-b6ee-026fc51e8296.png)

**Comment by littleGnAl** [comment]
Hello @dengking , are there any files in the path `Agora-Flutter-SDK/windows/third_party/iris` path?

**Comment by dengking** [comment]
> Hello @dengking , are there any files in the path `Agora-Flutter-SDK/windows/third_party/iris` path?

都是中国人，那就被说英语了。

![image](https://user-images.githubusercontent.com/14926769/170659281-2f52d0d6-0fa4-4efb-aa4d-5570271f6c24.png)

**Comment by littleGnAl** [comment]
@dengking Can you try to delete the `third_party/iris` and build again?

**Comment by littleGnAl** [comment]
We encourage to use English so that the people can understand what's went wrong more easily if they encounter this issue.
