### ISSUE TITLE
Question  - How to create multiple RTC channel with or without token and with listener?

### ISSUE THREAD

**Issue by user97116** [AgoraIO/Agora-Flutter-SDK#691]
I tried   
var rtc = await RtcChannel.create(channelId);
rtc.setEventHandler(handler)

it not listens and not works.

**Comment by littleGnAl** [comment]
Hello @user97116, can you check the example for reference 
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/example/lib/examples/advanced/join_multiple_channel/join_multiple_channel.dart

**Comment by user97116** [comment]
@littleGnAl already checked, I followed according to example but it cause platform exception when I join or leave channel

**Comment by littleGnAl** [comment]
Do you create `RtcEngine` first?

**Comment by user97116** [comment]
Yes,  init engine then I create rtc channel

**Comment by littleGnAl** [comment]
Can you show your code?

**Comment by user97116** [comment]
@littleGnAl  when I use await like  await customChannel?.setClientRole(ClientRole.Broadcaster); it throw below error and without await it works fine. note this setClientRole is future method. and this happend in most of the methods in agora. I used agora_rtc_engine 5.2.0
flutter 3.0.1

// init agora
```
rtcEngine = await RtcEngine.create(appId);
rtcEngine!.enableLocalVideo(true);
rtcEngine!.startPreview();
```
// custom channel
```
customChannel = await RtcChannel.create(
  "custom-channel-" + DateTime.now().millisecondsSinceEpoch.toString(),
);
customChannel?.setEventHandler(
  RtcChannelEventHandler(
    error: (err) => print("c error: $err"),
    joinChannelSuccess: (channel, uid, elapsed) {
      print("c joinChannelSuccess: $channel $uid, $elapsed");
      users.add(uid);
    },
    leaveChannel: (stats) {
      print("c leaveChannel: ${stats.userCount}");
      users.clear();
    },
    userJoined: (uid, elapsed) {
      print("c userJoined: $uid, $elapsed");
      users.add(uid);
    },
    userOffline: (uid, elapsed) {
      print("c userOffline: $uid, $elapsed");
      users.remove(uid);
    },
  ),
);
if (isHost) {
  await customChannel?.setClientRole(ClientRole.Broadcaster);
} else {
  await customChannel?.setClientRole(ClientRole.Audience);
}
```

```
E/flutter ( 5005): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(-4, not supported, null, null)
E/flutter ( 5005): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter ( 5005): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:177
E/flutter ( 5005): <asynchronous suspension>
E/flutter ( 5005): #2      StreamingProvider.joinCustomChannel
package:temples/…/agora/streaming_provider.dart:230
E/flutter ( 5005): <asynchronous suspension>
```

**Comment by littleGnAl** [comment]
Can you try paste your appid in our example to see it works or not?
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/050949cf3229aa72e49e9f8a8564b5a9bfc59e71/example/lib/config/agora.config.dart#L5

**Comment by user97116** [comment]
@littleGnAl I already tried example project but still same error.
