### ISSUE TITLE
E/flutter ( 5005): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(-4, not supported, null, null)

### ISSUE THREAD

**Issue by user97116** [AgoraIO/Agora-Flutter-SDK#695]
when I use await like await customChannel?.setClientRole(ClientRole.Broadcaster); it throw below error and without await it works fine. note this setClientRole is future method. and this happend in most of the methods in agora. I used agora_rtc_engine 5.2.0
flutter 3.0.1

// init agora
```
rtcEngine = await RtcEngine.create(appId);
rtcEngine!.enableLocalVideo(true);
rtcEngine!.startPreview();
```
// custom channel
```
customChannel = await RtcChannel.create(
  "custom-channel-" + DateTime.now().millisecondsSinceEpoch.toString(),
);
customChannel?.setEventHandler(
  RtcChannelEventHandler(
    error: (err) => print("c error: $err"),
    joinChannelSuccess: (channel, uid, elapsed) {
      print("c joinChannelSuccess: $channel $uid, $elapsed");
      users.add(uid);
    },
    leaveChannel: (stats) {
      print("c leaveChannel: ${stats.userCount}");
      users.clear();
    },
    userJoined: (uid, elapsed) {
      print("c userJoined: $uid, $elapsed");
      users.add(uid);
    },
    userOffline: (uid, elapsed) {
      print("c userOffline: $uid, $elapsed");
      users.remove(uid);
    },
  ),
);
if (isHost) {
  await customChannel?.setClientRole(ClientRole.Broadcaster);
} else {
  await customChannel?.setClientRole(ClientRole.Audience);
}
```
E/flutter ( 5005): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(-4, not supported, null, null)
E/flutter ( 5005): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter ( 5005): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:177
E/flutter ( 5005): <asynchronous suspension>
E/flutter ( 5005): #2      StreamingProvider.joinCustomChannel
package:temples/…/agora/streaming_provider.dart:230
E/flutter ( 5005): <asynchronous suspension>
```

**Comment by littleGnAl** [comment]
-4 means you call an unsupported function of the specific platform, it there any other function you called?

**Comment by user97116** [comment]
I am using android @littleGnAl

**Comment by user97116** [comment]
all this methods @littleGnAl 
```
customChannel?.leaveChannel();//RtcChannel
customChannel?.setClientRole(ClientRole.Broadcaster);
customChannel?.joinChannel(
      null,
      null,
      0,
      ChannelMediaOptions(
        publishLocalVideo: true,
        publishLocalAudio: true,
      ),
    );
 _mediaRecorder?.startRecording(MediaRecorderConfiguration(storagePath: p));


```

**Comment by littleGnAl** [comment]
Can you try temporary comment out the ` _mediaRecorder?.startRecording(MediaRecorderConfiguration(storagePath: p));`

**Comment by user97116** [comment]
commented but same error @littleGnAl 
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(-4, not supported, null, null)`

note: when I removed await then it works with await it causes same error

**Comment by littleGnAl** [comment]
It's there any log from the error callback?

**Comment by littleGnAl** [comment]
Have you called `setChannelProfile` function?

**Comment by faisal061213** [comment]
E/flutter ( 4033): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
how to solve this problem
