### ISSUE TITLE
iOS存在崩溃现象

### ISSUE THREAD

**Issue by liangdas** [AgoraIO/Agora-Flutter-SDK#696]
**Describe the bug**
[5.0.1-rc.1](https://github.com/AgoraIO/Agora-Flutter-SDK/compare/v5.0.0...v5.0.1-rc.1) (2022-03-13)

出错堆栈

0	CoreFoundation
___exceptionPreprocess + 216
1	libobjc.A.dylib
_objc_exception_throw + 56
2	CoreFoundation
-[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3	Foundation
-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 128
4	Flutter
0x0000000109d64000 + 74720
5	agora_rtc_engine
EventHandler::OnEvent(char const*, char const*) + 300
6	AgoraRtcWrapper
agora::iris::rtc::RtcEngineEventHandler::onApiCallExecuted(int, char const*, char const*) + 1868
7	AgoraRtcKit
createAgoraRtcEngine + 143728
8	AgoraRtcKit
createAgoraRtcEngine + 142700
9	AgoraRtcKit
0x0000000107e34000 + 2667920
10	AgoraRtcKit
0x0000000107e34000 + 2667776
11	AgoraCore
ahpl_perf_set_callback + 1476
12	AgoraCore
ahpl_mpq_itc_ack + 252
13	AgoraCore
ahpl_mpq_loop + 76
14	AgoraCore
ahpl_perf_set_callback + 2336
15	AgoraCore
ahpl_profile_clear_registered + 2496
16	libsystem_pthread.dylib
__pthread_start + 288
17	libsystem_pthread.dylib
_thread_start + 8

-------

出错堆栈

0	agora_rtc_engine
-[AgoraRtcChannelPlugin dealloc] + 36
1	agora_rtc_engine
-[AgoraRtcChannelPlugin dealloc] + 32
2	agora_rtc_engine
-[AgoraRtcEnginePlugin .cxx_destruct] + 52
3	libobjc.A.dylib
object_cxxDestructFromClass(objc_object*, objc_class*) + 112
4	libobjc.A.dylib
_objc_destructInstance + 88
5	libobjc.A.dylib
__objc_rootDealloc + 52
6	agora_rtc_engine
-[AgoraRtcEnginePlugin dealloc] + 108
7	libsystem_blocks.dylib
__Block_release + 148
8	Flutter
0x0000000109374000 + 81872
9	libsystem_blocks.dylib
__Block_release + 148
10	Flutter
0x0000000109374000 + 238792
11	Flutter
0x0000000109374000 + 238868
12	Flutter
0x0000000109374000 + 273376
13	Flutter
0x0000000109374000 + 267656
14	Flutter
0x0000000109374000 + 4050748
15	Flutter
0x0000000109374000 + 4049088
16	Flutter
0x0000000109374000 + 80660
17	Flutter
0x0000000109374000 + 64608
18	CoreFoundation
___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
19	CoreFoundation
____CFXRegistrationPost1_block_invoke + 64

-------

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by littleGnAl** [comment]
This bug should be fixed, please try `agora_rtc_engine: 5.2.0`.

**Comment by liangdas** [comment]
agora_rtc_engine: 5.2.0 更穿山甲短视频SDK冲突，会直接崩溃，因为这个原因才降级到[5.0.1-rc.1](https://github.com/AgoraIO/Agora-Flutter-SDK/compare/v5.0.0...v5.0.1-rc.1)

**Comment by littleGnAl** [comment]
Is there any crash log of `agora_rtc_engine: 5.2.0`

**Comment by liangdas** [comment]
没有捕获到崩溃日志，就是闪退了
Lost connection to device.

-[AVMDLDataLoader _removeRepeatedUrls:] [Line 459] test code Urls before: (
    "http://v6-opensdksv.onewsvod.com/1b594757a8d56c94ad397f9f10859cb3/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67",
    "http://v3-opensdksv.onewsvod.com/fe41d8f617ec301377a54e1323200698/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67"
)
-[AVMDLDataLoader _removeRepeatedUrls:] [Line 478] test code Urls after: (
    "http://v6-opensdksv.onewsvod.com/1b594757a8d56c94ad397f9f10859cb3/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67",
    "http://v3-opensdksv.onewsvod.com/fe41d8f617ec301377a54e1323200698/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67"
)
-[AVMDLDataLoader proxyUrlByKey:rawKey:size:urls:] [Line 254] baseURL:http://127.0.0.1:58052  qury:?rk=v0d016g10000c9pn0tjc77u17ohdjosg&k=15cbf813c15ca7e1f83e31a59e8756a4&u0=http%3A%2F%2Fv6-opensdksv.onewsvod.com%2F1b594757a8d56c94ad397f9f10859cb3%2F62b29e91%2Fvideo%2Ftos%2Fcn%2Ftos-cn-ve-0022%2Fd0f4b8e084f54bc585ffbde20014f9ac%2F%3Fa%3D34%26ch%3D0%26cr%3D1%26dr%3D6%26er%3D0%26lr%3Dtoutiao_open%26cd%3D0%7C0%7C0%7C1%26cv%3D1%26br%3D548%26bt%3D548%26cs%3D1%26ds%3D6%26ft%3DeltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8%26mime_type%3Dvideo_mp4%26qs%3D0%26rc%3DaDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D%26l%3D2022061512455601021121115314FCFA67&u1=http%3A%2F%2Fv3-opensdksv.onewsvod.com%2Ffe41d8f617ec301377a54e1323200698%2F62b29e91%2Fvideo%2Ftos%2Fcn%2Ftos-cn-ve-0022%2Fd0f4b8e084f54bc585ffbde20014f9ac%2F%3Fa%3D34%26ch%3D0%26cr%3D1%26dr%3D6%26er%3D0%26lr%3Dtoutiao_open%26cd%3D0%7C0%7C0%7C1%26cv%3D1%26br%3D548%26bt%3D548%26cs%3D1%26ds%3D6%26ft%3DeltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8%26mime_type%3Dvideo_mp4%26qs%3D0%26rc%3DaDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D%26l%3D2022061512455601021121115314FCFA67
-[AVMDLDataLoader _removeRepeatedUrls:] [Line 459] test code Urls before: (
    "http://v6-opensdksv.onewsvod.com/1b594757a8d56c94ad397f9f10859cb3/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67",
    "http://v3-opensdksv.onewsvod.com/fe41d8f617ec301377a54e1323200698/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67"
)
-[AVMDLDataLoader _removeRepeatedUrls:] [Line 478] test code Urls after: (
    "http://v6-opensdksv.onewsvod.com/1b594757a8d56c94ad397f9f10859cb3/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67",
    "http://v3-opensdksv.onewsvod.com/fe41d8f617ec301377a54e1323200698/62b29e91/video/tos/cn/tos-cn-ve-0022/d0f4b8e084f54bc585ffbde20014f9ac/?a=34&ch=0&cr=1&dr=6&er=0&lr=toutiao_open&cd=0%7C0%7C0%7C1&cv=1&br=548&bt=548&cs=1&ds=6&ft=eltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8&mime_type=video_mp4&qs=0&rc=aDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D&l=2022061512455601021121115314FCFA67"
)
-[AVMDLDataLoader proxyUrlByKey:rawKey:size:urls:] [Line 254] baseURL:http://127.0.0.1:58052  qury:?rk=v0d016g10000c9pn0tjc77u17ohdjosg&k=15cbf813c15ca7e1f83e31a59e8756a4&u0=http%3A%2F%2Fv6-opensdksv.onewsvod.com%2F1b594757a8d56c94ad397f9f10859cb3%2F62b29e91%2Fvideo%2Ftos%2Fcn%2Ftos-cn-ve-0022%2Fd0f4b8e084f54bc585ffbde20014f9ac%2F%3Fa%3D34%26ch%3D0%26cr%3D1%26dr%3D6%26er%3D0%26lr%3Dtoutiao_open%26cd%3D0%7C0%7C0%7C1%26cv%3D1%26br%3D548%26bt%3D548%26cs%3D1%26ds%3D6%26ft%3DeltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8%26mime_type%3Dvideo_mp4%26qs%3D0%26rc%3DaDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D%26l%3D2022061512455601021121115314FCFA67&u1=http%3A%2F%2Fv3-opensdksv.onewsvod.com%2Ffe41d8f617ec301377a54e1323200698%2F62b29e91%2Fvideo%2Ftos%2Fcn%2Ftos-cn-ve-0022%2Fd0f4b8e084f54bc585ffbde20014f9ac%2F%3Fa%3D34%26ch%3D0%26cr%3D1%26dr%3D6%26er%3D0%26lr%3Dtoutiao_open%26cd%3D0%7C0%7C0%7C1%26cv%3D1%26br%3D548%26bt%3D548%26cs%3D1%26ds%3D6%26ft%3DeltnY22Hjal9MyBMyqsQ1-C5qSYkf81EDtG4KUYxAq8%26mime_type%3Dvideo_mp4%26qs%3D0%26rc%3DaDk3OzNnNjk6O2Y2MzVlZEBpanJncjQ6ZndxPDMzNDkzM0A2YS0vMDMvXzAxYV9iMGMuYSNwZ2U0cjRnLW1gLS1kLmFzcw%3D%3D%26l%3D2022061512455601021121115314FCFA67
【BytedanceUnion-Lucidum-v3.5.0.1】【BytedanceUnion】Add request: LCDCustomRequest
Lost connection to device.

**Comment by littleGnAl** [comment]
@liangdas It seems I can not get more information about the crash from the logs, I think a reproducible example may be helpful.
