### ISSUE TITLE
The symbol is packaged unexpectedly, we will fix it in the next release, you can add the `packagingOptions` to your `build.gradle` file to temporarily remove it at this time

### ISSUE THREAD

**Issue by ali-hajeh** [AgoraIO/Agora-Flutter-SDK#699]
The symbol is packaged unexpectedly, we will fix it in the next release, you can add the `packagingOptions` to your `build.gradle` file to temporarily remove it at this time
```gradle
packagingOptions {
      exclude "**/libAgoraRtcWrapperSymbol.so"
 }
```

_Originally posted by @littleGnAl in https://github.com/AgoraIO/Agora-Flutter-SDK/issues/631#issuecomment-1074780686_

The agora package in flutter is increasing my application size by 30 mb which is absolutely ridiculous. Excluding this part of the package did nothing to the size. Can you please help me out?

**Comment by ali-hajeh** [comment]
@littleGnAl

**Comment by lotus-x** [comment]
Such a small issue still not fixed, disappointed.

**Comment by littleGnAl** [comment]
The symbol had been removed, you can try `agora_rtc_engine: ^5.2.0`.
I think the config should be working fine, you can view what caused the increasing size on Android Studio of your APK.
