### ISSUE TITLE
Why do we need Agora App ID?

### ISSUE THREAD

**Issue by Zohalmohal** [AgoraIO/Agora-Flutter-SDK#701]
I am interested to know, if the Agora is a completely open source and free SDK/library, why do we need to signup on their site and grab APP ID and all the example codes need this APP ID?

Is that mean we don't have access to complete code and Agora works like an API and maybe in future it won't be free to use?

**Comment by LichKing-2234** [comment]
The underlying SDK uses the SDK of the sound network. The SDK itself is not open source, and it can only be used after registering Agora appid. The open source of the shutter SDK is the wrapper part of the upper layer. Then, whether you use the fluent SDK or the native SDK, you can use the newly registered account for 10000 minutes free every month. This behavior is common.
