### ISSUE TITLE
Unable to start Channel Media Relay

### ISSUE THREAD

**Issue by bhavin-concetto** [AgoraIO/Agora-Flutter-SDK#707]
**Describe the bug**
I have implemented Media Relay functionality as per described: https://docs.agora.io/en/Interactive%20Broadcast/media_relay_android?platform=Android

**To Reproduce**
1. create two channel
2. call startChannelMediaRelay
3. called ChannelMediaRelayStateChanged with ServerErrorResponse

**Expected behavior**
There should be some mechanism to know the actual error.

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: 7.1

**Comment by littleGnAl** [comment]
Can you try our example to see if it works or not?
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/example/lib/examples/advanced/channel_media_relay/channel_media_relay.dart

**Comment by bhavin-concetto** [comment]
@littleGnAl  We have tried this but look like it is Agora server issue so raised ticket in Agora support.
