### ISSUE TITLE
Error when upload an app to app store apple

### ISSUE THREAD

**Issue by adham-ashraf77** [AgoraIO/Agora-Flutter-SDK#711]
<img width="917" alt="Screen Shot 2022-07-05 at 10 56 12 AM" src="https://user-images.githubusercontent.com/55947445/177290701-17e4d7f4-14ca-4e09-8db7-aadb6107c673.png">

seems there are some errors with the agora package with CFBundleShortVersionString must be 3 parts only not 4 can you fix it to complete the upload of the app?

**Comment by littleGnAl** [comment]
Can you provide the flutter doctor log and which version of `agora_rtc_engine` you used?

**Comment by adham-ashraf77** [comment]
5.2.0  and 5.1.1 are the same error when upload app store

**Comment by LichKing-2234** [comment]
you can find the info.plist file in AgoraRtcWrapper.framework and modify the version to x.x.x before we fix it.

**Comment by adham-ashraf77** [comment]
@LichKing-2234 
tried to modify the version but didn't work still read the old number because the file generated after 
flutter build ios

**Comment by LichKing-2234** [comment]
Yes, could pls use Xcode archive to release?

**Comment by adham-ashraf77** [comment]
after I use flutter build ios 
I open Xcode then product then archive

**Comment by adham-ashraf77** [comment]
okay, I will try but when the fix will be released?

**Comment by LichKing-2234** [comment]
> okay, I will try but when the fix will be released?

Yes

**Comment by adham-ashraf77** [comment]
@littleGnAl 
Can be next week we have an important release and we need to upload the app and the solution you provide that I manually edit the number to 3.6.2 only not working and give the same error that is shown above in the upper image.

**Comment by plutoless** [comment]
@adham-ashraf77  as @LichKing-2234 mentioned this is because flutter build ios will execute pod install again and overwrite your manual edit. if you can archive the app w/o flutter build then it should work.

**Comment by adham-ashraf77** [comment]
@plutoless 
I will try again thank you 🙏

**Comment by OmarHamed553** [comment]
i'm having the same issue when will this get resolved i can't upload the app to app store i tried downgrading to 5.0.1 ,5.0.0 , 5.1.0 i also tried with Xcode archive still the same this issue should be resolved immediately !

**Comment by OmarHamed553** [comment]
@adham-ashraf77 any luck fixing the issue it would be great to share the temporarily fix you've done if it worked

**Comment by adham-ashraf77** [comment]
@OmarHamed553 
you can edit the version string form Xcode after archive and the path in error message it works fine for me

**Comment by OmarHamed553** [comment]
is it possible to show me a capture of how to change the string form in xCode ?

**Comment by OmarHamed553** [comment]
@adham-ashraf77

**Comment by adham-ashraf77** [comment]
Can you email me at 
adhamashraf51@gmail.com
Because i don't have mac right now

**Comment by OmarHamed553** [comment]
sure @adham-ashraf77

**Comment by OmarHamed553** [comment]
sent already @adham-ashraf77

**Comment by littleGnAl** [comment]
Please try `agora_rtc_engine: ^5.3.0`.
