### ISSUE TITLE
java.lang.ClassNotFoundException: io.agora.rtc.ss.ScreenSharingClient

### ISSUE THREAD

**Issue by matrixccp** [AgoraIO/Agora-Flutter-SDK#712]
I/AudioManager(25902): In isBluetoothScoAvailableOffCall(), calling appilication: xxxxxx, return value: true
I/AudioManager(25902): In isBluetoothScoOn(), calling application: xxxxxxxx
D/spdlog  (25902): [2022-07-05 20:47:50.214] [0] [debug] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/iris_rtc_engine.cc:114 CallApi ret 0 result 
D/spdlog  (25902): [2022-07-05 20:47:50.215] [0] [debug] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/iris_rtc_engine.cc:104 CallApi api_type 1 params {"sync":true}
E/spdlog  (25902): [2022-07-05 20:47:50.215] [0] [error] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/internal/rtc_engine_event_handler.cc:56 onError err 18 msg nullptr
W/System.err(25902): java.lang.ClassNotFoundException: io.agora.rtc.ss.ScreenSharingClient
W/System.err(25902):    at java.lang.Class.classForName(Native Method)
W/System.err(25902):    at java.lang.Class.forName(Class.java:454)
W/System.err(25902):    at java.lang.Class.forName(Class.java:379)
W/System.err(25902):    at io.agora.rtc.internal.RtcEngineImpl.stopScreenCapture(RtcEngineImpl.java:922)
W/System.err(25902):    at io.agora.rtc.internal.RtcEngineImpl.doDestroy(RtcEngineImpl.java:353)
W/System.err(25902):    at io.agora.rtc.RtcEngine.destroy(RtcEngine.java:122)
W/System.err(25902):    at io.agora.iris.rtc.IrisRtcEngine.CallApi(Native Method)
W/System.err(25902):    at io.agora.iris.rtc.IrisRtcEngine.callApi(IrisRtcEngine.java:41)
W/System.err(25902):    at io.agora.agora_rtc_engine.CallApiMethodCallHandler.callApi(AgoraRtcEnginePlugin.kt:41)
W/System.err(25902):    at io.agora.agora_rtc_engine.CallApiMethodCallHandler.onMethodCall(AgoraRtcEnginePlugin.kt:96)
W/System.err(25902):    at io.agora.agora_rtc_engine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.kt:245)
W/System.err(25902):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(25902):    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(25902):    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/System.err(25902):    at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(25902):    at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(25902):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(25902):    at android.os.Looper.loop(Looper.java:236)
W/System.err(25902):    at android.app.ActivityThread.main(ActivityThread.java:8060)
W/System.err(25902):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(25902):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
W/System.err(25902):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
W/System.err(25902): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.agora.rtc.ss.ScreenSharingClient" on path: DexPathList[[zip file "/data/app/~~kMv9y4tV7tTCVyxUArGs3g==/xxxx4mU9lRCziwUpf5phvrmSIg==/base.apk"],nativeLibraryDirectories=[/data/app/~~kMv9y4tV7tTCVyxUArGs3g==/-4mU9lRCziwUpf5phvrmSIg==/lib/arm64, /data/app/~~kMv9y4tV7tTCVyxUArGs3g==/-4mU9lRCziwUpf5phvrmSIg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
W/System.err(25902):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
W/System.err(25902):    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err(25902):    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(25902):    ... 22 more
D/agora-jni(25902): android bridge destroy done...
D/spdlog  (25902): [2022-07-05 20:47:50.249] [0] [debug] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/iris_rtc_engine.cc:114 CallApi ret 0 result 
D/spdlog  (25902): [2022-07-05 20:47:50.253] [0] [debug] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/iris_rtc_engine.cc:104 CallApi api_type 1 params {"sync":true}
D/spdlog  (25902): [2022-07-05 20:47:50.254] [0] [debug] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/iris_rtc_engine.cc:114 CallApi ret 0 result 
I/flutter (25902): Join channel  error: createChannel failed errorCode:-1
I/flutter (25902): Logout error: logout failed errorCode:-1

**Comment by littleGnAl** [comment]
It's an exception caught by the native SDK internally, it's not actually a crash.
