### ISSUE TITLE
onRecordFrame is not work

### ISSUE THREAD

**Issue by LeeeYudE** [AgoraIO/Agora-Flutter-SDK#714]
I registerAudioFrameObserver in the AgoraRtcEnginePlugin.kt , it is worked , but on the onRecordFrame Method , the AudioFrame is no data , audioFrame.samples.hasArray() is false.

**Comment by littleGnAl** [comment]
Hello @LeeeYudE , can you share how your code?

**Comment by LeeeYudE** [comment]
sure，My code is as follows：
https://github.com/LeeeYudE/Agora-Flutter-SDK/blob/master/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraRtcEnginePlugin.kt

**Comment by littleGnAl** [comment]
You can try this feature to do this
https://github.com/AgoraIO/Agora-Flutter-SDK#experimental-features

**Comment by LeeeYudE** [comment]
my code is fork in https://github.com/AgoraIO/Agora-Flutter-SDK，i want to add registerAudioFrameObserver Method in the AgoraRtcEnginePlugin.kt，but it is not work

**Comment by LeeeYudE** [comment]
when i used buffer.flip() , ByteBuffer has no data , so i delete it
