### ISSUE TITLE
Detect the other user is in app

### ISSUE THREAD

**Issue by Tsagaanbayr1** [AgoraIO/Agora-Flutter-SDK#718]
**Is your feature request related to a problem? Please describe.**
My app has a counter in two-person video call sessions. The counter stops when a user is inactive (clicks the home button, locks the screen). I solved the problem by disabling their video on inactive. But the problem appeared after our app got a new user feature muting their local_video.

**Describe the solution you'd like**
Add the state to the `VideoRemoteStateReason`.

**Describe alternatives you've considered**
Create a new event that allows passing a string parameter. So we could use it to pass JSON or a string value. (That could help many other problems. But on the other hand, developers would use it for other reasons.

**Additional context**
There's no other way of fixing that. Our app's development awaits the next release of the package.

**Comment by plutoless** [comment]
@Tsagaanbayr1 
you may build your own server to keep connection with clients, and use your server to notify other clients that your app is inactive.
we also provide a message sdk maybe you can also consider using that, https://docs.agora.io/en/Real-time-Messaging/landing-page?platform=Windows
