### ISSUE TITLE
Flutter 3, Agora 5.2.0 - cannot find symbol

### ISSUE THREAD

**Issue by maerlynflagg** [AgoraIO/Agora-Flutter-SDK#719]
**Describe the bug**
`agora_rtc_engine: ^5.2.0`
`Flutter 3.0.5`

with `flutter build appbundle --release` all is fine and install the bundle over Play Store, all is fine. 

but, if i want to debug the app in a Android Simulator (Pixel 3 API 29 template), then it ends in:

```

C:\...\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: cannot find symbol
      flutterEngine.getPlugins().add(new io.agora.agora_rtc_engine.AgoraRtcEnginePlugin());
                                                                  ^
  symbol:   class AgoraRtcEnginePlugin
  location: package io.agora.agora_rtc_engine
``` 
if i try to debug on a real device, the issue still exists.

i'm not sure. i searched on Google and found some solutions:

- flutter clean & build again
- flutter clean, delete pub cache and build again
- flutter clean, cache repair und build again

nothing helped.

**Expected behavior**
it should working in simulator too, not only on real devices.

**Comment by littleGnAl** [comment]
The integration test is run with the simulator and it works fine, I think it's better to check your build.gradle file to see if there is any configuration that affects the simulator.

**Comment by maerlynflagg** [comment]
for 3 months all worked fine in debugging mode.

for a new app version of my app i have done 3 relevant things:

1. flutter upgrade to version 3.0.5
2. update packages in pubspec.xaml like Agora to 5.2.0
3. the only change in build.gradle: compileSdkVersion from 31 to 33, cause is needed.

so, i downgraded compileSDKVersion back to 31, Flutter back to 2.10.5 and some other packages back to an old version.  cleaned the pub cache again. cleaned the flutter build again and it works.

then, i upgrade back all. cleaned all again. now it works, too. issue is gone, after downgrade and upgrade again.

this is crazy.
