### ISSUE TITLE
5.3 Android - error joining a call: "PlatformException (PlatformException(, Not except type: uid, null, null))"

### ISSUE THREAD

**Issue by dgilperez** [AgoraIO/Agora-Flutter-SDK#722]
After upgrading, when I try to join a call I get this `PlatformException`

```
Not except type: uid
```

This is not happening on 5.2, without any other change.

This happens when calling `joinChannel(null, channelName, null, uid)`

**To Reproduce**
1. Wrap your join call on a try-catch
2. Join a call
3. See error captured

**Expected behavior**

Joining a call to proceed.

 - Flutter 3.0.5
 - Device: Poco M3
 - OS: Android

**Comment by littleGnAl** [comment]
Can you show more detail about the stack trace of this exception?

**Comment by acanteroruiz** [comment]
that´s the stacktrace with the error @dgilperez commented 

` [0m
[log] [31m PlatformException(, Not except type: uid, null, null) [0m
[log] [31m #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      _LiveVideoViewState._startAgora (package:rosita/features/live/live_video_view.dart:128:9)
<asynchronous suspension>
 [0m`

**Comment by littleGnAl** [comment]
@acanteroruiz 
Can you share what's the type of `uid`?

**Comment by acanteroruiz** [comment]
Hi @littleGnAl , uId is type String

**Comment by dgilperez** [comment]
@acanteroruiz is correct. What more information do you need? 

For reference, our current status is of major blockade:

* Flutter 3 will not work with Agora 4.2 (android will not compile). We're already in flutter 3.
* Agora 5.3, will not work for Android (this issue) nor iOS (crash seen in other issues here)
* Agora 5.2, crashes with iOS

Are you aware of this? Is there anything we can do to work around this blockade? Can you share some timeline on potential fixes from your side? We need to plan the next release ... 

Thanks

**Comment by littleGnAl** [comment]
The uid should be `int` for the [joinChannel](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/f76a0563482a5f3ff973e4e2cff802f04d57f5ef/lib/src/rtc_engine.dart#L187
) function.

I'm not sure why the uid with `String` type works with the `joinChannel` function in your case if you need to use uid of `String` type you should use the [joinChannelWithUserAccount](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/f76a0563482a5f3ff973e4e2cff802f04d57f5ef/lib/src/rtc_engine.dart#L481) function.

Here an example:
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/f76a0563482a5f3ff973e4e2cff802f04d57f5ef/example/lib/examples/basic/string_uid/string_uid.dart#L74

**Comment by dgilperez** [comment]
@littleGnAl sorry for the confusion - `joinChannel` is in deed accepting an `int` as uid. 

We are now able to operate apparently without issues. As you suggested, we moved from `joinChannel` to `joinChannelWithUserAccount` and suddenly everything works. 

Digging this a bit deeper, it seems both methods use different API endpoints. A bit surprising if you ask me, but that's also probably a good hint for someone more knowledgeable to dig deeper: the first method is totally broken for us, the second works.
