### ISSUE TITLE
Broadcaster can't hear other users, but the others can hear him/her

### ISSUE THREAD

**Issue by nizwar** [AgoraIO/Agora-Flutter-SDK#723]
In my application, once user take the Mic, we change the user role into broadcaster, sometime this user can be heard by everyone in the room, but he/she can't hear another broadcaster

I'm not sure if it related with my other issue #687, this happened without any logs from crashlytics or very hard to produce (it must be with user with slow connection) and it suddenly happend since last couple weeks, this happened on agora 5.2.0 - 5.3.0

**Comment by littleGnAl** [comment]
agora_rtc_engine: 5.3.0 is based on the native SDK 3.7.0, I think it's better to raise a new ticket to the Agora Support.

**Comment by nizwar** [comment]
I'll close it for now during open ticket, i'll reopen once i found something in logs
