### ISSUE TITLE
Crash in iOS Flutter app

### ISSUE THREAD

**Issue by krishnashetty0** [AgoraIO/Agora-Flutter-SDK#731]
Please see the error details below, please let me know if you need more details:

Fatal Exception: FlutterError
PlatformException(-7, S-SDK/rtc/cxx/src/iris_rtc_engine.cc:116 CallApi ret -7 result ams {}, null, null). Error thrown null.
StandardMethodCodec.decodeEnvelope

Crashed: com.apple.main-thread
0x0000000000000000
0
FirebaseCrashlytics
FIRCLSProcessRecordAllThreads + 184
7
FirebaseCrashlytics
-[FIRCrashlytics recordOnDemandExceptionModel:] + 192
8
Runner
FLTFirebaseCrashlyticsPlugin.m - Line 175
-[FLTFirebaseCrashlyticsPlugin recordError:withMethodCallResult:] + 175
9
Runner
FLTFirebaseCrashlyticsPlugin.m - Line 117
-[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:] + 117
10
Flutter
(Missing UUID d24b4305a5d8348c8a0909c859505f3a)
22
UIKitCore
UIApplicationMain + 336
23
Runner
AppDelegate.swift - Line 5
main + 5
24
(Missing)

com.apple.uikit.eventfetch-thread

**Comment by littleGnAl** [comment]
I think you should make sure your appId is valid
