### ISSUE TITLE
Own video get freeze when user go to background and come back to foreground.

### ISSUE THREAD

**Issue by Rishabhios** [AgoraIO/Agora-Flutter-SDK#733]
[**Smartphone]([url]([url](url))) (please complete the following information):**
 - Device: iphone XS MAX
 - OS: 15.5

**Comment by littleGnAl** [comment]
Check this for reference.
https://developer.apple.com/documentation/avfoundation/media_playback/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio?language=objc
