### ISSUE TITLE
audioVolumeIndication not working only on iOS.

### ISSUE THREAD

**Issue by Naoki-Hidaka** [AgoraIO/Agora-Flutter-SDK#736]
**Describe the bug**
```
await _engine?.enableAudioVolumeIndication(250, 10, true);
_engine?.setEventHandler(RtcEngineEventHandler(
    audioVolumeIndication: (speakers, v) {
        print('audioVolumeIndication');      
    },
));
```

When I run it on iOS, nothing is output
I do the same code for Android, but it outputs.

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS 15.5
 - SDK Version: 5.1.0

**Comment by littleGnAl** [comment]
Hello @Naoki-Hidaka, did you call the `joinChannel` function?

**Comment by Naoki-Hidaka** [comment]
@littleGnAl 
Hi
Yes, i called `joinChannel` function.

**Comment by ThangD** [comment]
@littleGnAl Same issue here.

**Comment by littleGnAl** [comment]
You can check this example for reference, it works on the iOS simulator
https://github.com/AgoraIO/Agora-Flutter-SDK/pull/737/files#diff-a997157bc5be883f1d56dd59dae57e94f041a6c43bfc22aa572c6526a0fa77c2
